[[req_decorations_crs-grid-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/cartographic-layout/grid-crs-definition*
^|A |The map operation SHALL support an optional parameter `grid-crss` with the characteristics defined in the OpenAPI Specification 3.0 fragment
[source,YAML]
----
  name: grid-crss
  in: query
  required: false
  description: Add one or more grid crss or graticules into the map
  style: form
  explode: false
  schema:
    type: array
    items:
      type: string
----
^|B |Each name in the comma separated list in the value of the `grid-crss` SHALL be interpreted as a CRS. For each CRS in the list, if the CRS coordinates are lat/long the server shall interpret the request for a graticule and otherwise the server shall interpret the request of a CRS grid.
^|B |The implementation SHALL support any of the CRSs listed in the collection (or collections) description. If the list of supported CRS is not present, only http://www.opengis.net/def/crs/OGC/1.3/CRS84 SHALL be supported.
^|C |The implementation SHALL support CRS expressed as URIs or as safe CURIEs.
^|D |The absence of the parameter `grid-crss` SHALL be interpreted as "neither CRS grid nor graticule in the map".
|===

NOTE: A CURIE {authority}[-{objectType}]:{id} would map to the following OGC URI: http://www.opengis.net/def/{objectType}/{authority}/0/{id}. If -{objectType} is missing, the default object type is crs.