== Requirement Class "Tiles Tile Matrix Set"

=== Overview

[[tiles-tmxs-overview]]

include::requirements/tiles/requirements_class_tmxs.adoc[]

The _tiles core_ clause states that if there is no information on TileMatrixSet, the service can behave as a service that supports the eight TileMatrixSets defined in the Annex D.1 of the OGC 17-083r2 standard. This extension adds all necessary elements to support other TileMatrixSets.

The entry point is a `Landing page` (path `/`).

The `Landing page` provides links to
* the `API definition` (path `/api`, link relation `service`),
* the `Conformance declaration` (path `/conformance`, link relation `conformance`), and
* the `Collections` (path `/collections`, link relation `data`).
* the `TileMatrixSets` (path `/tileMatrixSets`, link relation `tileMatrixSet`).

=== API landing page

The landing page provides links to start exploring the resources offered by the API. It mainly consists in a list of links. The core of this standard does not add anything to the links required by OWS Common. This extension for TileMatrixSet requires new ones for TileMatrixSets on top of the common ones.

==== Response

include::requirements/tiles/tmxs/REQ_api-definition-success.adoc[]

In the landing page, in JSON format, the links are following the link schema defined in the OGC API Common. The following is an example fragment of the response of a OGC API tiles landing page

[[landingPage]]
.API Landing Page fragment
=================
[source,JSON]
----
[
  [...],
  {
    "href": "http://data.example.org/tileMatrixSet?f=json",
    "rel": "tileMatrixSets",
    "type": "application/json",
    "title": "List of tileMatrixSets implemented by this API in JSON",
  },
  {
    "href": "http://data.example.org/tileMatrixSet?f=html",
    "rel": "tileMatrixSets",
    "type": "text/html",
    "title": "List of tileMatrixSets implemented by this API in HTML",
  }
]
----
=================

With a `/collections` successful response it is possible to retrieve the list of collectionId and links to the /collections/{collectionId}.
With a /collections/{collectionId} successful response is s possible to discover the links to retrieve some tiles. The other tiles can be retrieved by following the /collections/{collectionId}/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol} template. Other tile paths are defined for other resource types that are not collections.

=== Declaration of conformance classes

==== Response

The conformance page mainly consists in a list of links. OWS Commmon already requires some links.

include::requirements/tiles/tmxs/REQ_conformance-success.adoc[]

In the conformance page (commonly in JSON format) the links are following the link schema defined in the OGC API Common. The following is an example fragment of the response of a OGC API tiles conformance information page

[[ConformancePage]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/core"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/tmxs"
    "http://www.opengis.net/spec/tilematrixset/1.0/req/tilematrixset2d"
    "http://www.opengis.net/spec/tilematrixset/1.0/req/json-tilematrixset2d"
    "http://www.opengis.net/spec/tilematrixset/1.0/req/tilematrixsetlimits2d"
    "http://www.opengis.net/spec/tilematrixset/1.0/req/json-tilematrixsetlimits2d"
  ]
}
=================

=== TileMatrixSets

==== Operation
include::requirements/tiles/tmxs/REQ_tilematrixsets-op.adoc[]

==== Response
include::requirements/tiles/tmxs/REQ_tilematrixsets-success.adoc[]

[[TileMatrixSetsResponseSchema]]
.Schema for the TileMatrixSets resource
=================
[source,YAML]
tileMatrixSets:
  type: array
  items:
    $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/schemas/id-link'
=================

[[TileMatrixSetsResponseCommonSchema]]
.Schema for id-link from OGC API Common used in TileMatrixSets resource and reproduced here for completeness.
=================
id-link:
  type: object
  description: |-
    Reusable object that contains an id to a resource and links where the object is described or a representation retrieved. Typically it is useful for paths like `\resources` and `\resources\{resourceId}`.   `\resources` will respond an array of id-link listing the `resourceId` and the links to get it. \collections and \collections\{collectionId} is an exception to this pattern.
    The fact that `links` is an array can be used to advertise the same object representation in different formats.
  required:
    - id
    - links
  properties:
    id:
      type: string
    title:
      type: string
    links:
      type: array
      minItems: 1
      items:
        $ref: '#/components/schemas/link'
=================

[[TileMatrixSetsResponseExample]]
.Example for the TileMatrixSets resource
=================
[source,JSON]
[
  {
    "id": "MyWebMercatorQuad",
    "title": "My Google Maps Compatible for the World",
    "links": [
      {
        "href": "https://data.example.org/tileMatrixSet/MyWebMercatorQuad",
        "rel": "tileMatrixSet",
        "type": "application/json"
      }
    ]
  }
]
=================

=== TileMatrixSet

==== Operation
include::requirements/tiles/tmxs/REQ_tilematrixset-op.adoc[]

==== Response
include::requirements/tiles/tmxs/REQ_tilematrixset-success.adoc[]

include::recommendations/tiles/tmxs/REC_tilematrixset-response.adoc[]

=== Collection
This extension modifies the content of the collection description returned by a successful \collection\{collectionId} request.

==== Collection extra properties

include::requirements/tiles/tmxs/REQ_stc-limits.adoc[]

=================
[source,JSON]
----
  "tiles": {
    "tileMatrixSetLinks": [
      {
        "type": "tileMatrixSetLink",
        "tileMatrixSet": "http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad",
        "tileMatrixSetLimits": [
          {
            "type": "tileMatrixSetLimits",
            "tileMatrix": "5",
            "minTileRow": 0,
            "maxTileRow": 1,
            "minTileCol": 3,
            "maxTileCol": 4
          }
        ]
      }
    ]
  }
----
=================
