== Scope

This International Standard specifies the behaviour of an API that provides access to Maps and Tiles in a manner independent of the underlying data store. This standard specifies discovery and query operations.

== Scope
This [OGC API Coverages](https://github.com/opengeospatial/ogc_api_coverages[https://github.com/opengeospatial/ogc_api_coverages]) specification establishes how to access maps and tiles in a manner independent of the underlying data store through [OpenAPI](https://www.openapis.org/[https://www.openapis.org/]). This standard specifies discovery and query operations.

=== Current scope:

* Discovery operations allow the API to be interrogated to determine its capabilities and retrieve information (metadata) about this distribution of tiles and maps. This includes the API definition as well as metadata about the feature collections provided through the API and the TileMatrixSets supported by this service.

* Retrieve of maps as defined by the WMS 1.3
* Retrieve of tiles as defined by the WMTS 1.0
* Query about a point in a map or a tile (GetFeatureInfo)
* Retrieve multiple tiles in a single request.
