== Requirement Class "Maps Maps"

This extension describes how a map can be retrieved by specifying a set of parameters that will determine its resolution (width, height, boundingbox and CRS).

The map can use the default style or it can select one of the styles available if the right extension is also added to the core.

=== General
include::requirements/maps/core/REQ_api-common.adoc[]

In practice, this means that the landing page and the conformance page follows OGC API Common core requirements (STILL TBD but mostly equivalent to the more general parts of WFS3.0 requirements but with the text generalized to other resource types). This standard provides extra additions to the OWS common requirements that are particular of tiles.

=== API landing page

The landing page provides links to start exploring the resources offered by the API. It mainly consists in a list of links. OWS Common already requires some common links that are enough for this core.

==== Response
No variations are required in the landing page.
With a /collections successful response it is possible to retrieve the list of collectionId and links to the /collections/{collectionId}.
With a /collections/{collectionId} successful response, it is possible to discover the links to retrieve some maps.
Note that other resources can also be retrieved as collections (e.g. coverages)

=== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists in a list of links. OWS Commmon already requires some links.

include::requirements/maps/core/REQ_conformance-success.adoc[]

In the conformance page (commonly in JSON format) the links are following the link schema defined in the OGC API Common. The following is an example fragment of the response of a OGC API Maps with the maps extension conformance information page.

[[ConformancePage]]
.Conformance Information Page fragment
=================
[source,JSON]
[
  "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
  "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
  "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core"
  "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/maps"
]
=================

=== Collections
TBD: What will happen with collections of coverages?

This standard includes dependencies on OWS Common collections. Collections are mandatory in the core of this standard because collections are the object that will be included in a tile.

Collections will enumerate the collectionId available in this API as well as basic information about each collectionId: id, title, description, extent, crs and links. This common response is considered enough for a general
description of the collection. to retrieve more information, you should use /collections/{collectionId}

NOTE: The collectionId substitutes the concept of "layer" in WMS.

=== Collection
This standard includes dependencies on OWS Common collection. The response of the operation is extended with the necessary information to formulate a map response for this collection.

==== Collection Links

The links included by the OGS API maps core are sufficient for this standard.

==== Collection extra parameters

A collection that can be retrieved as maps will add specific object in the collection information about that will contain specific information necessary to get tiles in the resource collection response. In this extension, the _maps_ section informs about the formats the maps can be retrieved,...

include::requirements/maps/core/REQ_sfc-formats.adoc[]

.Example of a tiles property in the collection response.
=================
[source,JSON]
  "maps": {
    "formats": [
      [
        "image/jpeg",
        "image/png"
      ]
    ]
  }
=================

=== Maps from one collection

This standard specifies how to get maps from a single collection.

==== Operation

include::requirements/maps/core/REQ_mc-op.adoc[]

Typical resources that can be retrieved as maps are: features (/collections/{collectionId}), coverages (/collections/{collectionId}/coverage/{coverageId} or /coverage/{coverageId}).

==== Parameter crs
include::requirements/maps/core/REQ_mc-crs-definition.adoc[]

==== Parameter bbox
include::requirements/maps/core/REQ_mc-bbox-definition.adoc[]

==== Parameter width
include::requirements/maps/core/REQ_mc-width-definition.adoc[]

==== Parameter height
include::requirements/maps/core/REQ_mc-height-definition.adoc[]

==== Parameter transparent
include::requirements/maps/core/REQ_mc-transparent-definition.adoc[]

==== Parameter bgcolor
include::requirements/maps/core/REQ_mc-bgcolor-definition.adoc[]

==== Response

A successful response of a tile request will be consistent with the type of resource requested. For features can be geojson of Mapbox vector tiles; coverages it my be a geotiff and for maps it can be a jpeg or a png.

include::requirements/tiles/core/REQ_tc-success.adoc[]

==== Error situations

A general summary of the HTTP status codes can be found in OWS Common.

If the parameter tileMatrixSetId is not available by the server for this resource or the parameters  tileMatrix, tileRow, tileCol are out-of-range, the status code of the response will be 404.
