== Requirement Class "Tiles Core"

=== Overview

[[tiles-core-overview]]

include::requirements/tiles/requirements_class_core.adoc[]

An API that implements this conformance class provides access to tiled resources of a link:https://www.w3.org/TR/vocab-dcat/#class-dataset[dataset]. In other words, the API is a link:https://www.w3.org/TR/vocab-dcat/#class-distribution[distribution] of that dataset. The OGC API features, for example, would be another distribution.

The entry point is a `Landing page` (path `/`).

The `Landing page` provides links to
* the `API definition` (path `/api`, link relation `service`),
* the `Conformance declaration` (path `/conformance`, link relation `conformance`), and
* the `Collections` (path `/collections`, link relation `data`).

The `API definition` describes the capabilities of the API that can be used by clients to retrieve resources from the API or by development tools to support the implementation of API servers and clients. Accessing the `API definition` using HTTP GET returns a description of the API.

The `Conformance declaration` states the requirements classes from standards or community specifications, identified by a URI, that the API conforms to. Clients can, but are not required to, use this information. Accessing the `Conformance declaration` using HTTP GET returns the list of URIs of requirements classes implemented by the API.

The tiles core does not mandate the inclusion of an explicit definition of any TileMatrixSet. The standard assumes that clients and services know about the eight TileMatrixSets defined in OGC 17-083r2 annex D and there is no need to communicate these definitions. An extension to the core provides the capability to include definitions of flexible TileMatrixSets.

This standard assumes that data is organized into one or more collections. `Collections` provides information about and access to the collections.

This document does not specify requirements for collections and they can consist on features, coverages, a resource that does not represent data per-se (e.g. an annotation) any other resource that can be represented in a tile. collectionId replaces the concept of layer in WMS and WMTS. Maps or tiles can be generated from one collection (or a combination of collections as an extension).

Accessing `Collections` using HTTP GET returns a response that contains at least the list of collections. Accessing `Collections/{collectionId}` using HTTP GET returns a description of a collection with an indication if the collection can be retrieved as a map or a tile or both. Accessing the items of a collections is out of the scope of this standard and you need to refer to other document standard describing OGC APIs for features or coverages. For each `Collection`, a link to metadata about the collection is available (path `/collections/{collectionId}`) with key information about the collection. This information includes:

* A local identifier for the collection that is unique for the dataset;
* An optional title and description for the collection;
* An optional extent that can be used to provide an indication of the spatial and temporal extent of the collection - typically derived from the data;
* A list of TileMatrixSetLink to the available tiling schemas supported by the collection (From the linked TileMatrixSet member the client can determine the coordinate reference systems (CRS) in which tiles may be returned by the API)

The `Collection` resource is available at path `/collections/{collectionId}`, often with more details than included in the `Collections` response.

=== General
include::requirements/tiles/core/REQ_api-common.adoc[]

In practice, this means that the landing page and the conformance page follows OGC API Common core and collections requirements (STILL TBD but mostly equivalent to the more general parts of WFS3.0 requirements but with the text generalized to other resource types). This standard provides extra additions to the OWS common requirements that are particular to tiles.

=== API landing page

The landing page provides links to start exploring the resources offered by the API. It mainly consists in a list of links. OWS Common already requires some common links that are enough for this core.

==== Response
No variations are required in the landing page.
With a /collections successful response it is possible to retrieve the list of collectionId and links to the /collections/{collectionId}.
With a /collections/{collectionId} successful response, it is possible to discover the links to retrieve some tiles. The other tiles can be retrieved by following the /collections/{collectionId}/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol} template.
Note that other resources an also be retrieved as collections.

=== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists in a list of links. OWS Commmon already requires some links.

include::requirements/tiles/core/REQ_conformance-success.adoc[]

In the conformance page (commonly in JSON format) the links are following the link schema defined in the OGC API Common. The following is an example fragment of the response of a OGC API tiles conformance information page

[[ConformancePage]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/core"
  ]
}
=================

=== Collections
TBD: What will happen with collections of coverages?

This standard includes dependencies on OWS Common collections. Collections are mandatory in the core of this standard because collections are the object that will be included in a tile.

Collections will enumerate the collectionId available in this API as well as basic information about each collectionId: id, title, description, extent, crs and links. This common response is considered enough for a general
description of the collection. to retrieve more information, you should use /collections/{collectionId}

NOTE: The collectionId substitutes the concept of "layer" in WMTS.

=== Collection
This standard includes dependencies on OWS Common collection. The response of the operation is extended with the necessary information to formulate a tile response for this collection.

==== Collection Links

include::requirements/tiles/core/REQ_stc-tile-examples.adoc[]

One common order used in URL templates for tiles is .../tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol} this standard allows for other URL template dispositions.

[#URL_template_tile,reftext='{table-caption} {counter:table-num}']
.URI template variables for tiles and possible values
[cols="30,35,70,30",options="header"]
!===
|URL template variable |Meaning |Possible values
|TileMatrixSetId |tile matrix set identifier |the ones included in Annex D of OGC 17-083r2 or defined by extensions of this core.
|TileMatrix |tile matrix identifier |identifier of the tile matrix (representing a zoom level, a.k.a. a scale) listed in the TileMatrixSet definition
|TileRow |row index of tile matrix	|a non-negative integer between 0 and the MatrixHeight – 1. If there is a TileMatrixSetLimits the value is limited between MinTileRow and MaxTileRow
|TileCol |column index of tile matrix	|a non-negative integer between 0 and the MatrixWidth – 1. If there is a TileMatrixSetLimits the value is limited between MinTileCol and MaxTileCol
!===

.API collection response fragment
=================
[source,JSON]
links:
[
    {
      "href": "http://data.example.com/collections/buildings/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}",
      "rel": "tiles",
      "type": "image/png",
    }
]
=================

==== Collection extra properties

A collection that can be retrieved as tiles will add an specific object in the collection information that will contain specific information necessary to get tiles representing the resource collection. In this core, the _tiles_ section only informs about in width tile matrix sets they can be retrieved.

include::requirements/tiles/core/REQ_stc-tmxslink.adoc[]

.Example of a tiles property in the collection response.
=================
[source,JSON]
  "tiles": {
    "tileMatrixSetLinks": [
      {
        "tileMatrixSet": "WebMercatorQuad",
        "tileMatrixSetURI": "http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad"
      }
    ]
  }
=================

=== Tiled data from one collection

The core provides a mechanism to select and retrieve a tile from a TileMatrixSet. If the service does not advertise any other TileMatrixSet (this core does not provide any mechanism to do that, but extensions can do it) only the TileMatrixSet identifiers specified in the Annex D.1 of the OGC 17-083r2 standard can be used.

==== Operation

include::requirements/tiles/core/REQ_tc-op.adoc[]

Typical resources that can be retrieved as tiles are: features (/collections/{collectionId}), coverages (/collections/{collectionId}/coverage/{coverageId} or /coverage/{coverageId}) or maps (/collections/{collectionId}/map/styleId}).

==== Parameter tileMatrixSetId
include::requirements/tiles/core/REQ_tc-tilematrixsetid-definition.adoc[]

==== Parameter tileMatrix
include::requirements/tiles/core/REQ_tc-tilematrix-definition.adoc[]

==== Parameter tileRow
include::requirements/tiles/core/REQ_tc-tilerow-definition.adoc[]

==== Parameter tileCol
include::requirements/tiles/core/REQ_tc-tilecol-definition.adoc[]

==== Response

A successful response of a tile request will be consistent with the media type of resource requested. This standard does not impose any media type. For example; for features can be geojson of Mapbox vector tiles; coverages it my be a geotiff and for maps it can be a jpeg or a png.

include::requirements/tiles/core/REQ_tc-success.adoc[]

Normally, the content partially outside the tile bounding box will be clipped and this is particularly true when tiles are in raster format. Nevertheless, tiles containing features in vector format may not clip the features partially outside.

include::recommendations/tiles/core/REC_tc-success-scale.adoc[]

==== Error situations

A general summary of the HTTP status codes can be found in OWS Common.

If the parameter value `tileMatrixSetId` is not available by the server for this resource or the parameters values `tileMatrix`, `tileRow`, `tileCol` are out-of-range, the status code of the response will be 404.
