== Requirement Class "Checkpoint core"

This extension is a building block a prior applicable to any data resource that add a mechanism to request for server changes in a resource collection since a previous checkpoint. It should be implemented as a GET but it will be a _partial_ GET.

In order to implement it the service needs to keep an audit of every change in the resources and assign a checkpoint to it. At some point in time the client will request a resource collection and receive it with a checkpoint identifier. After a while, the client will send a request for updates and notify the server about the checkpoint the client received. The server will inform the client about the changes in the resources up to a current checkpoint and the client will update its copy of the resources.

While dealing with atomic resources, implementors can consider to use e-tags to detect changes on cached version of them as defined in https://tools.ietf.org/html/rfc7232. The e-tag mechanism permits the client to  provide a fast "not modified" response in case the resource has not changed. In case the resource has been modified it is completely downloaded. In contrast, this requirement class adds the capability for partial update of a collection and the server will only retrieve the resource completely if all its parts has changed.

=== Overview

include::requirements/checkpoint/requirements_class_core.adoc[]

=== General
include::requirements/checkpoint/core/REQ_api-common.adoc[]

In practice, this means that the landing page and the conformance page follows OGC API Common core and collections requirements (STILL TBD but mostly equivalent to the more general parts of WFS3.0 requirements but with the text generalized to other resource types). This standard provides extra additions to the OWS common requirements that are particular to maps.

=== API landing page
The checkpoint has been designed as query parameters that can potentially be added to any relevant URL. The landing page provides links to start exploring the resources offered by the API but does not expose checkpoints. It mainly consists in a list of links. OWS Common already requires some common links that are enough for this core.

==== Response
No variations are required in the landing page.

=== Declaration of conformance classes
To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

==== Response
The conformance page mainly consists in a list of links. OWS Commmon already requires some links.

include::requirements/checkpoint/core/REQ_conformance-success.adoc[]

In the conformance page (commonly in JSON format) the links are following the link schema defined in the OGC API Common. The following is an example fragment of the response of a OGC API map tiles conformance information page with checkpoint support.

[[ConformancePage]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/styles",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/tms",
    "http://www.opengis.net/spec/ogcapi-checkpoint-1/1.0/req/core",
  ]
}
=================

=== Resource retrieval

==== Headers
A header in the response of resource retrieval will be added to a successful GET request with the checkpoint. This header will be added to a successful response of complete GET request of with a checkpoint parameter.

include::requirements/checkpoint/core/REQ_resource-success.adoc[]

This is necessary for the client to be able to formulate a checkpoint update request later.

=== Checkpoint extra parameters
A resource retrieval GET request can have additional query parameters to specify a filter to get only the changes in a resource collections from the last client request. The client has saved checkpoint associated with the resources it has saved or cached and it will communicate it to the server. The server will be able to know what elements the client has and deliver only the updated elements (and the deleted elements).

For a low connectivity environment, a parameter will  be able to select the priority level of the update changes and request only the most significant changes.

An additional parameter allows for selecting the amount of content and the format of the response.

==== Parameter Checkpoint
include::requirements/checkpoint/core/REQ_cp-checkpoint-definition.adoc[]

==== Parameter priority
include::requirements/checkpoint/core/REQ_cp-priority-definition.adoc[]

==== Parameter changeSetType
include::requirements/checkpoint/core/REQ_cp-changesettype-definition.adoc[]

=== ChangeSet response

==== ChangeSet response with changes
A success response of a resource request that has the checkpoint query filter will change to a format that contains a changeSet report and eventually the relevant changes.

include::requirements/checkpoint/core/REQ_cp-success.adoc[]

==== ChangeSet response with no changes
include::requirements/checkpoint/core/REQ_cp-not-modified.adoc[]
