== Requirement Class "Checkpoint tiles"

This extension describes what is specific for tiles in checkpoints. It extents http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/multitiles, http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/cols-multitiles" and "http://www.opengis.net/spec/ogcapi-checkpoint-1/1.0/req/core".

=== Overview

include::requirements/checkpoint/requirements_class_tiles.adoc[]

=== API landing page

No changes in the The landing page are required.

=== Declaration of conformance classes

==== Response

The conformance page mainly consists in a list of links. OWS Commmon already requires some links.

include::requirements/checkpoint/tiles/REQ_conformance-success.adoc[]

In the conformance page (commonly in JSON format) the links are following the link schema defined in the OGC API Common. The following is an example fragment of the response of a OGC API tiles conformance information page

[[ConformancePage]]
.Conformance Information Page fragment
=================
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/styles",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/tms",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/multitiles",
    "http://www.opengis.net/spec/ogcapi-checkpoint-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-checkpoint-1/1.0/req/tiles"
  ]
}
=================

=== Checkpoint operation
This extension is applied on top of the requirements class "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/multitiles" or "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/cols-multitiles". The parameters defined in "http://www.opengis.net/spec/ogcapi-checkpoint-1/1.0/req/core" are added to the parameters defined for multitiles or cols-multitiles (multitiles of tiles of multiple collections). For requesting updates to tiles there are some restrictions in the parameters defined in the core that are described in this extenaions.

==== Parameter changeSetType
include::recommendations/checkpoint/tiles/REC_cp-changesettype.adoc[]

Note that the checkpoint operation has a different output than the pure multitile operation. In practice this means that the parameter changeSetType overwrites the parameter multiTileType and in case both parameters are present, changeSetType takes precedence and multiTileType should be ignored.

=== ChangeSet response
The changeSet report is the one defined in the core but with the addition of a scale range.

include::requirements/checkpoint/tiles/REQ_cp-success.adoc[]
