== Requirement Class "Tiled data from more than one collection"

In previous clauses we have been discussion about tiles that are produced form one and only one resource. This is achieved by concatenating the tile path to a resource (e.g. a feature collection). This extension discusses about the possibility to combine more than one resource to create a tile. This is achieved by using by adding the tile path to the root of the service.

=== Declaration of conformance classes

==== Response

The conformance page mainly consists in a list of links. OWS Commmon already requires some links.

include::requirements/tiles/collections/REQ_conformance-success.adoc[]

In the conformance page (commonly in JSON format) the links are following the link schema defined in the OGC API Common. The following is an example fragment of the response of a OGC API tiles conformance information page

[[ConformancePage]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/core"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/collections"
  ]
}
=================

=== Tiles from more than one collection

==== Operation
include::requirements/tiles/collections/REQ_tcs-op.adoc[]

==== Parameter tileMatrixSetId
include::requirements/tiles/collections/REQ_tcs-tileMatrixSetId-definition.adoc[]

==== Parameter tileMatrix
include::requirements/tiles/collections/REQ_tcs-tileMatrix-definition.adoc[]

==== Parameter tileRow
include::requirements/tiles/collections/REQ_tcs-tileRow-definition.adoc[]

==== Parameter tileCol
include::requirements/tiles/collections/REQ_tcs-tileCol-definition.adoc[]

==== Parameter Collections
include::requirements/tiles/collections/REQ_tcs-collections-definition.adoc[]

==== Response
A successful response of a tile request will be consistent with the media type of resource requested. This standard does not impose any media type. For example; for features can be geojson of Mapbox vector tiles; coverages it my be a geotiff and for maps it can be a jpeg or a png.

include::requirements/tiles/collections/REQ_tcs-success.adoc[]

==== Error situations
If the parameter value `tileMatrixSetId` is not available by the server for this resource or the parameters values `tileMatrix`, `tileRow`, `tileCol` are out-of-range, the status code of the response will be 404.

If the parameter value of `collections` does not exist on the server, the status code of the response will be 404.

If the parameter value of `collections` has a wrong format or combines collections and some of them are not compatible with the `tileMatrixSetId` value, the status code of the response will be 500.
