== Requirement Class "Tiles Info"

NOTE: TBD by the WMS.SWG. Here there are some initial thoughts to be elaborated

=== Overview

[[core-overview]]

include::requirements/tiles/requirements_class_info.adoc[]

=== Declaration of conformance classes

==== Response

The conformance page mainly consists in a list of links. OWS Commmon already requires some links.

include::requirements/tiles/limits/REQ_conformance-success.adoc[]

In the conformance page (commonly in JSON format) the links are following the link schema defined in the OGC API Common. The following is an example fragment of the response of a OGC API tiles conformance information page

[[ConformancePage]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/core"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/info"
  ]
}
=================


=== Collection

=== Collection
This standard includes dependencies on OWS Common collection. The response of the operation is extended with the necessary information to formulate a tile response for this collection.

==== Collection Links

include::recommendations/tiles/core/REC_sfc-tile-examples.adoc[]

.API collection response fragment
=================
[source,JSON]
links:
[
    {
      "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad/0/0/0",
      "rel": "tiles",
      "type": "image/png",
    },
    {
      "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad/0/0/0/info",
      "rel": "info",
      "type": "text/html",
    }
]
=================

==== Collection extra properties

.Example of a tiles property in the collection response.
=================
[source,JSON]
  "tiles": {
    "formats": [
      [
        "image/jpeg",
        "image/png"
      ]
    ],
    "infoFormats": [
      [
        "application/geo+json",
        "text/html"
      ]
    ]
  }
=================
