=== Tiles

NOTE: THIS SECTION IS REDUNDANT WITH THE CURRENT WORK. SOME TEXT MIGHT BE STILL USEFUL. PLEASE IGNORE IT

The tile resource is generally a rectangular image containing cartographic data. Alternatively, this resource might be a non-image representation of the tile such as a description of the tile or a link to the actual image. For example, the tile resource could be a KML document used in a superoverlay, or a tile metadata document. When returning an image tile, a full single tile SHALL always be returned. Also, the background pixels of a tile SHOULD be transparent when possible so that the client can overlay the tiles on top of other map data (possibly other tiles).

==== Tile of a collectionId

The GetTile operation allows Map Tile clients to request a particular tile of a particular tile matrix set in a predefined format. This operation has some parameters in common with WMS GetMap but it has been deliberately simplified. For instance, only one layer can be retrieved at a time. Map Tile APIs that want to allow a combination of layers to be served and requested have to give this combination an identifier and add it as a new layer in the **service metadata document**. Nevertheless, clients are expected to be able easily to overlay layers themselves eliminating the need for servers to offer layers by combination.

===== Path Template

/collections/{collectionId}/tiles/{styleId}/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}

===== Path Parameters

collectionId <<collectionId>>
styleId <<styleId>>
tileMatrixSetId <<tileMatrixSetId>>
tileMatrix <<tileMatrix>>
tileRow <<tileRow>>
tileCol <<tileCol>>

===== Query Parameters

TBD. See https://app.swaggerhub.com/apis/joanma747/opf-map-tiles-api/1.0.0

===== Query Parameters

TBD. See https://app.swaggerhub.com/apis/joanma747/opf-map-tiles-api/1.0.0

===== Returns
The tile resource is generally a rectangular image containing cartographic data. Alternatively, this resource might be a non-image representation of the tile such as a description of the tile or a link to the actual image. For example, the tile resource could be a KML document used in a superoverlay, or a tile metadata document. When returning an image tile, a full single tile SHALL always be returned. It can also be a vector tile format. Also, the background of a tile SHOULD be transparent when possible so that the client can overlay the tiles on top of other map data (possibly other tiles).

===== Requirements

.Get Tile
include::requirements/core/REQ_tile-op.adoc[]

.Get Tile Response
include::requirements/core/REQ_map-success.adoc[]

.Get Tile Error
include::requirements/core/REQ_map-error.adoc[]


==== Tiles of more than one collectionId

===== Path Template

/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}

===== Path Parameters
tileMatrixSetId <<tileMatrixSetId>>
tileMatrix <<tileMatrix>>
tileRow <<tileRow>>
tileCol <<tileCol>>

===== Query Parameters

TBD. See https://app.swaggerhub.com/apis/joanma747/opf-map-tiles-api/1.0.0

===== Returns
The return is the same of the last operation but instead of containing only cartographic data of a single collectionId, it represents data from more than one collectionId.

===== Requirements

.Get Tile N
include::requirements/core/REQ_tile-n-op.adoc[]

.Get Tile N Response
include::requirements/core/REQ_tile-n-success.adoc[]

.Get Tile N Error
include::requirements/core/REQ_tile-n-error.adoc[]


==== Info about a point of a tile of a collectionId

Map Tile APIs may support requests for information about the features present at a particular point location on a map tile. Requests for feature information will specify the tile along with a pixel location on that tile. The server will provide information on the features present at or near the location specified by the client request. The server may choose what information to provide about the nearby features.

===== Path Template

/collections/{collectionId}/tiles/[stylesId}/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}/info

===== Path Parameters

collectionId <<collectionId>>
styleId <<styleId>>
tileMatrixSetId <<tileMatrixSetId>>
tileMatrix <<tileMatrix>>
tileRow <<tileRow>>
tileCol <<tileCol>>

===== Query Parameters

TBD. See https://app.swaggerhub.com/apis/joanma747/opf-map-tiles-api/1.0.0

===== Returns
Returns information about a point of a tile resource in a format that can be easily presented to the user. It can contain a list of features and attributes, a table etc in a human readable format (e.g. HTML) or computer readable format (e.g. JSON or XML)

For a better interoperability between servers and clients we strongly recommend GML Simple Features Profile [06-049r1] as a supported document format for FeatureInfo resources. That standard defines three levels of content in three profiles with different degrees of constraints to the GML flexibility. We strongly recommend support of the most constrained one (level 0) that results in a simpler GML document. In the context of that profile only simple XML types can be used as thematic properties and cardinality greater than one is not allowed. Servers and clients SHALL specify the MIME type "application/gml+xml; version=3.1" as an InfoFormat value and the GML application schema of the response SHOULD conform to GML Simple Features profile level 0 when that GML profile is used. In most cases, only thematic attributes of the features are intended to be included in a FeatureInfo document but the Simple Feature profiles were evidently intended to include the geometric information of the features in the GML objects. However, it is possible to generate an application schema that does not include feature geometry and only describes non-geometric feature attribute types. This can be very useful to avoid unnecessarily requesting long sequences of position values in line or polygon layers.

Also, to allow easy presentation of the data, support for the HTML format (represented by an InfoFormat MIME type of "text/html") is also recommended.

===== Requirements

.Get Feature Info
include::requirements/core/REQ-tile-info-op.adoc[]

.Get Feature Info Response
include::requirements/core/REQ_tile-info-success.adoc[]

.Get Feature Info Error
include::requirements/core/REQ_tile-info-error.adoc[]


==== Info about a point of a tile composed by more than one collectionId

===== Path Template

/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}/info

===== Path Parameters
tileMatrixSetId <<tileMatrixSetId>>
tileMatrix <<tileMatrix>>
tileRow <<tileRow>>
tileCol <<tileCol>>

===== Query Parameters

TBD. See https://app.swaggerhub.com/apis/joanma747/opf-map-tiles-api/1.0.0

===== Returns
The return is the same of the last operation but instead of containing information about only cartographic data of a single collectionId, it contains information about more than one collectionId.

===== Requirements

.Get Feature Info N
include::requirements/core/REQ_tile-info-n-op.adoc[]

.Get Feature Info N Response
include::requirements/core/REQ_tile-info-n-success.adoc[]

.Get Feature Info N Error
include::requirements/core/REQ_tile-info-n-error.adoc[]
