=== Maps

MapsTiles APIs are designed to serve map image. The API Description document described in the previous subclause lists the maps available on the server and the requirements for requesting a map subset. Typically clients will first request the API Description Document and then use the information in that document to discover how to perform valid requests for maps.

==== Maps of a collectionId

===== Path Template

/collections/{collectionId}/map/{styleId}

===== Path Parameters

collectionId <<collectionId>>
styleId <<styleId>>

===== Query Parameters

TBD. See https://app.swaggerhub.com/apis/joanma747/opf-map-tiles-api/1.0.0

===== Returns
A map resource is generally a rectangular image containing a representation of cartographic data included in the collectionId. Alternatively, this resource might be a non-image representation such as a description of the map or a link to the actual image. When returning an image map, a subset of the representation of cartographic data will be returned. It is highly recommended that the background of a map is transparent when possible so that the client can overlay maps on top of other map data. There is no restrictions in the format to return. In general any format that can be represented in a computer screen will be appropriate including raster JPEG, PNG but also vector formats such as SVG. In addition, any format that the client is able to convert in a visual representation using style rules is also acceptable, such as GeoJSON or raster binary arrays.

===== Requirements

.Get Map
include::requirements/core/REQ_map-op.adoc[]

.Get Map Response
include::requirements/core/REQ_map-success.adoc[]

.Get Map Error
include::requirements/core/REQ_map-error.adoc[]


==== Maps of more than one collectionId

===== Path Template

/map

===== Path Parameters
None

===== Query Parameters

TBD. See https://app.swaggerhub.com/apis/joanma747/opf-map-tiles-api/1.0.0

===== Returns
The return is the same of the last resource but instead of containing only cartographic data of a single collectionId, it represents data from more than one collectionId.

===== Requirements

.Get Map N
include::requirements/core/REQ_map-n-op.adoc[]

.Get Map N Response
include::requirements/core/REQ_map-n-success.adoc[]

.Get Map N Error
include::requirements/core/REQ_map-n-error.adoc[]


==== Info about a point of a map of a collectionId

===== Path Template

/collections/{collectionId}/map/{styleId}/info

===== Path Parameters

collectionId <<collectionId>>
styleId <<styleId>>

===== Query Parameters
TBD. See https://app.swaggerhub.com/apis/joanma747/opf-map-tiles-api/1.0.0

===== Returns
Returns information about a point of a subset of a map resource in a format that can be easily presented to the user. It can contain a list of features and attributes, a table etc in a human readable format (e.g. HTML) or computer readable format (e.g. JSON or XML)

For a better interoperability between servers and clients we strongly recommend GML Simple Features Profile [06-049r1] as a supported document format for FeatureInfo resources. That standard defines three levels of content in three profiles with different degrees of constraints to the GML flexibility. We strongly recommend support of the most constrained one (level 0) that results in a simpler GML document. In the context of that profile only simple XML types can be used as thematic properties and cardinality greater than one is not allowed. Servers and clients SHALL specify the MIME type "application/gml+xml; version=3.1" as an InfoFormat value and the GML application schema of the response SHOULD conform to GML Simple Features profile level 0 when that GML profile is used. In most cases, only thematic attributes of the features are intended to be included in a FeatureInfo document but the Simple Feature profiles were evidently intended to include the geometric information of the features in the GML objects. However, it is possible to generate an application schema that does not include feature geometry and only describes non-geometric feature attribute types. This can be very useful to avoid unnecessarily requesting long sequences of position values in line or polygon layers.

Also, to allow easy presentation of the data, support for the HTML format (represented by an InfoFormat MIME type of "text/html") is also recommended.

===== Requirements

.Get Feature Info
include::requirements/core/REQ_map-info-op.adoc[]

.Get Feature Info Response
include::requirements/core/REQ_map-info-success.adoc[]

.Get Feature Info Error
include::requirements/core/REQ_map-info-error.adoc[]


==== Info about a point of a map composed by more than one collectionId

===== Path Template

/map/info

===== Path Parameters
None

===== Query Parameters
TBD. See https://app.swaggerhub.com/apis/joanma747/opf-map-tiles-api/1.0.0

===== Returns
The return is the same of the last operation but instead of containing information aobut only cartographic data of a single collectionId, it contains information about more than one collectionId.

===== Requirements

.Get Feature Info N
include::requirements/core/REQ_map-info-n-op.adoc[]

.Get Feature Info N Response
include::requirements/core/REQ_map-info-n-success.adoc[]

.Get Feature Info N Error
include::requirements/core/REQ_map-info-n-error.adoc[]
