== Requirement Class "Tiles Info"

NOTE: TBD by the WMS.SWG. Here there are some initial thoughts to be elaborated

=== Overview

[[core-overview]]

include::requirements/tiles/requirements_class_info.adoc[]

=== Declaration of conformance classes

==== Response

The conformance page mainly consists in a list of links. OWS Commmon already requires some links.

include::requirements/tiles/limits/REQ_conformance-success.adoc[]

In the conformance page (commonly in JSON format) the links are following the link schema defined in the OGC API Common. The following is an example fragment of the response of a OGC API tiles conformance information page

[[ConformancePage]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/core"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/info"
  ]
}
=================


=== Collection

=== Collection
This standard includes dependencies on OWS Common collection. The response of the operation is extended with the necessary information to formulate a tile response for this collection.

==== Collection Links

include::recommendations/tiles/core/REC_sfc-tile-examples.adoc[]

.API collection response fragment
=================
[source,JSON]
links:
[
    {
      "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad/0/0/0",
      "rel": "tiles",
      "type": "image/png",
    },
    {
      "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad/0/0/0/info",
      "rel": "info",
      "type": "text/html",
    }
]
=================

==== Collection extra properties

.Example of a tiles property in the collection response.
=================
[source,JSON]
  "tiles": {
    "formats": [
      [
        "image/jpeg",
        "image/png"
      ]
    ],
    "infoFormats": [
      [
        "application/geo+json",
        "text/html"
      ]
    ]
  }
=================
=== FeatureInfo

Map Tile APIs may support requests for information about the features present at a particular pixel location on a map tile. Requests for feature information will specify the tile along with a pixel location on that tile. The server will provide information on the features present at or near the location specified by the client request. The server may choose what information to provide about the nearby features.

==== FeatureInfo document

A FeatureInfo document is the resource representation of a FeatureInfo resource in resource oriented architectural style. The FeatureInfo document SHALL be in the format specified in the request when that format has been advertised in the *ServiceMetadata document* as available for that FeatureInfo resource.

For a better interoperability between servers and clients we strongly recommend GML Simple Features Profile [06-049r1] as a supported document format for FeatureInfo resources. That standard defines three levels of content in three profiles with different degrees of constraints to the GML flexibility. We strongly recommend support of the most constrained one (level 0) that results in a simpler GML document. In the context of that profile only simple XML types can be used as thematic properties and cardinality greater than one is not allowed. Servers and clients SHALL specify the MIME type "application/gml+xml; version=3.1" as an InfoFormat value and the GML application schema of the response SHOULD conform to GML Simple Features profile level 0 when that GML profile is used. In most cases, only thematic attributes of the features are intended to be included in a FeatureInfo document but the Simple Feature profiles were evidently intended to include the geometric information of the features in the GML objects. However, it is possible to generate an application schema that does not include feature geometry and only describes non-geometric feature attribute types. This can be very useful to avoid unnecessarily requesting long sequences of position values in line or polygon layers.

Also, to allow easy presentation of the data, support for the HTML format (represented by an InfoFormat MIME type of "text/html") is also recommended.

==== GetResourceRepresentation

The ServiceMetadata document in the resource oriented architectural style may contain a list of Layer elements and each layer that is available to be retrieved in this architectural style and is queryable SHALL have one or more <ResourceURL> elements with the "resourceType" attribute set to "FeatureInfo" and a template attribute. In this RESTful approach the template attribute contains a URL template that can be converted to a URL by using a template processor and then get the expected FeatureInfo in the format specified by the attribute "format" by requesting the resource with a standard HTTP GET.

include::requirements/core/REQ_grr.adoc[]

===== Operation

The GetResourceRepresentation request operation is defined by the following requirement:

include::requirements/core/REQ_grr-op.adoc[]

An example GetResourceRepresentation request
is

    http://www.maps.bob/etopo2/default/WholeWorld_CRS_84/10m/1/3/86/132.xml

It corresponds to the following ResourceURL element: <ResourceURL format="application/gml+xml; version=3.1" resourceType="FeatureInfo" template="http://www.maps.bob/etopo2/default/ {TileMatrixSet}/{TileMatrix}/{TileRow}/{TileCol}/{J}/{I}.xml"

===== Response

A successful GetResourceRepresentation response is defined by the following requirement:

include::requirements/core/REQ_grr-success.adoc[]

An XML document conforming GML Simple Features Profile [06-049r1] is the most typical representation but other representations and formats are also allowed.

===== Error situations

An unsuccessful GetResourceRepresentation reponse follows the general guidance for HTTP status codes provided in <<http_status_codes>> and the following requirement:

include::requirements/core/REQ_grr-error.adoc[]
