== Requirement Class "Tiles Tile Matrix Set"

The _tiles core_ clause states that if there is no information on TileMatrixSet, the service can behave as a service that supports the eight TileMatrixSets defined in the Annex D.1 of the OGC 17-083r2 standard. This extension adds all necessary elements to support other TileMatrixSets.

=== Overview
The entry point is a `Landing page` (path `/`).

The `Landing page` provides links to
* the `API definition` (path `/api`, link relation `service`),
* the `Conformance declaration` (path `/conformance`, link relation `conformance`), and
* the `Collections` (path `/collections`, link relation `data`).
* the `TileMatrixSets` (path `/tileMatrixSets`, link relation `tileMatrixSet`).


[[core-overview]]

include::requirements/tiles/requirements_class_tms.adoc[]

=== API landing page

The landing page provides links to start exploring the resources offered by the API. It mainly consists in a list of links. The core of this standard does not add anything to the links required by OWS Common. This extension for TileMatrixSet requires new ones for TileMatrixSets on top of the common ones.

==== Response

include::requirements/tiles/tms/REQ_api-definition-success.adoc[]

In the landing page, in JSON format, the links are following the link schema defined in the OGC API Common. The following is an example fragment of the response of a OGC API tiles landing page

[[landingPage]]
.API Landing Page fragment
=================
[source,JSON]
----
[
  [...],
  {
    "href": "http://data.example.org/tileMatrixSet?f=json",
    "rel": "tileMatrixSets",
    "type": "application/json",
    "title": "List of tileMatrixSets implemented by this API in JSON",
  },
  {
    "href": "http://data.example.org/tileMatrixSet?f=html",
    "rel": "tileMatrixSets",
    "type": "text/html",
    "title": "List of tileMatrixSets implemented by this API in HTML",
  }
]
----
=================

With a `/collections` successful response it is possible to retrieve the list of collectionId and links to the /collections/{collectionId}.
With a /collections/{collectionId} successful response is s possible to discover the links to retrieve some tiles. The other tiles can be retrieved by following the /collections/{collectionId}/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol} template. Other tile paths are defined for other resource types that are not collections.

=== Declaration of conformance classes

==== Response

The conformance page mainly consists in a list of links. OWS Commmon already requires some links.

include::requirements/tiles/tms/REQ_conformance-success.adoc[]

In the conformance page (commonly in JSON format) the links are following the link schema defined in the OGC API Common. The following is an example fragment of the response of a OGC API tiles conformance information page

[[ConformancePage]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/core"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/tms"
  ]
}
=================

=== TileMatrixSets

=== TileMatrixSet

=== Collection

==== Collection extra properties

include::requirements/tiles/tms/REQ_sfc-formats.adoc[]

=================
[source,JSON]
----
  "tiles": {
    "formats": [
      [
        "image/jpeg",
        "image/png"
      ]
    ],
    "tileMatrixSetLink": [
      {
        "type": "tileMatrixSetLink",
        "tileMatrixSet": "http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad",
        "tileMatrixSetLimits": [
          {
            "type": "tileMatrixSetLimits",
            "tileMatrix": "5",
            "minTileRow": 0,
            "maxTileRow": 1,
            "minTileCol": 3,
            "maxTileCol": 4
          }
        ]
      }
    ]
  }
----
=================
