[[req_scaling_width-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/scaling/width-definition*
^|A |The map operation SHALL support a parameter `width` with the characteristics defined in the OpenAPI Specification 3.0 fragment
[source,YAML]
----
  width:
    name: width
    in: query
    description:
      Width of the viewport in pixel units to present the response (the map subset).
    required: false
    style: form
    schema:
      type: number
----
^|B |The implementation SHALL interpret the `width` value as the horizontal size (columns) of the viewport where the response will be presented in pixel units (number of pixels).
^|C |The implementation SHALL return an error if the `width` number is not a positive integer number.
^|D |The implementation SHALL return an error if the value of the `width` exceeds a `maxWidth` property from a `x-OGC-limits.maps` object included in the service metadata.
^|E |The implementation SHALL return an error if the value of the `width` times `height` (specified or calculated) exceeds a `maxPixels` property from a `x-OGC-limits.maps` object included in the service metadata.
|===
