[[req_scaling_scale-denominator-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/scaling/scale-denominator-definition*
^|A |The map operation SHALL support a parameter `scale-denominator` with the characteristics defined in the OpenAPI Specification 3.0 fragment
[source,YAML]
----
  scale-denominator:
    name: scale-denominator
    in: query
    description:
      Number of units in the real-world corresponding to one such unit on the display.
    required: false
    style: form
    schema:
      type: number
----
^|B |The `scale-denominator` value SHALL be interpreted as the number of real-world units corresponding to one of the same unit on the map (as printed or displayed), based on the selected (e.g., from display resolution requirements class) or default (0.28 mm/pixel) display resolution.
^|C |The width and height dimensions of the returned map SHALL be computed based on the `scale-denominator` value, the display resolution, and the selected spatial subset of the map to return.
^|D |An HTTP 400 error SHALL be returned if the `scale-denominator` parameter is used together with `width` and/or `height` and the implementation does not declare conformance to the <<rc_table_spatial-subsetting, _spatial subsetting_>> requirements class (which specifies that the `width` and `height` parameters can also take on a subsetting role).
|===
