[[req_scaling_width-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/scaling/width-definition*
^|A |The map operation SHALL support a parameter `width` with the characteristics defined in the OpenAPI Specification 3.0 fragment
[source,YAML]
----
  width:
    name: width
    in: query
    description:
      Width of the viewport in pixel units to present the response (the map subset).
    required: false
    style: form
    schema:
      type: number
----
^|B |The `width` value SHALL be computed as the horizontal size (columns) of the viewport where the response will be presented in pixel units (number of pixels).
^|C |An error SHALL be returned if the `width` number is not a positive integer number.
^|D |An error SHALL be returned if the value of the `width` exceeds the `maxWidth` property specified in the `x-OGC-limits.maps` object included in the service metadata^1^.
2+|
^1^ service metadata may be provided as an extension of the `info` section of the Open API document as indicated in https://docs.ogc.org/is/19-072/19-072.html[OGC API – Common – Part 1: Core], Annex B.4 and discussed in the <<ScalingServiceMetadata, last subsection of the Maps API scaling requirements class section>>.
|===
