[[req_scaling_height-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/scaling/height-definition*
^|A |The map operation SHALL support a parameter `height` with the characteristics defined in the OpenAPI Specification 3.0 fragment
[source,YAML]
----
  height:
    name: height
    in: query
    description:
      Height of the viewport in pixel units to present the response (the map subset).
    required: false
    style: form
    schema:
      type: number
----
^|B |The `height` value SHALL be computed as the vertical size (rows) of the viewport where the response will be presented in pixel units (number of pixels).
^|C |An error SHALL be returned if the `height` value is not a positive integer number.
^|D |An error SHALL be returned if the value of the `height` exceeds the `maxHeight` property specified in the `x-OGC-limits.maps` object included in the service metadata^1^.
^|E |An error SHALL be returned if the value of the `width`  (specified or calculated) times `height` (specified or calculated) exceeds a `maxPixels` property from a `x-OGC-limits.maps` object included in the service metadata^1^.
2+|
^1^ service metadata may be provided as an extension of the `info` section of the Open API document as indicated in https://docs.ogc.org/is/19-072/19-072.html[OGC API – Common – Part 1: Core], Annex B.4 and discussed in the <<ScalingServiceMetadata, last subsection of the Maps API scaling requirements class section>>
|===
