[[req_scaling_height-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/scaling/height-definition*
^|A |The map operation SHALL support a parameter `height` with the characteristics defined in the OpenAPI Specification 3.0 fragment
[source,YAML]
----
  height:
    name: height
    in: query
    description:
      Height of the viewport to present the response in pixel units (the map subset).
    required: false
    style: form
    schema:
      type: number
----
^|B |The implementation SHALL interpret the `height` value as the vertical size (rows) of the viewport where the response will be presented in pixel units (number of pixels).
^|C |The implementation SHALL return an error if the `height` value is not a positive integer number.
^|D |The implementation SHALL return an error if the value of the `height` exceeds a `maxHeight` property from a `x-OGC-limits.maps` object included in the service metadata.
^|E |The implementation SHALL return an error if the value of the `width` (specified or calculated) times `height` exceeds a `maxPixels` property from a `x-OGC-limits.maps` object included in the service metadata.
|===
