[[overview]]
== Overview

=== Evolution from OGC Web Services

OGC Web Service (OWS) standards implemented a Remote-Procedure-Call-over-HTTP architectural style using XML for payloads. This was the state-of-the-art when OGC Web Services were originally designed in the late 1990s and early 2000s. This architectural style has fallen out of favor. It has been replaces by a RESTful API style which is resource oriented instead of service oriented. This Map Tiles API standard specifies an API that follows this Web architecture and in particular the <<SDWBP,W3C/OGC best practices for sharing Spatial Data on the Web>> as well as the <<DWBP,W3C best practices for sharing Data on the Web>>.

The OGC API (OAPI) Common specifies the common kernel of an API approach to services that follows current resource-oriented architecture practices. OAPI Common is the foundation upon which OGC APIs will be built. This common API is to be extended by resource-specific API standards. This specification extends OAPI Common to support Map Tile resources.

Beside the general alignment with the architecture of the Web (e.g., consistency with HTTP/HTTPS, hypermedia controls), another goal for OGC API standards is modularization. This goal has several facets:

* Clear separation between core requirements and more advanced capabilities. This document specifies the requirements that are relevant for almost everyone who wants to share or use Map Tiles on a fine-grained level. Additional capabilities that several communities are using today will be specified as extensions to the Core API.
* Technologies that change more frequently are decoupled and specified in separate modules ("requirements classes" in OGC terminology). This enables, for example, the use/re-use of new encodings for spatial data or API descriptions.
* Modularization is not just about a single "service". OGC APIs will provide building blocks that can be reused in APIs in general. In other words, a server supporting the Map Tiles API should not be seen as a standalone service.  Rather it should be viewed as a collection of API building blocks which together implement Map Tile capabilities. A corollary of this is that it should be possible to implement an API that simultaneously conforms to conformance classes from the Feature, Coverage, Map Tiles, and other OGC Web API standards.

This approach intends to support two types of client developers:

* Those that have never heard about OGC. Developers should be able to create a client using the API definition without the need to read an OGC standard (they may need to learn a little bit about geometry, etc.);
* Those that want to write a "generic" client that can access OGC APIs, i.e. are not specific for a particular API.

As a result of this modernization, OGC API implementations are not backwards compatible with OWS implementations per se. However, a design goal is to define OGC APIs in a way so that an OAPI interface can be mapped to a OWS implementation. OGC APIs are intended to be simpler and more modern, but still an evolution from the previous versions and their implementations.

=== Encodings

[NOTE]
========
Discuss if different encodings of map tiles are anticipated.
========



=== Examples

[NOTE]
========
Update the following content once a Map Tile example has been agreed on.
========

This document uses a simple example throughout the document: The dataset contains buildings and the API provides access to them through a single feature collection ("buildings") and two encodings, GeoJSON and HTML.

The buildings have a few (optional) properties: the polygon geometry of the building footprint, a name, the function of the building (residential, commercial or public use), the floor count and the timestamp of the last update of the building feature in the dataset.

This example serves to illustrate the concepts underlying OGC APIs. It does not indicate that OGC APIs are always feature based. Other resource types can and will be implemented as well. But the basic capapablities described in this specification will apply to all.
