[appendix]
:appendix-caption: Annex
[[annex-ats]]
== Conformance Class Abstract Test Suite (Normative)

=== Conformance Class "Core"


[[conf_core,/conf/core]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core
classification:: Target Type:Web API
abstract-test:: /conf/core/map-op
abstract-test:: /conf/core/map-response
abstract-test:: /conf/core/conformance-success
====

==== Abstract Test for Requirement Map Operation


[[conf_core_map-op,/conf/core/map-op]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/map-op
target:: /req/core/map-op
test-purpose:: Verify that the implementation supports the map retrieval operation
test-method::
+
--
*Given:* a geospatial data resource conforming to the Maps API Standard, with an API path including `.../map...` or discovered following a link with relation type `[ogc-rel:map]` +
*When:* performing a GET operation on the `/map` resource with a supported media type specified in the `Accept:` header (e.g., `Accept: image/png,image/jpeg`) +
*Then:* +
- assert that the implementation supports retrieving map resources at one or more `.../map` URL.
--
====


==== Abstract Test for Requirement Map Response


[abstract_test]
====
[%metadata]
identifier:: /conf/core/map-response
target:: /req/core/map-response
test-purpose:: Verify that the implementation's response for the map retrieval operation is correct
test-method::
+
--
*Given:* a map resource that was successfully retrieved for <<conf_core_map-op>> +
*When:* retrieving that resource for the map operation +
*Then:* +
- assert that the response has an HTTP status code 200, +
- assert that the map response is in the storage CRS specified in the description of the geospatial resource (such as the associated collection or dataset), or https://www.opengis.net/def/crs/OGC/1.3/CRS84 if none is specified, +
- assert that the headers of the response include the `Content-Crs:` header with the URI or the safe CURIEs of the CRS used to render the map, except if the content is in the https://www.opengis.net/def/crs/OGC/1.3/CRS84 CRS, +
- assert that the headers of the response include a `Content-Bbox:` header with the actual geospatial boundary of the rendered map, +
- assert that the `Content-Bbox:` coordinates are in the response CRS (indicated in the `Content-Crs:` or https://www.opengis.net/def/crs/OGC/1.3/CRS84 if it is not present) and contains four comma-separated numbers representing the lower-left and upper-right corners of the response honoring the CRS coordinates order, +
- assert that if the geospatial resource has a temporal aspect (e.g., if a temporal extent is defined in the collection description or in the dataset landing page), the headers of the response include a `Content-Datetime:` header with the actual datetime instant or datetime interval of the rendered map. +
- assert that a `Content-Datetime:` response header representing a temporal interval, if present, uses the notation `time-instant / time-instant`, +
- assert that if `Content-Datetime:` response header is present, time instants, whether a single value or the `time-instant` of an interval, are expressed as defined in RFC 3339, section 5.6 format,
using either UTC time or local time offsets, but also allowing for the additional formats `yyyy`, `yyyy-mm`, `yyyy-mm-dd`, `yyyy-mm-ddThhZ` (or e.g., `yyyy-mm-ddThh-04:00`) and `yyyy-mm-ddThh:mmZ` (or e.g., `yyyy-mm-ddThh-04:00`), +
- assert that the body of the response contains a map encoded in the negotiated format.
--
====

==== Abstract Test for Requirement Map Conformance Success


[abstract_test]
====
[%metadata]
identifier:: /conf/core/conformance-success
target:: /req/core/conformance-success
test-purpose:: For implementations having a mechanism to advertise conformance classes, verify that it reports conformance to this Standard correctly.
test-method::
+
--
*Given:* a conformance resource in a recognized format, such as the OGC API JSON `/conformance` resource +
*When:* retrieving that resource from the API endpoint +
*Then:* +
- assert that the list of conformance classes that are supported by this API implementation instance includes at minimum https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core.
This list of conformance classes can also be used to select which other abstract tests to perform as listed in the <<table_conformance_urls>> and indicated in the tests preconditions.
--
====

=== Conformance Class "Map Tilesets"

[[conf_tilesets,/conf/tilesets]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/tilesets
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/tilesets
classification:: Target Type:Web API
abstract-test:: /conf/tilesets/desc-links
abstract-test:: /conf/tilesets/tiles-parameters
====

==== Abstract Test for Requirement desc-links


[abstract_test]
====
[%metadata]
identifier:: /conf/tilesets/desc-links
target:: /req/tilesets/desc-links
test-purpose:: Verify that the implementation supports map tilesets
test-method::
+
--
*Given:* a geospatial data resource conforming to this Standard, to "Map Tilesets", to OGC _API - Tiles_ and providing a description resource including links +
*When:* retrieving the geospatial data resource description +
*Then:* +
- assert that the geospatial data resource (e.g., collection or landing page description's `links` property) includes a link with the `href` pointing to a tileset list supported that presents a tile aspect of this geospatial data resource and with rel: `[ogc-rel:tilesets-map]`
--
====

==== Abstract Test for Requirement tiles-parameters


[abstract_test]
====
[%metadata]
identifier:: /conf/tilesets/tiles-parameters
target:: /req/tilesets/tiles-parameters
test-purpose:: Verify that the implementation supports relevant parameters for map tilesets
test-method::
+
--
*Given:* a geospatial data resource conforming to this Standard, to "Map Tilesets", to OGC _API - Tiles_, and to _Maps_ requirements classes introducing parameters relevant for map tiles  +
*When:* retrieving the map tiles with parameters for the _background_, _display resolution_, _spatial subsetting_ (only for `subset` and `subset-crs` parameters, and only if a vertical dimension is available), _general subsetting_, and _scaling_ requirements classes +
*Then:* +
- assert that tiles responses reflect the relevant map parameters used for the requests
--
====

NOTE: This conformance class depends on _OGC API - Tiles - Part 1: Core_ "Tilesets List" conformance class to which the implementation must also conform.

=== Conformance Class "Background"

[[conf_background,/conf/background]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/background
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/background
classification:: Target Type:Web API
abstract-test:: /conf/background/bgcolor-definition
abstract-test:: /conf/background/transparent-definition
abstract-test:: /conf/background/void-color-definition
abstract-test:: /conf/background/void-transparent-definition
abstract-test:: /conf/background/map-success
====

==== Abstract Test for Requirement `bgcolor` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/background/bgcolor-definition
target:: /req/background/bgcolor-definition
test-purpose:: Verify that the implementation supports the `bgcolor` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a map without `bgcolor` parameter, with `bgcolor` using a hexadecimal value and with `bgcolor` using a W3C Web Color name +
*Then:* +
- assert that the map operation supports a `bgcolor` parameter in hexadecimal red-green-blue color value (from 00 to FF, FF representing 255) for the background color of the map. For a six-digit hexadecimal value, the first and second digits specify the intensity of red. The third and fourth digits specify the intensity of green. The fifth and sixth digits specify the intensity of blue, +
- assert that the map operation supports a `bgcolor` parameter in case-insensitive https://www.w3.org/wiki/CSS/Properties/color/keywords[W3C web color name] for the background color of the map, +
- assert that if `bgcolor` is not specified, and either `transparent` is set to `false` or the output format cannot encode transparency, and there is an style defined the server uses the background color specified by the requested style, +
- assert that if `bgcolor` is not specified, and either `transparent` is set to `false` or the output format cannot encode transparency, and there is no style used or the style do not specify a background color, the background color is set to 0xFFFFFF.
--
====

==== Abstract Test for Requirement `transparent` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/background/transparent-definition
target:: /req/background/transparent-definition
test-purpose:: Verify that the implementation supports the `transparent` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a map for all combinations of (no `transparent` parameter, transparent=false`, `transparent=true`) and with and without `bgcolor` parameter +
*Then:* +
- assert that the server interprets `transparent` as a Boolean indicating whether the background of the map should be transparent, +
- assert that, if `transparent` is not specified and a `bgcolor` is not specified, the server assumes a value of `true`, +
- assert that, if `transparent` is not specified and a `bgcolor` is specified, the server assumes a value of `false`, +
- assert that, if `transparent` is `true` and a `bgcolor` is specified, the server uses 0 for the background's opacity.
--
====

==== Abstract Test for Requirement `void-color` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/background/void-color-definition
target:: /req/background/void-color-definition
test-purpose:: Verify that the implementation supports the `void-color` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a map without `void-color` parameter, with `void-color` using a hexadecimal value and with `void-color` using a W3C Web Color name +
*Then:* +
- assert that the map operation supports a `void-color` parameter which can be an hexadecimal red-green-blue color value (from 00 to FF, FF representing 255) for the parts of the map outside of the valid areas of the projection / CRS. For a six-digit hexadecimal value, the first and second digits specify the intensity of red. The third and fourth digits specify the intensity of green. The fifth and sixth digits specify the intensity of blue, +
- assert that the map operation supports a case-insensitive https://www.w3.org/wiki/CSS/Properties/color/keywords[W3C web color name] the parts of the map outside of the valid areas of the projection / CRS, +
- assert that if `void-color` is not specified, the same color value as for `bgcolor` (specified or default) is used for the parts of the map outside of the valid areas of the projection / CRS.
--
====

==== Abstract Test for Requirement `void-transparent` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/background/void-transparent-definition
target:: /req/background/void-transparent-definition
test-purpose:: Verify that the implementation supports the `void-transparent` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a map for all combinations of (no `void-transparent` parameter, void-transparent=false`, `void-transparent=true`) and with and without `void-color` parameter +
*Then:* +
- assert that the server interprets `void-transparent` as a Boolean indicating whether the parts of the map outside of the valid areas of the projection / CRS should be transparent, +
- assert that, if `void-transparent` is not specified, the server assumes the same value as for `transparent` (specified or default).
--
====

==== Abstract Test for Requirement Background Map Success


[abstract_test]
====
[%metadata]
identifier:: /conf/background/map-success
target:: /req/background/map-success
test-purpose:: Verify that the implementation's response for the map retrieval operation with a background color and/or transparent parameter is correct
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* for all combinations of (no `transparent` parameter, transparent=false`, `transparent=true`) and (without `bgcolor` parameter, with `bgcolor` using a hexadecimal value and with `bgcolor` using a W3C Web Color name) +
*Then:* +
- assert that the color of the map in the areas with no data is exactly the one specified in the `bgcolor`, +
- assert that the color in parts of the map outside of the valid areas of the projection / CRS is the one specified by `void-color`, or otherwise default to the same as the background color (whether specified by `bgcolor` or default), +
- assert that the transparency setting in parts of the map outside of the valid areas of the projection / CRS is the one specified by `void-transparent`, or otherwise default to the same as the background transparency setting (whether specified by `transparent` or default), +
- assert that, in case the output format allows it and in the absence of the `transparent` parameter (or if it is `false`), the opacity (alpha value) of the map in the areas with no data is exactly 100%, if `transparent` is `false` or 0% if `transparent` is `true` (if the renderer supports anti-aliasing, at the edges between data and no-data areas, the opacity is allowed to have a value between 0% and 100%).
--
====

=== Conformance Class "Collection Selection"

[[conf_collections-selection,/conf/collections-selection]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collections-selection
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/collections-selection
classification:: Target Type:Web API
abstract-test:: /conf/collections-selection/collections-parameter
abstract-test:: /conf/collections-selection/collections-response
====

==== Abstract Test for Requirement `collections` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/collections-selection/collections-parameter
target:: /req/collections-selection/collections-parameter
test-purpose:: Verify that the implementation supports the `collections` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core and that is understood to consist of multiple collections (e.g., a dataset advertising support for Dataset Map and featuring multiple collections) +
*When:* retrieving a map using the `collections` parameter with one and multiple _collectionsIds_ +
*Then:* +
- assert that an operation that acts on a resource consisting of multiple geospatial data sub-resources (e.g., a resource derived from a root dataset) supports an optional parameter `collections` as an array of comma-separated collection id strings, +
- assert that the parameter `collections` is supported by maps originating from resources consisting of multiple geospatial data sub-resources that can be addressed by identifiers (e.g. dataset map at `{datasetAPI}/maps/`), +
- assert that implementations support both comma-separated list of geospatial resource identifiers (e.g., collectionId's) and full URLs to local geospatial resources.
--
====

==== Abstract Test for Requirement Collection Selection Response


[abstract_test]
====
[%metadata]
identifier:: /conf/collections-selection/collections-response
target:: /req/collections-selection/collections-response
test-purpose:: Verify that the implementation responds correctly to map requests using the `collections` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core and that is understood to consist of multiple collections (e.g., a dataset advertising support for Dataset Map and featuring multiple collections) +
*When:* retrieving a map using the `collections` parameter with one and multiple _collectionsIds_ +
*Then:* +
- assert that only collections of geospatial data enumerated in the values of the `collections` parameter are used to generate the responses for the resource (map) to which they apply, +
- assert that if there is more than one collection name and the style applied does not specify otherwise, the collections are rendered in the result in an order starting with the first (leftmost) collection and ending with the last (rightmost).
--
====

=== Conformance Class "Scaling"

[[conf_scaling,/conf/scaling]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/scaling
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/scaling
classification:: Target Type:Web API
abstract-test:: /conf/scaling/width-definition
abstract-test:: /conf/scaling/height-definition
abstract-test:: /conf/scaling/scale-denominator-definition
====

==== Abstract Test for Requirement `width` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/scaling/width-definition
target:: /req/scaling/width-definition
test-purpose:: Verify that the implementation supports the (scaling) `width` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using `width` parameter for different values, as well as the same `bbox` parameter if spatial subsetting is supported, with and without `height` parameter, with and without `mm-per-pixel` parameter if display resolution is supported +
*Then:* +
- assert that the `width` value is interpreted as the horizontal size (columns) of the viewport where the response will be presented in pixel units (number of pixels), +
- assert that an HTTP 4xx error is returned if the `width` number is not a positive integer number, +
- assert that an error is returned if the value of the `width` exceeds the `maxWidth` property specified in the `x-OGC-limits.maps` object included in the service metadata, +
- assert that an HTTP 4xx error is returned if the value of the `width` (specified or calculated) times `height` (specified or calculated) exceeds a `maxPixels` property from a `x-OGC-limits.maps` object included in the service metadata, +
- assert that an HTTP 4xx error be returned if the `width` parameter is used together with the `bbox` (or `subset` for spatial dimensions) as well as the `scale-denominator` parameter, +
- assert that an HTTP 4xx error is returned if the `width` parameter is used together with the `scale-denominator` parameter and the implementation does not also support the "Subsetting" requirements class, +
- assert that, when the `width` parameter is omitted, the implementation uses an appropriate width which accurately reflects the default or requested scale established as the ratio between the horizontal dimension of the viewport and the corresponding size of the physical world, specifically for the local subset (bounding box) of the map being returned, and taking into consideration the default (0.28 mm/pixel) or specified display resolution (`mm-per-pixel`).
--
====

==== Abstract Test for Requirement `height` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/scaling/height-definition
target:: /req/scaling/height-definition
test-purpose:: Verify that the implementation supports responds the (scaling) `height` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using `height` parameter for different values, as well as the same `bbox` parameter if spatial subsetting is supported, with and without `width` parameter, with and without `mm-per-pixel` parameter if display resolution is supported +
*Then:* +
- assert that the `height` value is interpreted as the vertical size (rows) of the viewport where the response will be presented in pixel units (number of pixels), +
- assert that an HTTP 4xx error is returned if the `height` value is not a positive integer number, +
- assert that an HTTP 4xx error is returned if the value of the `height` exceeds the `maxHeight` property specified in the `x-OGC-limits.maps` object included in the service metadata, +
- assert that an HTTP 4xx error is returned if the value of the `width`  (specified or calculated) times `height` (specified or calculated) exceeds a `maxPixels` property from a `x-OGC-limits.maps` object included in the service metadata, +
- assert that an HTTP 4xx error is returned if the `height` parameter is used together with the `bbox` (or `subset` for spatial dimensions) as well as the `scale-denominator` parameter, +
- assert that an HTTP 4xx error is returned if the `height` parameter is used together with the `scale-denominator` parameter and the implementation does not also support the "Subsetting" requirements class, +
- assert that, when the `height` parameter is omitted, the implementation uses an appropriate height which accurately reflects the default or requested scale established as the ratio between the vertical dimension of the viewport and the corresponding size of the physical world, specifically for the local subset (bounding box) of the map being returned.
--
====

==== Abstract Test for Requirement `scale-denominator` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/scaling/scale-denominator-definition
target:: /req/scaling/scale-denominator-definition
test-purpose:: Verify that the implementation supports the `scale-denominator` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `scale-denominator` parameter, combining all possibilities of with and without `width` and/or `height` parameters, with and without `bbox` and `center` parameter if spatial subsetting is supported, with and without `mm-per-pixel` parameter if display resolution is supported +
*Then:* +
- assert that the `scale-denominator` value is interpreted as the number of real-world units corresponding to one of the same unit on the map (as printed or displayed), considering only the local subset of the map being returned, based on the selected (e.g., from display resolution requirements class) or default (0.28 mm/pixel) display resolution, +
- assert that the implementation establishes the correspondence between real-world units and pixel units based on the equation: _physicalMetersPerPixel_= (`mm-per-pixel` / 1000 mm/m) * `scale-denominator`, where the _physicalMetersPerPixel_ are not necessarily the same as the CRS units (even if those units are expressed in meters) for the region of that CRS consisting of the map subset being returned, +
- assert that an HTTP 4xx error is returned if the `scale-denominator` parameter is used together with `width` and/or `height` and the implementation does not declare conformance to the <<rc_table_spatial-subsetting, _spatial subsetting_>> requirements class (which specifies that the `width` and `height` parameters can also take on a subsetting role), +
- assert that an HTTP 4xx error is returned if the `scale-denominator` parameter is used together with `width` and/or `height` as well as a `bbox` (or equivalent `subset` parameter for a spatial dimension), +
- assert that, if the `scale-denominator` parameter is omitted, the implementation computes it as needed (for purposes such as applying scale-dependent symbology rules) based on the default or selected dimensions, display resolution, and the spatial subset of the map to return, +
- assert that, for implementations also supporting "Subsetting", when the spatial subset of the map is not specified in the request, the `scale-denominator` value (default or specified) is used to compute this bounding box, taking into consideration the display resolution as well as the default or specified dimensions.
--
====

=== Conformance Class "Display Resolution"

[[conf_display-resolution,/conf/display-resolution]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/display-resolution
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/display-resolution
classification:: Target Type:Web API
abstract-test:: /conf/display-resolution/mm-per-pixel-definition
abstract-test:: /conf/display-resolution/map-success
====

==== Abstract Test for Requirement `mm-per-pixel` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/display-resolution/mm-per-pixel-definition
target:: /req/display-resolution/mm-per-pixel-definition
test-purpose:: Verify that the implementation supports the `mm-per-pixel` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `mm-per-pixel` parameter, for different styles if styled maps are supported, combining all possibilities of with and without `width` and/or `height` parameters, with and without `bbox` and `center` parameter if spatial subsetting is supported, with and without `mm-per-pixel` parameter if display resolution is supported +
*Then:* +
- assert that the implementation interprets `mm-per-pixel` as the size (in millimeters) of a rendering device pixel, +
- assert that an HTTP 4xx error is returned if the `mm-per-pixel` value is not a positive number, +
- assert that, if the parameter `mm-per-pixel` is not provided, the server assumes that the pixel size is 0.28 millimeters (90.71 pixels per inch).
--
====

==== Abstract Test for Requirement Display Resolution Map Success


[abstract_test]
====
[%metadata]
identifier:: /conf/display-resolution/map-success
target:: /req/display-resolution/map-success
test-purpose:: Verify that the implementation responds correctly to map requests using the `mm-per-pixel` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `mm-per-pixel` parameter, for different styles if styled maps are supported, combining all possibilities of with and without `width` and/or `height` parameters, with and without `bbox` and `center` parameter if spatial subsetting is supported, with and without `mm-per-pixel` parameter if display resolution is supported +
*Then:* +
- assert that for an implementation supporting the Maps API _scaling_ requirements class, the implementation uses the `mm-per-pixel` value instead of the default 0.28 mm/pixel when establishing the relationship between the dimensions of the output image, the scale and the spatial extent of the map, +
- assert that the `mm-per-pixel` value is used instead of the default 0.28 mm/pixel when establishing scale for the purpose of applying styling and symbology rules to the map. For example, this needs to be considered for scale-dependent rule selectors as well as for graphical units in real world units (e.g., meters) or display units (e.g., millimeters).
--
====

=== Conformance Class "Spatial Subsetting"

[[conf_spatial-subsetting,/conf/spatial-subsetting]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/spatial-subsetting
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/spatial-subsetting
classification:: Target Type:Web API
abstract-test:: /conf/spatial-subsetting/bbox-crs
abstract-test:: /conf/spatial-subsetting/subset-crs
abstract-test:: /conf/spatial-subsetting/center-crs
abstract-test:: /conf/spatial-subsetting/bbox-definition
abstract-test:: /conf/spatial-subsetting/subset-definition
abstract-test:: /conf/spatial-subsetting/subset-response
abstract-test:: /conf/spatial-subsetting/center-definition
abstract-test:: /conf/spatial-subsetting/width-height
abstract-test:: /conf/spatial-subsetting/map-success
====

==== Abstract Test for Requirement `bbox-crs` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/bbox-crs
target:: /req/spatial-subsetting/bbox-crs
test-purpose:: Verify that the implementation supports the `bbox-crs` parameter for specifying the CRS of the `bbox` parameter correctly
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using `bbox` and `bbox-crs` parameter for different values, as well as different values for the `crs` parameter if supported and applicable, +
*Then:* +
- assert that the map retrieval operation supports a query parameter `bbox-crs` with a string, +
- assert that for Earth centric data, the implementation supports https://www.opengis.net/def/crs/OGC/1.3/CRS84 as a value, +
- assert that if the bbox-crs is not indicated https://www.opengis.net/def/crs/OGC/1.3/CRS84 is assumed, +
- assert that if the storage (native) CRS is known, the storage CRS is supported as a value. Other conformance classes may allow additional values (see `crs` parameter definition), +
- assert that the CRS expressed as URIs or as safe CURIEs is supported, +
- assert that if the `bbox` parameter is not used, the `bbox-crs` is ignored.
--
====

==== Abstract Test for Requirement `subset-crs` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/subset-crs
target:: /req/spatial-subsetting/subset-crs
test-purpose:: Verify that the implementation supports the `subset-crs` parameter for specifying the CRS of the `subset` parameter correctly
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using `subset` and `subset-crs` parameter for different values (using the correct spatial axes), as well as different values for the `crs` parameter if supported and applicable, +
*Then:* +
- assert that the map operation supports a parameter `subset-crs` with a string, +
- assert that for Earth centric data, https://www.opengis.net/def/crs/OGC/1.3/CRS84 is supported as a value, +
- assert that if the `subset-crs` is not indicated https://www.opengis.net/def/crs/OGC/1.3/CRS84 is assumed, +
- assert that if the storage (native) CRS is known, the storage CRS is supported as a value. Other requirements classes may allow additional values (see crs parameter definition), +
- assert that CRS expressed as URIs or as safe CURIEs is supported, +
- assert that if no `subset` parameter referring to an axis of the CRS is used, the `subset-crs` is ignored.
--
====

==== Abstract Test for Requirement `center-crs` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/center-crs
target:: /req/spatial-subsetting/center-crs
test-purpose:: Verify that the implementation supports the `center-crs` parameter for specifying the CRS of the `center` parameter correctly
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using `center` and `center-crs` parameter for different values, as well as different values for the `crs` parameter if supported and applicable, +
*Then:* +
- assert that the map retrieval operation supports a parameter `center-crs` with a string, +
- assert that for Earth centric data, https://www.opengis.net/def/crs/OGC/1.3/CRS84 is supported as a value, +
- assert that if the `center-crs` is not used, https://www.opengis.net/def/crs/OGC/1.3/CRS84 is assumed, +
- assert that if the storage (native) CRS is known, the storage CRS is supported as a value, +
- assert that CRS expressed as URIs or as safe CURIEs are supported, +
- assert that if no `center` parameter is used, the `center-crs` is ignored.
====

==== Abstract Test for Requirement `bbox` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/bbox-definition
target:: /req/spatial-subsetting/bbox-definition
test-purpose:: Verify that the implementation supports the `bbox` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `bbox` parameter (with and without the `bbox-crs` parameter), +
*Then:* +
- assert that the map operation supports a parameter `bbox` with a comma-separated list of four or six floating point numbers. +
If the bounding box consists of six numbers, the first three numbers are the coordinates of the lower bound corner of a three-dimensional bounding box and the last three are the coordinates of the upper bound corner.
The axis order is determined by the `bbox-crs` parameter value or longitude and latitude if the parameter is missing (https://www.opengis.net/def/crs/OGC/1.3/CRS84 axis order for a 2D bounding box,
https://www.opengis.net/def/crs/OGC/1.3/CRS84h for a 3D bounding box).
For example in https://www.opengis.net/def/crs/OGC/1.3/CRS84 the order is left_long, lower_lat, right_long, upper_lat, +
- assert that if the `bbox` parameter is used together with the `center` and/or with a `subset` parameter including any of the dimensions corresponding to those of the map bounding box, the server returns a 4xx client error.
--
====

==== Abstract Test for Requirement spatial subsetting `subset` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/subset-definition
target:: /req/spatial-subsetting/subset-definition
test-purpose:: Verify that the implementation supports the `subset` parameter for spatial subsetting
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `subset` parameter (with and without the `subset-crs` parameter, for the correct spatial axes), +
*Then:* +
- assert that the axis names `Lat` and `Lon` are supported for geographic CRS and `E` and `N` for projected CRS, which are to be interpreted as the best matching spatial axis in the CRS definition, +
- assert that if a third spatial dimension is supported (if the resource's spatial extent bounding box is three dimensional), the implementation also supports a `h` dimension. This is the elevation above the ellipsoid in EPSG:4979 or CRS84h for geographic CRS and `z` for projected CRS, which are interpreted as the vertical axis in the CRS definition, +
- assert that an 4xx error status code is returned if an axis name in the subset parameter value does not correspond to one of the axes of the subsetting CRS, is not an alias recommended to be supported (`lat`, `Latitude`, `latitude`, `lon`, `long`, `Long`, `Longitude`, `longitude`, `e`, `easting`, `Easting`, `x`, `X`, `n`, `y`, `Y`, `Northing`, `northing`, `z`, `Z`, `H`), and is not defined in the context of another supported requirements class, +
- assert that if the _interval_ values fall entirely outside the range of valid values defined for the identified axis, a 204 or 404 status code is returned, +
- assert that, for a CRS where an axis can wrap around, such as subsetting across the dateline (anti-meridian) in a geographic CRS, a _low_ value greater than _high_ is supported to indicate an extent crossing that wrapping point, +
- assert that coordinates are interpreted as values for the named axis of the CRS specified in the `subset-crs` parameter value or in https://www.opengis.net/def/crs/OGC/1.3/CRS84 (https://www.opengis.net/def/crs/OGC/1.3/CRS84h for vertical dimension) if the `subset-crs` parameter is missing, +
- assert that if the `subset` parameter including any of the dimensions corresponding to those of the map bounding box is used with a `bbox` and/or `center` parameter, the server returns a 4xx error, +
- assert that multiple `subset` parameters are interpreted, as if all dimension subsetting values were provided in a single `subset` parameter (comma separated).
--
====

==== Abstract Test for Requirement map subset response


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/subset-response
target:: /req/spatial-subsetting/subset-response
test-purpose:: Verify that the implementation responds correctly to map requests using the `subset` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `subset` (with and without the `subset-crs` parameter) +
*Then:* +
- assert that only the part of the resource that falls within the bounds of the subset interval and/or corresponds to the single point value is returned.
--
====

==== Abstract Test for Requirement `center` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/center-definition
target:: /req/spatial-subsetting/center-definition
test-purpose:: Verify that the implementation supports the `center` parameter correctly
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `center` parameter (with and without the `center-crs` parameter), +
*Then:* +
- assert that a `center` parameter is supported to specify the center of the subset of the map to include, with coordinates in the CRS specified in the `center-crs` parameter value or in https://www.opengis.net/def/crs/OGC/1.3/CRS84 if the `center-crs` parameter is missing, +
- assert that if the `center` parameter is used together with the `bbox` and/or with a `subset` parameter including any of the dimensions corresponding to those of the map bounding box, the server returns a 4xx client error.
--
====

==== Abstract Test for Requirement subsetting `width` and `height` parameters definition


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/width-height
target:: /req/spatial-subsetting/width-height
test-purpose:: Verify that the implementation supports the `width` and `height` parameter for spatial subsetting when used together with the `center` and/or the `scale-denominator` parameters
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `center` parameter together, with the `width` and/or `height` (with and without the `center-crs` parameter), with and without the `scale-denominator` parameter if scaling is supported +
*Then:* +
- assert that when the `center` parameter and/or the `scale-denominator` parameter is used, or if the _scaling_ conformance class is not supported, a `width` and `height` parameter specifying the subset of the map to return around the specified or default center of the map is supported, +
- assert that the scale of the map is considered whether returning the map at a native scale or resampled (e.g., using the _scaling_ conformance class `scale-denominator` parameter), as well as the display resolution (either the default 0.28 mm/pixel, or the one specified by the `mm-per-pixel` parameter of the _display resolution_ conformance class).
--
====

==== Abstract Test for Requirement map subset success


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/map-success
target:: /req/spatial-subsetting/map-success
test-purpose:: Verify that the implementation responds correctly to map requests using subsetting parameters (`bbox`, `subset` or `center`)
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `bbox` (with and without the `bbox-crs` parameter), `subset` (with and without the `subset-crs` parameter), and `center` parameter (with and without the `center-crs` parameter, with the `width` and/or `height` parameter, with and without the `scale-denominator` parameter if scaling is supported +
*Then:* +
- assert that the content of the response represents elements inside or intersecting with the spatial extent of the geographical area of the map identified with the subsetting coordinates.
--
====

=== Conformance Class "Date and Time"

[[conf_datetime,/conf/datetime]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/datetime
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/datetime
classification:: Target Type:Web API
abstract-test:: /conf/datetime/datetime-definition
abstract-test:: /conf/datetime/datetime-response
abstract-test:: /conf/datetime/subset-definition
abstract-test:: /conf/datetime/subset-response
abstract-test:: /conf/datetime/axis
abstract-test:: /conf/datetime/map-success
====

==== Abstract Test for Requirement `datetime` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/datetime/datetime-definition
target:: /req/datetime/datetime-definition
test-purpose:: Verify that the implementation supports the `datetime` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `datetime` parameter +
*Then:* +
- assert that the implementation supports an `instant` defined as specified by link:https://tools.ietf.org/html/rfc3339#section-5.6[RFC 3339, 5.6], with the exception that the server is only required to support the `Z` UTC time notation, and not required to support local time offsets, + 
- assert that time intervals unbounded at the start or end are supported using a double-dot (`..`) or an empty string for the start/end.
--
====

==== Abstract Test for Requirement `datetime` parameter response


[abstract_test]
====
[%metadata]
identifier:: /conf/datetime/datetime-response
target:: /req/datetime/datetime-response
test-purpose:: Verify that the implementation responds correctly to map requests using the `datetime` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `datetime` parameter +
*Then:* +
- assert that if the `datetime` parameter is provided by the client and supported by the server, then only resources that have a temporal geometry that intersects the temporal information in the `datetime` parameter are part of the result set, +
- assert that using a `datetime` parameter all resources that does not have a temporal information associate are present in the map.
--
====

==== Abstract Test for Requirement temporal `subset` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/datetime/subset-definition
target:: /req/datetime/subset-definition
test-purpose:: Verify that the implementation supports temporal subsetting using the `subset` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `subset` parameter with the `time` axis +
*Then:* +
- assert that the implementation supports a `subset` parameter, consisting of an axis name (`time`) followed by parentheses within which can be specified an interval consisting of two "time coordinate"s separated by a colon (`:`), or a single "time coordinate", where a "time coordinate" consists of a single number, a string or an asterisk (`\*`), +
- assert that the implementation supports an axis name `time`, +
- assert that the implementation returns a 4xx status code if the axis name is not `time` (or its recommended aliases `Time`, `t` and `T`) and is not recognized in the context of another requirements class, +
- assert that if "time coordinate"s fall entirely outside the range of valid values defined for the identified axis, a 204 or 404 status code is returned, +
- assert that "time coordinates" are interpreted as values for the CRS specified in the temporal extent, or Gregorian UTC time if it is not specified in the temporal extent, +
- assert that when Gregorian UTC time is used, the implementation supports time expressed using RFC 3339 section 5.6, with only support for the UTC (`Z`) notation required (meaning that support for local time offsets should not be tested),
as well as the following additional partial date and time formats: `yyyy`, `yyyy-mm`, `yyyy-mm-dd`, `yyyy-mm-ddThhZ`, `yyyy-mm-ddThh:mmZ`, +
- assert that the implementation supports a `*` value indicating the earliest available time (for `low`) or the latest available time (for `high` and when used as a single time instant), +
- assert that multiple `subset` parameters is interpreted as if all dimension subsetting values were provided in a single `subset` parameter (comma separated).
--
====

==== Abstract Test for Requirement temporal subset response


[abstract_test]
====
[%metadata]
identifier:: /conf/datetime/subset-response
target:: /req/datetime/subset-response
test-purpose:: Verify that the implementation responds correctly to temporal subsetting requests using the `subset` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `subset` parameter with the `time` axis +
*Then:* +
- assert that only the part of the resource that falls within the bounds of the subset interval and/or corresponds to the single point value is returned.
--
====

==== Abstract Test for Requirement temporal axis


[abstract_test]
====
[%metadata]
identifier:: /conf/datetime/axis
target:: /req/datetime/axis
test-purpose:: Verify that the implementation supports the `time` axis for temporal subsetting using the `subset` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `subset` parameter with the `time` axis +
*Then:* +
- assert that to subset a generic time dimension, the server supports `time` as axis name in the `subset` parameter.
--
====

==== Abstract Test for Requirement temporal subsetting success


[abstract_test]
====
[%metadata]
identifier:: /conf/datetime/map-success
target:: /req/datetime/map-success
test-purpose:: Verify that the implementation responds correctly to temporal subsetting requests
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `subset` parameter with the `time` axis +
*Then:* +
- assert that the content of that response is consistent with the requested datetime.
--
====

=== Conformance Class "General Subsetting"

[[conf_general-subsetting,/conf/general-subsetting]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/general-subsetting
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/general-subsetting
classification:: Target Type:Web API
abstract-test:: /conf/general-subsetting/uniform-additional-dimensions
abstract-test:: /conf/general-subsetting/subset-definition
====

==== Abstract Test for Requirement uniform additional dimensions

[abstract_test]
====
[%metadata]
identifier:: /conf/general-subsetting/uniform-additional-dimensions
target:: /req/general-subsetting/uniform-additional-dimensions
test-purpose:: Verify that the implementation describes additional dimensions in a uniform manner
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core for which an extent description is available (e.g., conforming successfully to either the "Collection Map" or "Dataset Map") +
*When:* retrieving the description of the data resource e.g., the collection (for "Collection Map") or the landing page (for "Dataset Map")  +
*Then:* +
- assert that the extent of any additional dimension(s) beyond temporal and spatial is described in a way similar to the temporal dimension,
using the name of the dimension as a key and an object as value, with that object containing an `interval` property, a URI for the semantic `definition`, a `unit` of measure if applicable,
and a `grid` definition if applicable, as specified in https://raw.githubusercontent.com/opengeospatial/ogcapi-maps/master/openapi/schemas/common-geodata/extent-uad.yaml[_extent-uad.yaml_].
--
====

==== Abstract Test for Requirement general subsetting `subset` parameter

[abstract_test]
====
[%metadata]
identifier:: /conf/general-subsetting/subset-definition
target:: /req/general-subsetting/subset-definition
test-purpose:: Verify that the implementation supports general subsetting using the `subset` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `subset` parameter for an additional dimension besides space and time +
*Then:* +
- assert that the implementation supports a `subset` parameter, consisting of an axis name followed by an interval or single value within parentheses, where an interval is separated by a colon (`:`), +
- assert that all additional dimensions described in the extent of the collection are supported as axis name, +
- assert that a 4xx error status code is returned if an axis name not corresponding to the name of one of the _additional_ dimensions in the extent of the collection, and not corresponding to the required
  or recommended aliases in the spatial subsetting and temporal subsetting requirements classes is used, +
- assert that when the _intervalOrSingle_ values fall entirely outside the range of valid values defined for the identified axis, a 204 or 404 status code is returned, +
- assert that for an axis that can wrap around, a _low_ value greater than _high_ are supported to indicate an extent crossing that wrapping point, +
- assert that multiple subset parameters are interpreted as if all dimension subsetting values were provided in a single `subset` parameter (comma separated).
--
====

=== Conformance Class "Coordinate Reference System"

[[conf_crs,/conf/crs]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/crs
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/crs
classification:: Target Type:Web API
abstract-test:: /conf/crs/crs-definition
abstract-test:: /conf/crs/map-success
====

==== Abstract Test for Requirement `crs` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/crs/crs-definition
target:: /req/crs/crs-definition
test-purpose:: Verify that the implementation supports the output `crs` parameter for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps with the `crs` parameter for different available CRS and without +
*Then:* +
- assert that the map operation supports a `crs` string parameter, +
- assert that all CRSs listed in the collection (or collections) description are supported, or that `[OGC:CRS84]` is supported if no list of CRS is available, +
- assert that, if the spatial subsetting requirements class is also supported, the `bbox-crs` and the `subset-crs` also support those available CRS values when the same value is also specified in the `crs` parameter, +
- assert that the CRS values can be expressed either as URIs or as safe CURIEs.
--
====


==== Abstract Test for Requirement CRS map success


[abstract_test]
====
[%metadata]
identifier:: /conf/crs/map-success
target:: /req/crs/map-success
test-purpose:: Verify that the implementation responds correctly to map requests using the `crs` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps with the `crs` parameter for different available CRS and without +
*Then:* +
- assert that the content of the map response is consistent with the requested CRS.
--
====

=== Conformance Class "Orientation"

[[conf_orientation,/conf/orientation]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/orientation
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/orientation
classification:: Target Type:Web API
abstract-test:: /conf/orientation/orientation
abstract-test:: /conf/orientation/response-headers
====

==== Abstract Test for Requirement `orientation` parameter

[abstract_test]
====
[%metadata]
identifier:: /conf/orientation/orientation
target:: /req/orientation/orientation
test-purpose:: Verify that the implementation supports the `orientation` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps with the `orientation` parameter for different values and without +
*Then:* +
- assert that an orientation parameter that specifies the amount by which to rotate a map is supported , expressed as counterclockwise degrees, resulting in the viewing perspective being rotated by that same orientation in a clockwise direction, +
- assert that when the `orientation` parameter is not specified, a zero orientation value is be assumed, +
- assert that the orientation is applied to the map with the center of the selected spatial subset as the pivot point, or the center of the map if none is specified, +
- assert that if an `orientation` parameter is used together with `subset` or `bbox` spatial subsetting parameter,
the counterclockwise orientation is applied to the four corners of the clipping box associated to that subset,
as if the equivalent `center`, `width` and `height` spatial subsetting query parameters were used instead, avoiding leaving empty corners in the final rotated map image.
--
====

==== Abstract Test for Requirement orientation response headers


[abstract_test]
====
[%metadata]
identifier:: /conf/orientation/response-headers
target:: /req/orientation/response-headers
test-purpose:: Verify that the implementation includes the correct response headers for map requests using the `orientation` parameter.
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps with the `orientation` parameter for different values and without +
*Then:* +
- assert that for responses to a map request where the `orientation` query parameter is used, a response header `Content-Orientation: [value in decimal degrees]` corresponding to the orientation of the map is returned, +
- assert that for responses to map request where the `orientation` query parameter is used, the `Content-Bbox` response header reflects the bounding box in the map output CRS prior to the orientation being applied.
--
====

=== Conformance Class "Custom Projection CRS"

[[conf_projection,/conf/projection]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/projection
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/projection
classification:: Target Type:Web API
abstract-test:: /conf/projection/crs-proj-method
abstract-test:: /conf/projection/crs-proj-params
abstract-test:: /conf/projection/crs-proj-center-definition
abstract-test:: /conf/projection/crs-datum
abstract-test:: /conf/projection/response-headers
abstract-test:: /conf/projection/projections-resource
abstract-test:: /conf/projection/projections-response
====

==== Abstract Test for Requirement `crs-proj-method` parameter


[abstract_test]
====
[%metadata]
identifier:: /conf/projection/crs-proj-method
target:: /req/projection/crs-proj-method
test-purpose:: Verify that the implementation supports the `crs-proj-method` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to <<conf_core>> and passing <<conf_projection_projections-response>> +
*When:* retrieving maps with the `crs-proj-method` parameter for different available values as listed in `/projectionsAndDatums` +
*Then:* +
- assert that a `crs-proj-method` parameter supporting selection of a projection operation method is supported, +
- assert that CURIEs are supported in addition to URIs to specify the projection method.
--
====

==== Abstract Test for Requirement `crs-proj-params` parameter


[abstract_test]
====
[%metadata]
identifier:: /conf/projection/crs-proj-params
target:: /req/projection/crs-proj-params
test-purpose:: Verify that the implementation supports the `crs-proj-params` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to <<conf_core>> and passing <<conf_projection_projections-response>> +
*When:* retrieving maps with the `crs-proj-method` parameter for different available values and different values of the associated method parameters (specified using the `crs-proj-params` query parameter) as listed in `/projectionsAndDatums` +
*Then:* +
- assert that a `crs-proj-params` parameter is supported that enables selection of one or more value for operation method parameters, with values in between parentheses `(` `)` following the URI of
a projection parameter, and different parameters separated by value (e.g., `crs-proj-params=[epsg-parameter:8823](40),[epsg-parameter:8824](90)`), +
- assert that in addition to CURIEs, URIs are also supported to specify the projection parameters.
--
====

==== Abstract Test for Requirement  `crs-proj-center` parameter


[abstract_test]
====
[%metadata]
identifier:: /conf/projection/crs-proj-center-definition
target:: /req/projection/crs-proj-center-definition
test-purpose:: Verify that the implementation supports the `crs-proj-center` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to <<conf_core>> and passing <<conf_projection_projections-response>> +
*When:* retrieving maps with the `crs-proj-method` parameter for different available values as listed in `/projectionsAndDatums` and the `crs-proj-center` parameter for different values +
*Then:* +
- assert that a `crs-proj-center` parameter of the form `Lat(centerLat),Lon(centerLon)` is supported to facilitate the selection of the most relevant projection parameters to center a custom projection, +
- assert that the projection center `Lat` value is mapped to the first matching operation method parameter available for the selected operation method of the projection query parameter, in the epsg-parameter order 8832, 8823, 8801, 8811, +
- assert that the projection-center `Lon` value is mapped to the first matching operation method parameter available for the selected operation method of the projection query parameter, in the epsg-parameter order 8802, 8812, 8833.
--
====

==== Abstract Test for Requirement `crs-datum` parameter


[abstract_test]
====
[%metadata]
identifier:: /conf/projection/crs-datum
target:: /req/projection/crs-datum
test-purpose:: Verify that the implementation supports the `crs-datum` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to <<conf_core>> and passing <<conf_projection_projections-response>> +
*When:* retrieving maps with the `crs-datum` parameter for different available values as listed in `/projectionsAndDatums` +
*Then:* +
- assert that a `crs-datum` parameter as a URI allowing to select a datum for the output CRS is supported, +
- assert that CURIEs are supported in addition to URIs to specify the datum parameter, +
- assert that a if a `crs-datum` parameter is not specified, the native (storage) CRS datum is assumed (the WGS84 ensemble `[epsg-datum:6326]` datum is assumed if the native CRS is not declared).
--
====

==== Abstract Test for Requirement custom CRS projection response headers


[abstract_test]
====
[%metadata]
identifier:: /conf/projection/response-headers
target:: /req/projection/response-headers
test-purpose::  Verify that the implementation responds to map requests using the `crs-proj-method` parameter and/or `crs-datum` with the correct response headers
test-method::
+
--
*Given:* a map resource that conformed successfully to <<conf_core>> and passing <<conf_projection_projections-response>> +
*When:* retrieving maps with the `crs-proj-method` parameter for different available values, different values of the associated method parameters (using both `crs-proj-center` and `crs-proj-params`), and different values for `crs-datum` as listed in `/projectionsAndDatums` +
*Then:* +
- assert that for responses to map request where the `crs-proj-method` query parameter was used, a response header `Content-Crs-Method: <[URI]>` including the URI of the projection operation method is returned, +
- assert that a response header `Content-Crs-Method-Params: <URI>=[value]; ...` is returned, including the URI of the projection operation parameters and its value for each parameter specified using the `crs-proj-method` or `crs-proj-center` query parameters, +
- assert that for responses to map request where the `crs-datum` query parameter was used, a response header `Content-Crs-Datum: <[URI]>` corresponding to the URI of the projection operation method is returned, +
- assert that for responses to map requests specifying the `crs-proj-method` query parameter, a `Content-Crs` response header is not included, +
- assert that for responses to map requests specifying the `crs-proj-method` query parameter, the CRS of the `Content-Bbox` response header coordinates is in the custom CRS defined by this operation method and its parameters.
--
====

==== Abstract Test for Requirement `/projectionsAndDatums` resource


[[conf_projection_projections-resource,/conf/projection/projections-resource]]
[abstract_test]
====
[%metadata]
identifier:: /conf/projection/projections-resource
target:: /req/projection/projections-resource
test-purpose:: Verify that the implementation supports retrieving the list of available projection operation methods, their parameters, and the list of available datums at `/projectionsAndDatums`
test-method::
+
--
*Given:* an API implementation being tested +
*When:* retrieving the `/projectionsAndDatums` resource +
*Then:* +
- assert that a GET operation at `/projectionsAndDatums` providing a JSON representation is supported.
--
====

==== Abstract Test for Requirement `/projectionsAndDatums` response

[[conf_projection_projections-response,/conf/projection/projections-response]]
[abstract_test]
====
[%metadata]
identifier:: /conf/projection/projections-response
target:: /req/projection/projections-response
test-purpose:: Verify that the implementation responds correctly to a request for the `/projectionsAndDatums` resource, conforming to the JSON schema and using the correct URIs
test-method::
+
--
*Given:* an API implementation being tested passing <<conf_projection_projections-resource>>  +
*When:* retrieving the `/projectionsAndDatums resource` +
*Then:* +
- assert that the implementation includes in its response for the `/projectionsAndDatums` resource the complete list of custom CRS projection operation methods supported for map retrieval operations, +
- assert that the implementation includes in its response for the `/projectionsAndDatums` resource the complete list of custom CRS datums supported for map retrieval operations, +
- assert that in the JSON representation, the list of supported projection operation methods is provided as a dictionary (associative array) value for a `methods` property associating operation method objects
(including optional `title` and `description` properties) to the corresponding identifiers to be used as values for the `crs-proj-method` query parameter, +
- assert that these operation method identifiers are safe CURIEs when a registered URI exists for the method, +
- assert that in the JSON representation, the list of supported datums are provided as a dictionary (associative array) value for a `datums` property associating datum objects to the corresponding identifiers to be used as values for the `crs-datum` query parameter, +
- assert that these datum identifiers are safe CURIEs when a registered URI exists for the datum, +
- assert that the datum object includes an `ellipsoid` property specifying the safe CURIE for the associated ellipsoid and may contain additional optional `title` and `description` properties, +
- assert that in the JSON representation, the operation method objects include all valid parameters for that method as a dictionary (associative array) value for a `parameters` property to method parameters object (including optional `title` and `description` properties) to the corresponding identifiers to be used as values for the `crs-proj-params` query parameter, +
- assert that these method parameters are safe CURIEs when a registered URI exists for the parameter (to avoid repeating the same parameter, those objects may use a JSON pointer (`$ref`) to a top-level `parameters` property in the same custom projections JSON document), +
- assert that in the JSON representation, the operation method objects include `centerLatParam` and/or `centerLonParam` properties (as applicable) whose values are the identifiers corresponding to the parameters for which values specified for the `crs-proj-center` query parameter will be mapped, in a manner consistent with requirement `/req/projection/crs-proj-center-definition`.
--
====

=== Conformance Class "Collection Map"

[[conf_collection-map,/conf/collection-map]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collection-map
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/collection-map
classification:: Target Type:Web API
abstract-test:: /conf/collection-map/desc-links
abstract-test:: /conf/collection-map/desc-crs
abstract-test:: /conf/collection-map/map-operation
====

==== Abstract Test for Requirement collection description links


[abstract_test]
====
[%metadata]
identifier:: /conf/collection-map/desc-links
target:: /req/collection-map/desc-links
test-purpose:: Verify that the implementation links correctly from the collection description resource to the map resource
test-method::
+
--
*Given:* a collection from an API implementation conforming to OGC API - Common - Part 2: Geospatial Data "Collections" conformance class +
*When:* retrieving the JSON representation of the description for that collection +
*Then:* +
- assert that the OGC API collection description includes a link with relation type `https://www.opengis.net/def/rel/ogc/1.0/map` (or `[ogc-rel:map]`) and the href pointing to a the map resource for this collection.
--
====

==== Abstract Test for Requirement collection description CRS

[abstract_test]
====
[%metadata]
identifier:: /conf/collection-map/desc-crs
target:: /req/collection-map/desc-crs
test-purpose:: Verify that the implementation describes the supported CRS correctly in its collection description resources
test-method::
+
--
*Given:* an API implementation conforming to OGC API - Common - Part 2: Geospatial Data "Collections" conformance class +
*When:* retrieving the JSON representation of the description for that collection +
*Then:* +
- assert that the `crs` property in the collection object of a geospatial collection contains URIs or safe CURIEs for the list of CRSs supported by the server for that collection, +
- assert that if the collection is available more efficiently (e.g., if it is stored in the server in that CRS) using a particular CRS (the native CRS, also _called storage CRS_)
that is not https://www.opengis.net/def/crs/OGC/1.3/CRS84, a `storageCrs` property in the collection object of a geospatial collection is the URI or the safe CURIE for that CRS, +
- assert that if a `storageCrs` property is used and that is not https://www.opengis.net/def/crs/OGC/1.3/CRS84, an overall bounding box (and optional inner bounding boxes for sparse data)
is provided in a `storageCrsBbox` property within the `spatial` dimension of the `extent` following the same schema as the CRS84 `bbox`.
--
====

==== Abstract Test for Requirement collection map operation


[abstract_test]
====
[%metadata]
identifier:: /conf/collection-map/map-operation
target:: /req/collection-map/map-operation
test-purpose:: Verify that the implementation supports retrieving maps from an OGC API a collection as defined in the OGC API  Common Standard.
test-method::
+
--
*Given:* a collection correctly linking to a map resource as per /conf/collection-map/desc-links +
*When:* retrieving a map for that collection resource as per /conf/core +
*Then:* +
- assert that every OGC API collection available as a map supports an HTTP GET operation to a URL `/collections/{collectionId}/map` to retrieve a map from that collection resource.
--
====

=== Conformance Class "Dataset Map"

[[conf_dataset-map,/conf/dataset-map]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/dataset-map
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/dataset-map
classification:: Target Type:Web API
abstract-test:: /conf/dataset-map/landingpage
abstract-test:: /conf/dataset-map/desc-extent
abstract-test:: /conf/dataset-map/desc-crs
abstract-test:: /conf/dataset-map/operation
====

==== Abstract Test for Requirement dataset landing page


[abstract_test]
====
[%metadata]
identifier:: /conf/dataset-map/landingpage
target:: /req/dataset-map/landingpage
test-purpose:: Verify that the implementation supports linking properly from an OGC API landing page to a map resource
test-method::
+
--
*Given:* a dataset provided by an API implementation conforming to OGC API - Common - Part 1: Core +
*When:* retrieving the JSON representation of the landing page description for that dataset +
*Then:* +
- assert that the deployed API endpoint landing page includes a link with relation type `https://www.opengis.net/def/rel/ogc/1.0/map` (or `[ogc-rel:map]`) to the dataset map URL at `/map`.
--
====

==== Abstract Test for Requirement dataset description extent


[abstract_test]
====
[%metadata]
identifier:: /conf/dataset-map/desc-extent
target:: /req/dataset-map/desc-extent
test-purpose:: Verify that the implementation describes the extent of the dataset correctly from the landing page
test-method::
+
--
*Given:* a dataset provided by an API conforming to OGC API - Common - Part 1: Core +
*When:* retrieving the JSON representation of the landing page description for that dataset +
*Then:* +
- assert that an extent CRS is provided in an "extent" property of the API landing page following the same schema as the "extent" property for the collection (see OGC API - Common: Part 2).
--
====

==== Abstract Test for Requirement dataset description CRS


[abstract_test]
====
[%metadata]
identifier:: /conf/dataset-map/desc-crs
target:: /req/dataset-map/desc-crs
test-purpose:: Verify that the implementation describes the supported CRS correctly in its landing page resource
test-method::
+
--
*Given:* a dataset provided by an API conforming to OGC API - Common - Part 1: Core +
*When:* retrieving the JSON representation of the landing page description for that dataset +
*Then:* +
- assert that the `crs` property in the landing page of a dataset contains URIs or safe CURIEs for the list of CRSs supported by the dataset as a whole, +
- assert that if the dataset is available more efficiently using a particular CRS that is not https://www.opengis.net/def/crs/OGC/1.3/CRS84, a `storageCrs` property in the landing page of a dataset is the URI or
the safe CURIE for that CRS as a value, +
- assert that if a `storageCrs` property is used and that is not https://www.opengis.net/def/crs/OGC/1.3/CRS84, an overall bounding box (and optional inner bounding boxes for sparse data) is provided in
a `storageCrsBbox` property within the `spatial` dimension of the `extent` following the same schema as the CRS84 `bbox`.
--
====

==== Abstract Test for Requirement dataset map operation


[abstract_test]
====
[%metadata]
identifier:: /conf/dataset-map/operation
target:: /req/dataset-map/operation
test-purpose:: Verify that the implementation supports retrieving dataset maps a resource exposed by the OGC Maps API implementation
test-method::
+
--
*Given:* an OGC API dataset correctly linking to a map resource as per /conf/dataset-map/landingpage +
*When:* retrieving a map for that dataset resource as per /conf/core +
*Then:* +
- assert that the implementation supports an HTTP GET operation for the `/map` URL to retrieve a map from the dataset API endpoint in the default style.
--
====

=== Conformance Class "Styled Map"

[[conf_styled-map,/conf/styled-map]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/styled-map
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/styled-map
classification:: Target Type:Web API
abstract-test:: /conf/styled-map/desc-links
abstract-test:: /conf/styled-map/map-operation
====

==== Abstract Test for Requirement styled map links


[abstract_test]
====
[%metadata]
identifier:: /conf/styled-map/desc-links
target:: /req/styled-map/desc-links
test-purpose:: Verify that the implementation links correctly from a style resource to a map resource
test-method::
+
--
*Given:* a list of styles provided by an API implementation conforming to OGC API - Styles - Part 1: Core +
*When:* retrieving the JSON representation of that list of styles +
*Then:* +
- assert that if the deployed API endpoint has a mechanism to expose links associated with styled geospatial resoures
(e.g., the OGC API - Styles list of styles at `/styles` for a dataset or at `/collections/{collectionId}/styles` for a collection),
those styled resources include a link with link relation `https://www.opengis.net/def/rel/ogc/1.0/map` (or `[ogc-rel:map]`) and the href pointing to the map associated with that styled resource.
--
====

==== Abstract Test for Requirement styled map operation


[abstract_test]
====
[%metadata]
identifier:: /conf/styled-map/map-operation
target:: /req/styled-map/map-operation
test-purpose:: Verify that the implementation supports retrieving maps from _OGC API - Styles_ style resources
test-method::
+
--
*Given:* a style correctly linking to a map resource as per /conf/styled-map/desc-links +
*When:* retrieving a map for that style as per /conf/core +
*Then:* +
- assert that every resource for which a styled map is available supports an HTTP GET operation to a `.../styles/{styleId}/map` URL to retrieve a map for a particular style
(e.g., `/collections/{collectionId}/styles/{styleId}` for a styled collection map or `/styles/{styleId}/map` for a styled dataset map).
--
====

=== Conformance Class "PNG"

[[conf_png,/conf/png]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/png
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/png
classification:: Target Type:Web API
abstract-test:: /conf/png/content
====

==== Abstract Test for Requirement PNG map content


[abstract_test]
====
[%metadata]
identifier:: /conf/png/content
target:: /req/png/content
test-purpose:: Verify that the implementation supports retrieving maps negotiating for PNG content
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a PNG (`image/png`) representation of a map resource through HTTP content negotiation +
*Then:* +
- assert that every 200-response of the server with the media type `image/png` is a PNG document representing only one map, +
- assert that the colors of the PNG represent the geospatial features or coverage values in the map, +
- assert that the alpha channel of the PNG is used when partial transparency is required, +
- assert that all maps representing parts of the same resource or resources and using the same style follow the same portrayal rules.
--
====

=== Conformance Class "JPEG"

[[conf_jpeg,/conf/jpeg]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/jpeg
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/jpeg
classification:: Target Type:Web API
abstract-test:: /conf/jpeg/content
====

==== Abstract Test for Requirement JPEG map content


[abstract_test]
====
[%metadata]
identifier:: /conf/jpeg/content
target:: /req/jpeg/content
test-purpose:: Verify that the implementation supports retrieving maps negotiating for JPEG content
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a JPEG (`image/jpeg`) representation of a map resource through HTTP content negotiation +
**Then:** +
- assert that every 200-response of the server with the media type `image/jpeg` is a JPEG document representing only one map, +
- assert that the colors of the JPEG represent geospatial features and/or coverage values in the map, +
- assert that all maps representing parts of the same resource or resources and using the same style follow the same portrayal rules.
--
====

=== Conformance Class "JPEG XL"

[[conf_jpegxl,/conf/jpegxl]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/jpegxl
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/jpegxl
classification:: Target Type:Web API
abstract-test:: /conf/jpegxl/content
====

==== Abstract Test for Requirement JPEG XL map content


[abstract_test]
====
[%metadata]
identifier:: /conf/jpegxl/content
target:: /req/jpegxl/content
test-purpose:: Verify that the implementation supports retrieving maps negotiating for JPEG XL content
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a JPEG XL (`image/jxl`) representation of a map resource through HTTP content negotiation +
**Then:** +
- assert that every 200-response of the server with the media type `image/jxl` is a JPEG XL file representing only one map, +
- assert that the JPEG XL is a color image representing the geospatial features or coverage values in the map, +
- assert that all maps representing parts of the same resource or resources and using the same style follow the same portrayal rules.
--
====

=== Conformance Class "TIFF"

[[conf_tiff,/conf/tiff]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/tiff
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/tiff
classification:: Target Type:Web API
abstract-test:: /conf/tiff/content
====

==== Abstract Test for Requirement TIFF map content


[abstract_test]
====
[%metadata]
identifier:: /conf/tiff/content
target:: /req/tiff/content
test-purpose:: Verify that the implementation supports retrieving maps negotiating for TIFF and/or GeoTIFF content
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a TIFF (`image/tiff`) and GeoTIFF (`image/tiff; application=geotiff`) representation of a map resource through HTTP content negotiation +
*Then:* +
- assert that every 200-response of the server with the media type `image/tiff` is a TIFF document representing only one map, +
- assert that the TIFF file represents colors by using an image palette or RGB combination, +
- assert that all maps representing parts of the same resource or resources and using the same style follow the same portrayal rules or represent data with the same reference and units of measure.
--
====

=== Conformance Class "SVG"

[[conf_svg,/conf/svg]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/svg
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/svg
classification:: Target Type:Web API
abstract-test:: /conf/svg/content
====

==== Abstract Test for Requirement SVG map content


[abstract_test]
====
[%metadata]
identifier:: /conf/svg/content
target:: /req/svg/content
test-purpose:: Verify that the implementation supports retrieving maps negotiating for SVG content
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving an SVG (`image/svg+xml`) representation of a map resource through HTTP content negotiation +
*Then:* +
- assert that every 200-response of the server with the media type `image/svg+xml` is an SVG document representing only a map, +
- assert that the SVG coordinates inside the map start at 0,0 and end in the width and height of the request.
--
====

=== Conformance Class "HTML"

[[conf_html,/conf/html]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/html
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/html
classification:: Target Type:Web API
abstract-test:: /conf/html/content
====

==== Abstract Test for Requirement HTML map content


[abstract_test]
====
[%metadata]
identifier:: /conf/html/content
target:: /req/html/content
test-purpose:: Verify that the implementation supports retrieving maps negotiating for HTML content
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving an (`text/html`) HTML representation of a map resource HTTP content negotiation +
*Then:* +
- assert that every 200-response of the server with the media type `text/html` is an HTML document representing the geospatial data as maps.
--
====

=== Conformance Class "API Operations"

[[conf_api-operations,/conf/api-operations]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/api-operations
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/api-operations
classification:: Target Type:Web API
abstract-test:: /conf/api-operations/completeness
abstract-test:: /conf/api-operations/operation-id
====

==== Abstract Test for Requirement API Operations completeness

[abstract_test]
====
[%metadata]
identifier:: /conf/api-operations/completeness
target:: /req/api-operations/completeness
test-purpose:: Verify that the implementation completely and correctly describes the map resources
test-method::
+
--
*Given:* an API conforming to _OGC API - Common - Part 1: Core_ "Landing Page" conformance class, +
*When:* retrieving the API description +
*Then:* +
- assert that the API definition provides paths for all map, custom projections, tileset, tilesets list and tile resources provided by the API instance, +
- assert that the resource paths defined in the API definition is consistent with the links to the same resources provided by the landing page, collections, tileset and tilesets list resources, +
- assert that the resource paths defined in the API definition provides the description of the parameters that the map, tileset and tile resources need to operate that are specified in corresponding conformance classes.
--
====

==== Abstract Test for Requirement API Operation identifiers


[abstract_test]
====
[%metadata]
identifier:: /conf/api-operations/operation-id
target:: /req/api-operations/operation-id
test-purpose:: Verify that the implementation uses the correct API operation identifier suffixes to identify the resources defined in the Maps API Standard
test-method::
+
--
*Given:* an API implementation conforming to _OGC API - Common - Part 1: Core_ "Landing Page" conformance class supporting an API definition language with a concept of operation identifiers +
*When:* retrieving the API description +
- assert that the paths defined in the API definition have an operation identifier value ending with the relevant dot-separated suffix corresponding to the resource as specified in <<api-operation-id-suffixes>>.
--
====

=== Conformance Class "CORS"

[[conf_cors,/conf/cors]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/cors
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/cors
classification:: Target Type:Web API
abstract-test:: /conf/cors/cors
====

==== Abstract Test for Requirement CORS

[abstract_test]
====
[%metadata]
identifier:: /conf/cors/cors
target:: /req/cors/cors
test-purpose:: Verify that the implementation completely and correctly implement CORS
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving resources, such as the map resource, defined in the supported requirements classes from a web page at a different origin +
*Then:* +
- assert that the implementation supports CORS as defined by W3C (https://www.w3.org/TR/2020/SPSD-cors-20200602/) for these resources.
--
====
