[appendix]
:appendix-caption: Annex
== Evolution from OGC Web Map Service

=== From OGC Web Services to OGC Web APIs

OGC Web Service (OWS) Standards have historically implemented a Remote-Procedure-Call-over-HTTP architectural style using Extensible Markup Language (XML) for the metadata and capability payloads.
This was state-of-the-art when initial versions of OGC Web Services were originally designed in the late 1990s and early 2000s.
The resource-oriented RESTful Web API style is proposed as an alternative architectural style to the RPC pattern which was service-oriented.
The Web Map Service 1.3 Standard did not describe a resource oriented architectural style or a Web API definition.
This _OGC API - Maps_ Standard specifies requirements for a Web API that follows the Web architecture and the https://www.w3.org/TR/sdw-bp/[W3C/OGC best practices for sharing Spatial Data on the Web] as well as the
https://www.w3.org/TR/dwbp/[W3C best practices for sharing Data on the Web].

The _OGC API - Maps - Part 1: Core_ Standard provides the necessary elements to incorporate *_maps_* support into a broader Web API implementation.
These elements can be incorporated in an API based on _OGC API - Features - Part 1: Core_ or can be incorporated in a Web API implementation based on
_OGC API - Common - Part 1: Core_.
Both specify a kernel of a Web API approach to services that follows current resource-oriented architecture practices in the OGC.
The _OGC API - Common_ Standard provides the foundation upon which implementations of the OGC API Standards can be built.
_OGC API - Common_ can be combined with the _Maps API_ Standard and other resource-specific OGC API Standards to build an OGC standards-based API implementation.
However, the _Maps API_ Standard is specified in a way that can extend _OGC API - Common_ but does not make _OGC API - Common_ mandatory.
In this way, the _Maps API_ Standard can be reused as a building block in other APIs that do not follow the OGC API pattern.

Beside the general alignment with the architecture of the Web (e.g., consistency with HTTP/HTTPS, hypermedia controls), another goal for OGC API Standards is modularization. This goal has several facets:

* Clear separation between Core requirements and more advanced capabilities. The _OGC API - Maps - Part 1: Core_ Standard presents the requirements that are
relevant for almost any organization wanting to share or use maps at a fine-grained level. Additional capabilities deemed useful for several communities will be specified as extensions to the Core API.
* Technologies that change more frequently are decoupled and specified in separate modules ("requirements classes" in OGC terminology). This enables, for example, the use/re-use of new encodings for spatial data or Web API definition (such as new version of the OpenAPI description document).
* Modularization is not just about a single "service". OGC API Standards define building blocks that can be reused in API implementations in general. In other words, a server supporting _OGC API - Maps_ should not be seen as a standalone service. Rather it should be viewed as a collection of Web API building blocks that together implement _OGC API - Maps_ capabilities. A corollary for this is that it should be possible to implement an API that simultaneously conforms to conformance classes from the https://ogcapi.ogc.org/features/[OGC API - Features], https://ogcapi.ogc.org/coverages/[OGC API - Coverages], https://ogcapi.ogc.org/maps/[OGC API - Maps], https://ogcapi.ogc.org/tiles/[OGC API - Tiles], and other future OGC API Standards.

This approach intends to support two types of client developers:

* Those that have never heard about the OGC. Developers should be able to create a client using the Web API definition without the need to adopt a specific
OGC approach. For example, developers no longer need to read how to implement a _GetCapabilities_ document, allowing them to focus on the geospatial aspects.
* Those that want to write a "generic" client that can access implementations of OGC API Standards. In other words, common capability and metadata resources are not specific to a particular API.

As a result of following a RESTful approach, OGC API implementations are not backwards compatible with OWS implementations per se. However, a design goal is to define OGC API Standards in a way that an OGC API interface can be mapped to an OWS implementation (where appropriate). OGC API Standards are intended to be simpler and more modern, but still an evolution from the previous versions and their implementations making the transition easy (e.g., by initially implementing facades in front of the current OWS services).

=== Comparison between _WMS_ and _OGC API - Maps_

The OGC WMS and WMTS Standards share the concept of a map and the capability to create and distribute maps at a limited resolution and size.
In WMS, the number of rows and columns can be selected by the user within limits and in WMTS the number of rows and columns of the response is predefined in the tile matrix set.

The concept of a map used in OGC API Standards is more abstract than the one used in WMS. Read more about the map concept in the <<overview>>.

==== Functionality changes from WMS

One important enhancement in the _OGC API - Maps_ Standard when compared to WMS is that requests are built out of modular building blocks,
allowing different levels of complexity: From a simple map request with no parameters to a precise selection of
collections, spatiotemporal subsets, output dimensions, scale, background settings and so on.

Additionally, to accommodate different client preferences and use cases as well as maintain consistency with other OGC API
data access mechanisms such as the _OGC API - Coverages_ and _OGC API - Features_ Standards, multiple
equivalent subsetting mechanisms are supported such as subsetting by bounding box, date and time, generic dimension subset or center point.

Similarly, the ability to explicitly specify a scale denominator as a way to control down-sampling is also defined.

The concept of a display resolution (millimeters per pixel) is also introduced as an alternative to the default 0.28 mm/pixel specified in WMS,
enabling a better control on how a server renders symbology suitable for devices and printed maps of different resolutions.

A flexible mechanism to define custom CRS and re-orient the map is also introduced, offering a more comprehensive approach based on
coordinate operation (see https://docs.ogc.org/as/18-005r4/18-005r4.html, definition 3.1.8) methods, parameters and datums (implying a particular ellipsoid) compared to the _AUTO2:_ namespace for CRSs as specified in the WMS Standard. The _AUTO2_ namespace is used for “automatic” coordinate reference systems.

Finally, _OGC API - Maps_ can also be used to represent a vertical dimension. This can be done either by returning a 3D data format, by
selecting a vertical subset of features to be rendered on a 2D output, or by rendering a vertical profile.
Some examples include:

* a 3D map to be displayed on virtual reality devices,
* a 1D graph of NDVI over time for a particular point,
* a 1D graph of a temperature over a vertical profile for a given spatial point,
* intensity of rain along a latitude and vertical dimension,
* a video over a temporal axis,
* a video of temperature representing different elevation levels in different frames of the video.

==== Correspondence between WMS map metadata and OGC API Standards

In the WMS Standard, the `GetCapabilities` response provides some metadata about the server and individual `layer` sections that inform the client about layer characteristics and some restrictions useful to formulate a successful map query. In the OGC API - Maps Standard, the equivalent metadata is provided via the landing page, the list of collections, the collections details, the API definition, and the service-meta link from the landing page. Implementers of Web APIs are encouraged to make use of the mechanisms provided by other standards of the OGC API family to communicate the relevant metadata to the client.

The following table provides a reference to where some of metadata aspects at the service level are specified.

[#where-service-metadata-is,reftext='{table-caption} {counter:table-num}']
.Where some "service" metadata elements are specified
[width = "100%",options="header"]
|===
| Name in <Service> WMS 1.3 | Where in the API | property | Specified in
| Title | service metadata^2^ | title | OGC API - Common - Part 1
| Name fixed to "WMS" | N/A |  |
| Abstract | service metadata^2^ | description | OGC API - Common - Part 1
| OnlineResource | landing page | links | OGC API - Common - Part 1
| Keywords | service metadata^2^ | x-keywords | OGC API - Common - Part 1, Annex B.4
| LayerLimit | service metadata^2^ | x-OGC-limits.maps.maxCollections | This standard
| MaxWidth

MaxHeight | service metadata | x-OGC-limits.maps.maxWidth

x-OGC-limits.maps.maxHeight

x-OGC-limits.maps.maxPixels ^1^ | This standard <<rc_scaling>>
| Fees | N/A |   |
| AccessConstraints | N/A |   |
4+|
^1^ `x-OGC-limits.maps.maxWidth`, `x-OGC-limits.maps.maxHeight` and `x-OGC-limits.maps.maxPixels` are intended to control the work load of the server by providing limitations in size of the outputs of the subset. `width` and `height` parameters in _OGC API - Maps_ (defined in <<rc_scaling>>) control the size of the response and its resolution. The core of OGC API - Maps does not provide explicit limits on the size and resolution, but the server is free to respond with an error to avoid work overload. `width` and `height` parameters are commonly related to the size of the device screen. The fact that new devices are being built with more and more available display pixels. As such, specifying a reasonable limit on the server side based on today's technology may become too restrictive for future devices.
^2^ service metadata may be provided as an extension of the `info` section of the Open API document as indicated in OGC API - Common - Part 1, Annex B.4 
|===

The following table provides a reference to where some of layer metadata aspects are specified.

[#where-layer-metadata-is,reftext='{table-caption} {counter:table-num}']
.Where some "layer" metadata elements are specified
[width = "100%",options="header"]
|===
| Name in WMS 1.3 <Layer> | Where in the API | property | Specified in
| Title | collection response | title | OGC API - Common - Part 2
| Name | collection response | id | OGC API - Common - Part 2
| Abstract | collection response | description | OGC API - Common - Part 2
| Keywords | collection response | keywords | OGC API - Records (Local Resources Catalogue)
| Style | style response | id | OGC API - Styles - Part 1
| EX_GeographicBoundingBox | collections response | extent.spatial.bbox | OGC API - Common - Part 2
| CRS | collection response | storageCrs | This standard
| BoundingBox | collection response | extent.spatial.storageCrsBbox^1^ | This standard
| minScaleDenominator

maxScaleDenominator | collection response | minScaleDenominator

maxScaleDenominator | Possibly in OGC API - Common - Part 2
| Sample Dimensions | collection response | extent ^2^ | This standard
| MetadataURL | collection response | link with rel describedBy | OGC API Common - Part 2
| Attribution | collection response | attribution | OGC API - Common - Part 2
| Identifier

AuthorityURL | collection response | externalIds | OGC API - Records (Local Resources Catalogue)
| FeatureListURL | items response |  | OGC API - Features provides this capability
| DataURL  |  |  | OGC API - Features, Coverages and EDR provide download capabilities
| queryable ^3^  |  |  | OGC API - Features, Coverages and EDR provide query capabilities
| cascaded ^4^

noSubsets ^5^

fixedWidth ^6^

fixedHeight ^7^ | N/A | |
4+| ^1^ In WMS it was possible to specify one bounding box for each supported output CRS. In OGC API - Maps, it is only provided for the native CRS (storageCrs).

^2^ If extra dimensions are supported the range of values are defined in additional properties of the 'extent' of the collection.

^3^ No equivalent functionality to GetFeatureInfo is provided so this flag is not applicable to OGC API - Maps. Please use the query capabilities of other OGC API Standards instead.

^4^ The `cascaded` XML attribute in WMS is removed because no practical use has been seen. `cascaded` indicated if a map was generated by the addressed service or by another service assisting the first one.

^5^ The `noSubsets` XML attribute in WMS was used to indicate lack of subsetting support. The client will know if the server does not support the _spatial subsetting_, _date and time_ (for temporal subsetting) or _general subsetting_ conformance class by inspecting its conformance declaration.

^6^ The `fixedWidth` XML attribute in WMS was used to indicate lack of scaling support. The client will know if the server does not support the _scaling_ conformance class by inspecting its conformance declaration.

^7^ The `fixedHeight` XML attribute in WMS was used to indicate lack of scaling support. The client will know if the server does not support the _scaling_ conformance class by inspecting its conformance declaration.

|===

NOTE: The supported formats for map resources, or more precisely the media types of the supported encodings, can also be determined from the API definition. The desired encoding is selected using HTTP content negotiation. In addition to the parameters specified by the core, other parameters should be added.


NOTE: The `opaque` XML attribute in WMS was rarely useful and has been removed. This attribute indicated whether the map data represents features that probably do not completely fill space and shows the background opaque (true) or transparent (false).

==== No equivalent to _GetFeatureInfo_ as part of the OGC API - Maps - Part 1
The OGC Web Map Service _GetFeatureInfo_ operation provides the capability for clients to implement some simple level of user interaction with the map. In essence the user can focus on a point on the map (e.g., by clicking on it) and the client will request from the server some textual information related to the elements represented at that point of the map (a functionality sometimes called "query by location"). If the elements represented in the map are simple features, the result should be related to their properties (attributes). If the map represents a coverage, the result should report the value of the coverage in that position (eventually, if the coverage is multidimensional, it could be a e.g., time series graphic or a vertical profile). The format of the actual response is left to the discretion of the server.

_GetFeatureInfo_ was first proposed in the 2000 version of the OGC Web Map Service Standard. In that environment _GetFeatureInfo_ provided an easy to implement solution for the first step to "queryable" maps. 

The new OGC API Standards emerged in a completely different context where most web content is dynamic and JavaScript is now a powerful programming language for the Web. Most simplistic implementations of WMS _GetFeatureInfo_ resulted in an imperfect presentation of the attribute text. Users demand much more than query by location. Now, the integration of the different building blocks defined in OGC API Standards can be provided by default. A map is connected to a collection (or a dataset) that is probably also offered as features with _OGC API - Features_ or as coverage with _OGC API - Coverages_ -- all from the same API landing page. Furthermore, _OGC API - Environmental Data Retrieval (EDR)_ also provides a point query, similar to _GetFeatureInfo_ as well as much more advanced queries by polygons, trajectories or corridors.

Implementers of map clients are encouraged to implement support for OGC API Standards in addition to _OGC API - Maps_ to provide a functionality similar to _GetFeatureInfo_. Instead of building a request to a map point in map coordinates (I, J), implementers should use point narrow bounding boxes in CRS coordinates. For example:

  * In _OGC API - Features_, map coordinates should be transformed to Lon,Lat WGS84 in the client side and implement an HTTP GET request to `/collections/{collectionId}/items?bbox=Lon,Lat,Lon,Lat`.
  * In _OGC API - Coverages_, map coordinates should be transformed to native coordinates and use `/collections/{collectionId}/coverage?bbox=x,y,x,y` or the equivalent "subset" query.
  * In _OGC API - EDR_, map coordinates should be transformed to a CRS that the API supports `/collections/{collectionId}/position?coords=POINT(x y)` or by adding a radius query `/collections/{collectionId}/radius?coords=POINT(x y)&within=20&within-units=km`.

The use of _OGC API - Tiles_ and serving vector tiled content directly also makes creating visualizations with query capabilities directly on the client side possible. Since tiled vector data can contain features, their attributes can be presented to the user when clicked, and a different style can be applied to highlight that selected feature.

NOTE: Even if the _OGC API - Maps - Part 1_ does not provide a direct _GetFeatureInfo_ equivalent, there is a strong tradition of _GetFeatureInfo_ implementations that suggests a possible _OGC API - Maps_ Standard future "part" could reintroduce a _GetFeatureInfo_ equivalent - if users and implementers demand this capability.

NOTE: The second most commonly expected function, querying or filtering by the attributes of the features shown in the map, was never introduced in WMS. The same _OGC API - Maps_ future "part" could provide the ability to filter by attributes using a CQL2 expression.
