[appendix]
:appendix-caption: Annex
[[annex-ats]]
== Conformance Class Abstract Test Suite (Normative)

=== Conformance Class "Core"


[[conf_core,/conf/core]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core
classification:: Target Type:Web API
abstract-test:: /conf/core/map-op
abstract-test:: /conf/core/map-response
abstract-test:: /conf/core/conformance-success
====

==== Abstract Test for Requirement Map Operation


[[conf_core_map-op,/conf/core/map-op]]
[abstract_test]
====
[%metadata]
identifier:: /conf/core/map-op
target:: /req/core/map-op
test-purpose:: Verify that the implementation supports the map retrieval operation
test-method::
+
--
*Given:* a geospatial data resource conforming to the Maps API Standard, with an API path including `.../map...` or discovered following a link with relation type `[ogc-rel:map]` +
*When:* performing a GET operation on the `/map` resource with a supported media type specified in the `Accept:` header (e.g., `Accept: image/png,image/jpeg`) +
*Then:* +
- assert that the response has HTTP status code 200 +
- assert that the CRS of the resulting map is the native CRS (the native CRS is `[ogc:crs84]`, unless specified in the dataset map or collection map description `storageCrs` property, or specified out-of-band if _OGC API - Common_ is not implemented), +
- assert that the response headers either includes a `Content-Crs:` header for the native CRS, or omits it if the nativeCRS is `[ogc:crs84]`, +
- assert that the headers of the response include a `Content-Bbox:` header with the actual axis-aligned geospatial boundary of the rendered map, +
- assert that the `Content-Bbox:` coordinates are in the native CRS and honor the CRS coordinates order, +
- assert that the body of the response is a map of the geospatial data resource in the negotiated format.
--
====


==== Abstract Test for Requirement Map Response


[abstract_test]
====
[%metadata]
identifier:: /conf/core/map-response
target:: /req/core/map-response
test-purpose:: Verify that the implementation's response for the map retrieval operation is correct
test-method::
+
--
*Given:* a map resource that was successfully retrieved for <<conf_core_map-op>> +
*When:* retrieving that resource for the map operation +
*Then:* +
- assert that the response has an HTTP status code 200, +
- assert that the map response is in the storage CRS specified in the collection description, or https://www.opengis.net/def/crs/OGC/1.3/CRS84 if none is specified, +
- assert that the headers of the response include the "Content-Crs" header with the URI or the safe CURIEs of the CRS used to render the map, except if the content is in the https://www.opengis.net/def/crs/OGC/1.3/CRS84 CRS, +
- assert that the headers of the response include a "Content-Bbox" header with the actual geospatial boundary of the rendered map, +
- assert that the "Content-Bbox" coordinates are in the response CRS (indicated in the "Content-Crs" or https://www.opengis.net/def/crs/OGC/1.3/CRS84 if it is not present) and contains four comma-separated numbers representing the lower-left and upper-right corners of the response honoring the CRS coordinates order, +
- assert that if the geospatial resource has a temporal aspect (e.g., if a temporal extent is defined in the collection description or in the dataset landing page), the headers of the response include a "Content-Datetime" header with the actual datetime instant or datetime interval of the rendered map expressed in RFC 3339, section 5.6 format (using either UTC time or local time offsets), +
- assert that the body of the response contains a map encoded in the negotiated format.
--
====

==== Abstract Test for Requirement Map Conformance Success


[abstract_test]
====
[%metadata]
identifier:: /conf/core/conformance-success
target:: /req/core/conformance-success
test-purpose:: For implementations having a mechanism to advertise conformance classes, verify that it reports conformance to this Standard correctly.
test-method::
+
--
*Given:* a conformance resource in a recognized format, such as the OGC API JSON `/conformance` resource +
*When:* retrieving that resource from the API endpoint +
*Then:* +
- assert that the list of conformance classes that are supported by this API implementation instance includes at minimum https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core.
This list of conformance classes can also be used to select which other abstract tests to perform as listed in the <<table_conformance_urls>> and indicated in the tests preconditions.
--
====

=== Conformance Class "Map Tilesets"

[[conf_tilesets,/conf/tilesets]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/tilesets
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/tilesets
classification:: Target Type:Web API
abstract-test:: /conf/tilesets/desc-links
abstract-test:: /conf/tilesets/tiles-parameters
====

==== Abstract Test for Requirement desc-links


[abstract_test]
====
[%metadata]
identifier:: /conf/tilesets/desc-links
target:: /req/tilesets/desc-links
test-purpose:: Verify that the implementation supports map tilesets
test-method::
+
--
*Given:* a geospatial data resource conforming to this Standard, to "Map Tilesets", to OGC _API - Tiles_ and providing a description resource including links +
*When:* retrieving the geospatial data resource description +
*Then:* +
- assert that the geospatial data resource (e.g., collection or landing page description's `links` property) includes a link with the `href` pointing to a tileset list supported that presents a tile aspect of this geospatial data resource and with rel: `[ogc-rel:tilesets-map]`
--
====

==== Abstract Test for Requirement tiles-parameters


[abstract_test]
====
[%metadata]
identifier:: /conf/tilesets/tiles-parameters
target:: /req/tilesets/tiles-parameters
test-purpose:: Verify that the implementation supports relevant parameters for map tilesets
test-method::
+
--
*Given:* a geospatial data resource conforming to this Standard, to "Map Tilesets", to OGC _API - Tiles_, and to _Maps_ requirements classes introducing parameters relevant for map tiles  +
*When:* retrieving the map tiles with parameters for the _background_, _display resolution_, _spatial subsetting_ (only for `subset` and `subset-crs` parameters, and only if a vertical dimension is available), _general subsetting_, and _scaling_ requirements classes +
*Then:* +
- assert that tiles responses reflect the relevant map parameters used for the requests
--
====

NOTE: This conformance class depends on _OGC API - Tiles - Part 1: Core_ "Tilesets List" conformance class to which the implementation must also conform.

=== Conformance Class "Background"

[[conf_background,/conf/background]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/background
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/background
classification:: Target Type:Web API
abstract-test:: /conf/background/bgcolor-definition
abstract-test:: /conf/background/transparent-definition
abstract-test:: /conf/background/void-bgcolor-definition
abstract-test:: /conf/background/void-transparent-definition
abstract-test:: /conf/background/map-success
====

==== Abstract Test for Requirement `bgcolor` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/background/bgcolor-definition
target:: /req/background/bgcolor-definition
test-purpose:: Verify that the implementation supports the `bgcolor` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a map without `bgcolor` parameter, with `bgcolor` using a hexadecimal value and with `bgcolor` using a W3C Web Color name +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement `transparent` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/background/transparent-definition
target:: /req/background/transparent-definition
test-purpose:: Verify that the implementation supports the `transparent` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a map for all combinations of (no `transparent` parameter, transparent=false`, `transparent=true`) and with and without `bgcolor` parameter +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement `void-bgcolor` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/background/void-bgcolor-definition
target:: /req/background/void-bgcolor-definition
test-purpose:: Verify that the implementation supports the `void-bgcolor` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a map without `void-bgcolor` parameter, with `void-bgcolor` using a hexadecimal value and with `void-bgcolor` using a W3C Web Color name +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement `void-transparent` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/background/void-transparent-definition
target:: /req/background/void-transparent-definition
test-purpose:: Verify that the implementation supports the `void-transparent` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a map for all combinations of (no `void-transparent` parameter, void-transparent=false`, `void-transparent=true`) and with and without `void-bgcolor` parameter +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement Background Map Success


[abstract_test]
====
[%metadata]
identifier:: /conf/background/map-success
target:: /req/background/map-success
test-purpose:: Verify that the implementation's response for the map retrieval operation with a background color and/or transparent parameter is correct
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* for all combinations of (no `transparent` parameter, transparent=false`, `transparent=true`) and (without `bgcolor` parameter, with `bgcolor` using a hexadecimal value and with `bgcolor` using a W3C Web Color name) +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "Collection Selection"

[[conf_collections-selection,/conf/collections-selection]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collections-selection
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/collections-selection
classification:: Target Type:Web API
abstract-test:: /conf/collections-selection/collections-parameter
abstract-test:: /conf/collections-selection/collections-response
====

==== Abstract Test for Requirement `collections` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/collections-selection/collections-parameter
target:: /req/collections-selection/collections-parameter
test-purpose:: Verify that the implementation supports the `collections` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core and that is understood to consist of multiple collections (e.g., a dataset advertising support for Dataset Map and featuring multiple collections) +
*When:* retrieving a map using the `collections` parameter with one and multiple _collectionsIds_ +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement Collection Selection Response


[abstract_test]
====
[%metadata]
identifier:: /conf/collections-selection/collections-response
target:: /req/collections-selection/collections-response
test-purpose:: Verify that the implementation responds correctly to map requests using the `collections` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core and that is understood to consist of multiple collections (e.g., a dataset advertising support for Dataset Map and featuring multiple collections) +
*When:* retrieving a map using the `collections` parameter with one and multiple _collectionsIds_ +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "Scaling"

[[conf_scaling,/conf/scaling]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/scaling
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/scaling
classification:: Target Type:Web API
abstract-test:: /conf/scaling/width-definition
abstract-test:: /conf/scaling/height-definition
abstract-test:: /conf/scaling/scale-denominator-definition
====

==== Abstract Test for Requirement `width` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/scaling/width-definition
target:: /req/scaling/width-definition
test-purpose:: Verify that the implementation supports the (scaling) `width` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using `width` parameter for different values, as well as the same `bbox` parameter if spatial subsetting is supported, with and without `height` parameter, with and without `mm-per-pixel` parameter if display resolution is supported +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement `height` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/scaling/height-definition
target:: /req/scaling/height-definition
test-purpose:: Verify that the implementation supports responds the (scaling) `height` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using `height` parameter for different values, as well as the same `bbox` parameter if spatial subsetting is supported, with and without `width` parameter, with and without `mm-per-pixel` parameter if display resolution is supported +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement `scale-denominator` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/scaling/scale-denominator-definition
target:: /req/scaling/scale-denominator-definition
test-purpose:: Verify that the implementation supports the `scale-denominator` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `scale-denominator` parameter, combining all possibilities of with and without `width` and/or `height` parameters, with and without `bbox` and `center` parameter if spatial subsetting is supported, with and without `mm-per-pixel` parameter if display resolution is supported +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "Display Resolution"

[[conf_display-resolution,/conf/display-resolution]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/display-resolution
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/display-resolution
classification:: Target Type:Web API
abstract-test:: /conf/display-resolution/mm-per-pixel-definition
abstract-test:: /conf/display-resolution/map-success
====

==== Abstract Test for Requirement `mm-per-pixel` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/display-resolution/mm-per-pixel-definition
target:: /req/display-resolution/mm-per-pixel-definition
test-purpose:: Verify that the implementation supports the `mm-per-pixel` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `mm-per-pixel` parameter, for different styles if styled maps are supported, combining all possibilities of with and without `width` and/or `height` parameters, with and without `bbox` and `center` parameter if spatial subsetting is supported, with and without `mm-per-pixel` parameter if display resolution is supported +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement Display Resolution Map Success


[abstract_test]
====
[%metadata]
identifier:: /conf/display-resolution/map-success
target:: /req/display-resolution/map-success
test-purpose:: Verify that the implementation responds correctly to map requests using the `mm-per-pixel` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `mm-per-pixel` parameter, for different styles if styled maps are supported, combining all possibilities of with and without `width` and/or `height` parameters, with and without `bbox` and `center` parameter if spatial subsetting is supported, with and without `mm-per-pixel` parameter if display resolution is supported +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "Spatial Subsetting"

[[conf_spatial-subsetting,/conf/spatial-subsetting]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/spatial-subsetting
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/spatial-subsetting
classification:: Target Type:Web API
abstract-test:: /conf/spatial-subsetting/bbox-crs
abstract-test:: /conf/spatial-subsetting/subset-crs
abstract-test:: /conf/spatial-subsetting/center-crs
abstract-test:: /conf/spatial-subsetting/bbox-definition
abstract-test:: /conf/spatial-subsetting/subset-definition
abstract-test:: /conf/spatial-subsetting/subset-response
abstract-test:: /conf/spatial-subsetting/center-definition
abstract-test:: /conf/spatial-subsetting/width-height
abstract-test:: /conf/spatial-subsetting/map-success
====

==== Abstract Test for Requirement `bbox-crs` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/bbox-crs
target:: /req/spatial-subsetting/bbox-crs
test-purpose:: Verify that the implementation supports the `bbox-crs` parameter for specifying the CRS of the `bbox` parameter correctly
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using `bbox` and `bbox-crs` parameter for different values, as well as different values for the `crs` parameter if supported and applicable, +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement `subset-crs` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/subset-crs
target:: /req/spatial-subsetting/subset-crs
test-purpose:: Verify that the implementation supports the `subset-crs` parameter for specifying the CRS of the `subset` parameter correctly
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using `subset` and `subset-crs` parameter for different values (using the correct spatial axes), as well as different values for the `crs` parameter if supported and applicable, +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement `center-crs` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/center-crs
target:: /req/spatial-subsetting/center-crs
test-purpose:: Verify that the implementation supports the `center-crs` parameter for specifying the CRS of the `center` parameter correctly
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using `center` and `center-crs` parameter for different values, as well as different values for the `crs` parameter if supported and applicable, +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement `bbox` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/bbox-definition
target:: /req/spatial-subsetting/bbox-definition
test-purpose:: Verify that the implementation supports the `bbox` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `bbox` parameter (with and without the `bbox-crs` parameter), +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement spatial subsetting `subset` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/subset-definition
target:: /req/spatial-subsetting/subset-definition
test-purpose:: Verify that the implementation supports the `subset` parameter for spatial subsetting
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `subset` parameter (with and without the `subset-crs` parameter, for the correct spatial axes), +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement map subset response


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/subset-response
target:: /req/spatial-subsetting/subset-response
test-purpose:: Verify that the implementation responds correctly to map requests using the `subset` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `subset` (with and without the `subset-crs` parameter) +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement `center` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/center-definition
target:: /req/spatial-subsetting/center-definition
test-purpose:: Verify that the implementation supports the `center` parameter correctly
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `center` parameter (with and without the `center-crs` parameter), +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement subsetting `width` and `height` parameters definition


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/width-height
target:: /req/spatial-subsetting/width-height
test-purpose:: Verify that the implementation supports the `width` and `height` parameter for spatial subsetting when used together with the `center` and/or the `scale-denominator` parameters
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `center` parameter together, with the `width` and/or `height` (with and without the `center-crs` parameter), with and without the `scale-denominator` parameter if scaling is supported +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement map subset success


[abstract_test]
====
[%metadata]
identifier:: /conf/spatial-subsetting/map-success
target:: /req/spatial-subsetting/map-success
test-purpose:: Verify that the implementation responds correctly to map requests using subsetting parameters (`bbox`, `subset` or `center`)
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `bbox` (with and without the `bbox-crs` parameter), `subset` (with and without the `subset-crs` parameter), and `center` parameter (with and without the `center-crs` parameter, with the `width` and/or `height` parameter, with and without the `scale-denominator` parameter if scaling is supported +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "Date and Time"

[[conf_datetime,/conf/datetime]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/datetime
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/datetime
classification:: Target Type:Web API
abstract-test:: /conf/datetime/datetime-definition
abstract-test:: /conf/datetime/datetime-response
abstract-test:: /conf/datetime/subset-definition
abstract-test:: /conf/datetime/subset-response
abstract-test:: /conf/datetime/axis
abstract-test:: /conf/datetime/map-success
====

==== Abstract Test for Requirement `datetime` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/datetime/datetime-definition
target:: /req/datetime/datetime-definition
test-purpose:: Verify that the implementation supports the `datetime` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `datetime` parameter +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement `datetime` parameter response


[abstract_test]
====
[%metadata]
identifier:: /conf/datetime/datetime-response
target:: /req/datetime/datetime-response
test-purpose:: Verify that the implementation responds correctly to map requests using the `datetime` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `datetime` parameter +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement temporal `subset` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/datetime/subset-definition
target:: /req/datetime/subset-definition
test-purpose:: Verify that the implementation supports temporal subsetting using the `subset` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `subset` parameter with the `time` axis +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement temporal subset response


[abstract_test]
====
[%metadata]
identifier:: /conf/datetime/subset-response
target:: /req/datetime/subset-response
test-purpose:: Verify that the implementation responds correctly to temporal subsetting requests using the `subset` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `subset` parameter with the `time` axis +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement temporal axis


[abstract_test]
====
[%metadata]
identifier:: /conf/datetime/axis
target:: /req/datetime/axis
test-purpose:: Verify that the implementation supports the `time` axis for temporal subsetting using the `subset` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `subset` parameter with the `time` axis +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement temporal subsetting success


[abstract_test]
====
[%metadata]
identifier:: /conf/datetime/map-success
target:: /req/datetime/map-success
test-purpose:: Verify that the implementation responds correctly to temporal subsetting requests
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `subset` parameter with the `time` axis +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "General Subsetting"

[[conf_general-subsetting,/conf/general-subsetting]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/general-subsetting
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/general-subsetting
classification:: Target Type:Web API
abstract-test:: /conf/general-subsetting/uniform-additional-dimensions
abstract-test:: /conf/general-subsetting/subset-definition
====

==== Abstract Test for Requirement uniform additional dimensions


[abstract_test]
====
[%metadata]
identifier:: /conf/general-subsetting/uniform-additional-dimensions
target:: /req/general-subsetting/uniform-additional-dimensions
test-purpose:: Verify that the implementation describes the extent of all additional dimensions of the data resource using the uniform additional dimension schema (using `interval`, `crs/trs/vrs` and optionally `grid`).
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core for which an extent description is available +
*When:* retrieving the description of the data resource +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement general subsetting `subset` parameter


[abstract_test]
====
[%metadata]
identifier:: /conf/general-subsetting/subset-definition
target:: /req/general-subsetting/subset-definition
test-purpose:: Verify that the implementation supports general subsetting using the `subset` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps using the `subset` parameter for an additional dimension besides space and time +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "Coordinate Reference System"

[[conf_crs,/conf/crs]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/crs
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/crs
classification:: Target Type:Web API
abstract-test:: /conf/crs/crs-definition
abstract-test:: /conf/crs/map-success
====

==== Abstract Test for Requirement `crs` parameter definition


[abstract_test]
====
[%metadata]
identifier:: /conf/crs/crs-definition
target:: /req/crs/crs-definition
test-purpose:: Verify that the implementation supports the output `crs` parameter for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps with the `crs` parameter for different available CRS and without +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====


==== Abstract Test for Requirement CRS map success


[abstract_test]
====
[%metadata]
identifier:: /conf/crs/map-success
target:: /req/crs/map-success
test-purpose:: Verify that the implementation responds correctly to map requests using the `crs` parameter
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps with the `crs` parameter for different available CRS and without +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "Orientation"

[[conf_orientation,/conf/orientation]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/orientation
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/req/orientation
classification:: Target Type:Web API
abstract-test:: /conf/orientation/orientation
abstract-test:: /conf/orientation/response-headers
====

==== Abstract Test for Requirement `orientation` parameter


[abstract_test]
====
[%metadata]
identifier:: /conf/orientation/orientation
target:: /req/orientation/orientation
test-purpose:: Verify that the implementation supports the `orientation` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps with the `orientation` parameter for different values and without +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement orientation response headers


[abstract_test]
====
[%metadata]
identifier:: /conf/orientation/response-headers
target:: /req/orientation/response-headers
test-purpose:: Verify that the implementation includes the correct response headers for map requests using the `orientation` parameter.
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving maps with the `orientation` parameter for different values and without +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "Custom Projection CRS"

[[conf_projection,/conf/projection]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/projection
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/projection
classification:: Target Type:Web API
abstract-test:: /conf/projection/crs-proj-method
abstract-test:: /conf/projection/crs-proj-params
abstract-test:: /conf/projection/crs-proj-center-definition
abstract-test:: /conf/projection/crs-datum
abstract-test:: /conf/projection/response-headers
abstract-test:: /conf/projection/projections-resource
abstract-test:: /conf/projection/projections-response
====

==== Abstract Test for Requirement `crs-proj-method` parameter


[abstract_test]
====
[%metadata]
identifier:: /conf/projection/crs-proj-method
target:: /req/projection/crs-proj-method
test-purpose:: Verify that the implementation supports the `crs-proj-method` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to <<conf_core>> and passing <<conf_projection_projections-response>> +
*When:* retrieving maps with the `crs-proj-method` parameter for different available values as listed in `/projectionsAndDatums` +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement `crs-proj-params` parameter


[abstract_test]
====
[%metadata]
identifier:: /conf/projection/crs-proj-params
target:: /req/projection/crs-proj-params
test-purpose:: Verify that the implementation supports the `crs-proj-params` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to <<conf_core>> and passing <<conf_projection_projections-response>> +
*When:* retrieving maps with the `crs-proj-method` parameter for different available values and different values of the associated method parameters (specified using the `crs-proj-params` query parameter) as listed in `/projectionsAndDatums` +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement  `crs-proj-center` parameter


[abstract_test]
====
[%metadata]
identifier:: /conf/projection/crs-proj-center-definition
target:: /req/projection/crs-proj-center-definition
test-purpose:: Verify that the implementation supports the `crs-proj-center` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to <<conf_core>> and passing <<conf_projection_projections-response>> +
*When:* retrieving maps with the `crs-proj-method` parameter for different available values as listed in `/projectionsAndDatums` and the `crs-proj-center` parameter for different values +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement `crs-datum` parameter


[abstract_test]
====
[%metadata]
identifier:: /conf/projection/crs-datum
target:: /req/projection/crs-datum
test-purpose:: Verify that the implementation supports the `crs-datum` parameter correctly for map requests
test-method::
+
--
*Given:* a map resource that conformed successfully to <<conf_core>> and passing <<conf_projection_projections-response>> +
*When:* retrieving maps with the `crs-datum` parameter for different available values as listed in `/projectionsAndDatums` +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement custom CRS projection response headers


[abstract_test]
====
[%metadata]
identifier:: /conf/projection/response-headers
target:: /req/projection/response-headers
test-purpose::  Verify that the implementation responds to map requests using the `crs-proj-method` parameter and/or `crs-datum` with the correct response headers
test-method::
+
--
*Given:* a map resource that conformed successfully to <<conf_core>> and passing <<conf_projection_projections-response>> +
*When:* retrieving maps with the `crs-proj-method` parameter for different available values, different values of the associated method parameters (using both `crs-proj-center` and `crs-proj-params`), and different values for `crs-datum` as listed in `/projectionsAndDatums` +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement `/projectionsAndDatums` resource


[[conf_projection_projections-resource,/conf/projection/projections-resource]]
[abstract_test]
====
[%metadata]
identifier:: /conf/projection/projections-resource
target:: /req/projection/projections-resource
test-purpose:: Verify that the implementation supports retrieving the list of available projection operation methods, their parameters, and the list of available datums at `/projectionsAndDatums`
test-method::
+
--
*Given:* an API implementation being tested +
*When:* retrieving the `/projectionsAndDatums` resource +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement `/projectionsAndDatums` response

[[conf_projection_projections-response,/conf/projection/projections-response]]
[abstract_test]
====
[%metadata]
identifier:: /conf/projection/projections-response
target:: /req/projection/projections-response
test-purpose:: Verify that the implementation responds correctly to a request for the `/projectionsAndDatums` resource, conforming to the JSON schema and using the correct URIs
test-method::
+
--
*Given:* an API implementation being tested passing <<conf_projection_projections-resource>>  +
*When:* retrieving the `/projectionsAndDatums resource` +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "Collection Map"

[[conf_collection-map,/conf/collection-map]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collection-map
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/collection-map
classification:: Target Type:Web API
abstract-test:: /conf/collection-map/desc-links
abstract-test:: /conf/collection-map/desc-crs
abstract-test:: /conf/collection-map/map-operation
====

==== Abstract Test for Requirement collection description links


[abstract_test]
====
[%metadata]
identifier:: /conf/collection-map/desc-links
target:: /req/collection-map/desc-links
test-purpose:: Verify that the implementation links correctly from the collection description resource to the map resource
test-method::
+
--
*Given:* a collection from an API implementation conforming to OGC API - Common - Part 2: Geospatial Data "Collections" conformance class +
*When:* retrieving the JSON representation of the description for that collection +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement collection description CRS


[abstract_test]
====
[%metadata]
identifier:: /conf/collection-map/desc-crs
target:: /req/collection-map/desc-crs
test-purpose:: Verify that the implementation describes the supported CRS correctly in its collection description resources
test-method::
+
--
*Given:* an API implementation conforming to OGC API - Common - Part 2: Geospatial Data "Collections" conformance class +
*When:* retrieving the JSON representation of the description for that collection +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement collection map operation


[abstract_test]
====
[%metadata]
identifier:: /conf/collection-map/map-operation
target:: /req/collection-map/map-operation
test-purpose:: Verify that the implementation supports retrieving maps from an OGC API a collection as defined in the OGC API – Common Standard.
test-method::
+
--
*Given:* a collection correctly linking to a map resource as per /conf/collection-map/desc-links +
*When:* retrieving a map for that collection resource as per /conf/core +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "Dataset Map"

[[conf_dataset-map,/conf/dataset-map]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/dataset-map
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/dataset-map
classification:: Target Type:Web API
abstract-test:: /conf/dataset-map/landingpage
abstract-test:: /conf/dataset-map/desc-extent
abstract-test:: /conf/dataset-map/desc-crs
abstract-test:: /conf/dataset-map/operation
====

==== Abstract Test for Requirement dataset landing page


[abstract_test]
====
[%metadata]
identifier:: /conf/dataset-map/landingpage
target:: /req/dataset-map/landingpage
test-purpose:: Verify that the implementation supports linking properly from an OGC API landing page to a map resource
test-method::
+
--
*Given:* a dataset provided by an API implementation conforming to OGC API - Common - Part 1: Core +
*When:* retrieving the JSON representation of the landing page description for that dataset +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement dataset description extent


[abstract_test]
====
[%metadata]
identifier:: /conf/dataset-map/desc-extent
target:: /req/dataset-map/desc-extent
test-purpose:: Verify that the implementation describes the extent of the dataset correctly from the landing page
test-method::
+
--
*Given:* a dataset provided by an API conforming to OGC API - Common - Part 1: Core +
*When:* retrieving the JSON representation of the landing page description for that dataset +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement dataset description CRS


[abstract_test]
====
[%metadata]
identifier:: /conf/dataset-map/desc-crs
target:: /req/dataset-map/desc-crs
test-purpose:: Verify that the implementation describes the supported CRS correctly in its landing page resource
test-method::
+
--
*Given:* a dataset provided by an API conforming to OGC API - Common - Part 1: Core +
*When:* retrieving the JSON representation of the landing page description for that dataset +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement dataset map operation


[abstract_test]
====
[%metadata]
identifier:: /conf/dataset-map/operation
target:: /req/dataset-map/operation
test-purpose:: Verify that the implementation supports retrieving dataset maps a resource exposed by the OGC Maps API implementation
test-method::
+
--
*Given:* an OGC API dataset correctly linking to a map resource as per /conf/dataset-map/landingpage +
*When:* retrieving a map for that dataset resource as per /conf/core +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "Styled Map"

[[conf_styled-map,/conf/styled-map]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/styled-map
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/styled-map
classification:: Target Type:Web API
abstract-test:: /conf/styled-map/desc-links
abstract-test:: /conf/styled-map/map-operation
====

==== Abstract Test for Requirement styled map links


[abstract_test]
====
[%metadata]
identifier:: /conf/styled-map/desc-links
target:: /req/styled-map/desc-links
test-purpose:: Verify that the implementation links correctly from a style resource to a map resource
test-method::
+
--
*Given:* a list of styles provided by an API implementation conforming to OGC API - Styles - Part 1: Core +
*When:* retrieving the JSON representation of that list of styles +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement styled map operation


[abstract_test]
====
[%metadata]
identifier:: /conf/styled-map/map-operation
target:: /req/styled-map/map-operation
test-purpose:: Verify that the implementation supports retrieving maps from _OGC API - Styles_ style resources
test-method::
+
--
*Given:* a style correctly linking to a map resource as per /conf/styled-map/desc-links +
*When:* retrieving a map for that style as per /conf/core +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "PNG"

[[conf_png,/conf/png]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/png
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/png
classification:: Target Type:Web API
abstract-test:: /conf/png/content
====

==== Abstract Test for Requirement PNG map content


[abstract_test]
====
[%metadata]
identifier:: /conf/png/content
target:: /req/png/content
test-purpose:: Verify that the implementation supports retrieving maps negotiating for PNG content
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a PNG (`image/png`) representation of a map resource through HTTP content negotiation +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "JPEG"

[[conf_jpeg,/conf/jpeg]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/jpeg
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/jpeg
classification:: Target Type:Web API
abstract-test:: /conf/jpeg/content
====

==== Abstract Test for Requirement JPEG map content


[abstract_test]
====
[%metadata]
identifier:: /conf/jpeg/content
target:: /req/jpeg/content
test-purpose:: Verify that the implementation supports retrieving maps negotiating for JPEG content
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a JPEG (`image/jpeg`) representation of a map resource through HTTP content negotiation +
**Then:** (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "JPEG XL"

[[conf_jpegxl,/conf/jpegxl]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/jpegxl
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/jpegxl
classification:: Target Type:Web API
abstract-test:: /conf/jpegxl/content
====

==== Abstract Test for Requirement JPEG XL map content


[abstract_test]
====
[%metadata]
identifier:: /conf/jpegxl/content
target:: /req/jpegxl/content
test-purpose:: Verify that the implementation supports retrieving maps negotiating for JPEG XL content
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a JPEG XL (`image/jxl`) representation of a map resource through HTTP content negotiation +
**Then:** (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "TIFF"

[[conf_tiff,/conf/tiff]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/tiff
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/tiff
classification:: Target Type:Web API
abstract-test:: /conf/tiff/content
====

==== Abstract Test for Requirement TIFF map content


[abstract_test]
====
[%metadata]
identifier:: /conf/tiff/content
target:: /req/tiff/content
test-purpose:: Verify that the implementation supports retrieving maps negotiating for TIFF and/or GeoTIFF content
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving a TIFF (`image/tiff`) and GeoTIFF (`image/tiff; application=geotiff`) representation of a map resource through HTTP content negotiation +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "SVG"

[[conf_svg,/conf/svg]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/svg
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/svg
classification:: Target Type:Web API
abstract-test:: /conf/svg/content
====

==== Abstract Test for Requirement SVG map content


[abstract_test]
====
[%metadata]
identifier:: /conf/svg/content
target:: /req/svg/content
test-purpose:: Verify that the implementation supports retrieving maps negotiating for SVG content
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving an SVG (`image/svg+xml`) representation of a map resource through HTTP content negotiation +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "HTML"

[[conf_html,/conf/html]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/html
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/html
classification:: Target Type:Web API
abstract-test:: /conf/html/content
====

==== Abstract Test for Requirement HTML map content


[abstract_test]
====
[%metadata]
identifier:: /conf/html/content
target:: /req/html/content
test-purpose:: Verify that the implementation supports retrieving maps negotiating for HTML content
test-method::
+
--
*Given:* a map resource that conformed successfully to /conf/core +
*When:* retrieving an (`text/html`) HTML representation of a map resource HTTP content negotiation +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "API Operations"

[[conf_api-operations,/conf/api-operations]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/api-operations
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/api-operations
classification:: Target Type:Web API
abstract-test:: /conf/api-operations/completeness
abstract-test:: /conf/api-operations/operation-id
====

==== Abstract Test for Requirement API Operations completeness


[abstract_test]
====
[%metadata]
identifier:: /conf/api-operations/completeness
target:: /req/api-operations/completeness
test-purpose:: Verify that the implementation completely and correctly describes the map resources
test-method::
+
--
*Given:* an API conforming to _OGC API - Common - Part 1: Core_ "Landing Page" conformance class +
*When:* retrieving the API description +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

==== Abstract Test for Requirement API Operation identifiers


[abstract_test]
====
[%metadata]
identifier:: /conf/api-operations/operation-id
target:: /req/api-operations/operation-id
test-purpose:: Verify that the implementation uses the correct API operation identifier suffixes to identify the resources defined in the Maps API Standard
test-method::
+
--
*Given:* an API implementation conforming to _OGC API - Common - Part 1: Core_ "Landing Page" conformance class supporting an API definition language with a concept of operation identifiers +
*When:* retrieving the API description +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====

=== Conformance Class "CORS"

[[conf_cors,/conf/cors]]
[conformance_class]
====
[%metadata]
identifier:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/cors
target:: https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/cors
classification:: Target Type:Web API
abstract-test:: /conf/cors/cors
====

==== Abstract Test for Requirement CORS


[abstract_test]
====
[%metadata]
identifier:: /conf/cors/cors
target:: /req/cors/cors
test-purpose:: Verify that the implementation completely and correctly implement CORS
test-method::
+
--
*Given:* an API conforming to _OGC API - Common - Part 1: Core_ "Landing Page" conformance class +
*When:* retrieving the API description +
*Then:* (assert that all parts of the requirement are fully satisfied)
--
====
