[[rc_decorations]]
== Requirement Class "Map Decorations"

=== Overview

[[background-overview]]

include::requirements/requirements_class_decorations.adoc[]

This requirement class describes parameters to add a title, a legend, a scale bar, a compass, a situation map, an attribution text or logo, a lat/long graticule, and a CRS grid to the map.

NOTE: The work "element" or "parts" normally designates the previous enumerations. However "element" is used in many other contexts so the authors decided to call the "decorations" in this section.

Many of these decorations can be better generated by the client that shows the map, so these parameters are reserved to create maps that are going to be used as static illustrations (e.g. as images in web pages). If the map is going to be presented alone as an illustration, these decorations could be make the map more informative and more "cartographic" (see for example https://reference.yourdictionary.com/resources/5-basic-parts-of-any-map.html). When a map is going to be presented overlaid with other maps these elements may interfere and collide, impeding the correct visualization or the result and are not recommended.

=== Map operation

The map core of this standard defines how to get a map. This requirements class specifies parameters to add some decorations on top of it

==== Parameters for map decorations
The title, legend, scale-bar, compass, situation-map, attribution, graticule and crs-grid,  parameters indicate if and where the decorations elements will be situated on top of the map.

include::requirements/decorations/REQ_title-definition.adoc[]

NOTE: The style and size of the text of the title is at complete discretion of the server

include::requirements/decorations/REQ_legend-definition.adoc[]

include::requirements/decorations/REQ_scale-bar-definition.adoc[]

include::requirements/decorations/REQ_compass-definition.adoc[]

NOTE: It is up to de server to decide how the compass can look like being some possibilities a full wind rose or a simple arrow to the north.

include::requirements/decorations/REQ_situation-map-definition.adoc[]

include::requirements/decorations/REQ_attribution-definition.adoc[]

NOTE: The attribution may be represented as a text naming the responsible party of the data represented in the map or a logo of the responsible party organzation.

REQ_include::requirements/decorations/graticule-definition.adoc[]

NOTE: A graticule is a network of lines on a map that delineate the geographic expressed as lines of equal latitude or longitude (a.k.a. meridians and parallels). A graticule added to a map in a lat/long CRS (such as CRS:84) will appear as a set of vertical and horizontal strait lines. In other CRSs, meridians a parallels may result in curbed lines.

include::requirements/decorations/REQ_crs-grid-definition.adoc[]

NOTE: A CRS grid is a network of lines on a map that delineate the CRS coordinates expressed as lines of equal X or Y. A CRS grid added results in a set of vertical and horizontal strait lines.

==== Response
A successful GET response is described in the core class (http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core)

include::requirements/decorations/REQ_map-success.adoc[]
