[[rs_spatial-subsetting]]
== Requirement Class "Maps spatial subsetting"

=== Overview

[[maps-spatial-partitioning-overview]]

include::requirements/requirements_class_spatial-partitioning.adoc[]

The core requirements class of this standard defines the map resource. The core also defines a minimum set of metadata to enable a client application to formulate a map request. This extension describes how to subset a map. Another way to subset a map is provided by <<rc_maps_tileSets-list>> that make a map accessible as tiles.

This class defines the extension to the core to formulate a subset using two mechanims, one similar to the WMS 1.3 BBOX and the other similar to the WCS 2.0 subset. The client will select between the `bbox` and the `subset` mechanism.

=== CRS for subsetting
In WMS 1.3 the CRS parametres had two missions: it indicated the CRS of the data rendered in the map and it was the CRS of the coordinates of the BBOX parameter. In this standards, this two mossions has been separated. In this section we will define the CRS parameters for subsetting.

The CRS advertised in the collection's spatial extent is always in CRS84 (for Earthly data and as required by OGC API Features). At least, for OGC API Maps and OGC API Coverages a native CRS (also called or storage CRS) is defined. The Content-Crs header (see <<maps-core-overview>>) specifies the CRS used in the response to avoid confussion.

NOTE: There is no obligation to provide the maps in CRS84.

NOTE: The collections description will contain a native or storage CRS. If it is not there then we will assume CRS84. The exact mechanims to do so will be defined by OGC API common.

NOTE: Provide the extent of the collection in native native CRS (also called or storage CRS) is recommended and the mechanims will be defined by OGC API common.

NOTE: A list of supported CRS's will be provided by the the collection. The first should be storage CRS. The mechanims to do so will be defined by OGC API common.

==== Parameter bbox-crs

include::requirements/subsetting/REQ_bbox-crs-definition.adoc[]

NOTE: For clarification: The default CRS of the BBOX is CRS84 and the default CRS of the map is native or storage CRS

==== Parameter subset-crs

include::requirements/subsetting/REQ_subset-crs-definition.adoc[]

NOTE: The `subset-crs` and `bbox-crs` are defined identically except they are afecting `subset` and `bbox` parameters respectively.

=== Subsetting coordinates

==== Parameter bbox
This parameter defines how to subset a map by bounding box (in the bbox-crs coordinates). The `bbox` parameter values are defined considering the exterior edges of the pixels of the viewport defined by the width and height. In other words, the relation of the Bounding Box to the map pixel matrix is that the bounding box goes around the "outside" of the pixels of the map rather than through the centers of the map's border pixels (as many times done in coverages). In this context, individual pixels represent a cell area on the ground.

include::requirements/subsetting/REQ_bbox-definition.adoc[]

NOTE: This parameter use the comma (",") as the separator between the coordinates. Additional white space will not be used to delimit list items. The comma character should not be escaped (IETF RFC 2396).

==== Parameters subset
The behavior of the subset parameter is imported from the OGC API - Common subset module. The entire module is reproduced here.
However, some considerations may not apply, and the generic behavior is limited by the CRS axis abbreviations.

include::api_modules/subset/requirements_module_subset.adoc[]

include::requirements/subsetting/REQ_subset-coordinates.adoc[]

include::recommendations/subsetting/REC_subset-crs-axis-names.adoc[]

=== Response

A successful response to a map GET operation will be consistent with the media type of resource requested.

include::requirements/subsetting/REQ_map-success.adoc[]

Normally, the content partially outside the map bounding box will be clipped at the extent of the bounding box. This can be done efficiently when map subsets are in raster format (e.g. map tiles). However, maps containing features in vector format may not clip features that are partially outside to ensure continuity of features or for performance.

include::recommendations/subsetting/REC_map-outside-bounds.adoc[]

include::recommendations/subsetting/PER_map-outside-bounds.adoc[]

NOTE: As defined in the core conformance class, the ogcapi-bbox and the content-crs reports the actual bounding box of the data returned.


=== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the CRS in the parameter value `bbox-crs` or `subset-crs` is not supported by the server for this resource, the parameter value is out-of-range, or the map is not provided due to lack of data in the area, the status code of the response will be `404`.
