[[rc_maps_tileSets-list]]
== Requirement Class "Map Tiles"

=== Overview

[[maps-tilesets-overview]]

include::requirements/requirements_class_tilesetslist.adoc[]
This document describes two main ways to subset maps. For example, subsetting can be used to implement zoom and pan in a web map browser. The combination of <<rc_scaling>> and <<rs_spatial-subsetting>> requirements classes provides a way to subset by an arbitrary bounding box (in a CRS). However, the approach will not benefit from cache mechanisms. Instead, a map can be retrieved as tiles in a predefined TileMatrixSet. This extension describes how to use OGC API maps in combination with OGC API tiles by making maps accessible as tiles.

NOTE: The concept of map tiles substitutes the WMTS 1.0 usage of tiles. WMTS was focused on map tiles (tiles that are rendered using a style).

=== Map
A map resource can be accessed as tiles if the API exposes a link to map tiles in the resource that is available as map tiles.

include::requirements/tilesets/REQ_desc-links.adoc[]

.Fragment of a collection description document with a links array with one item of the array pointing to a tileset.
=================
[source,JSON]

{
    "links": [
    ...
    {
      "href": "http://data.example.com/collections/buildings/map/tiles",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/tileset",
      "type": "application/json"
    }
  ]
}
=================

=== Map Tileset
A tileset contains the necessary metadata to enable a client application to formulate a tile request from a single geospatial data resource.

==== Operation

The tileset operation is described in the tileset class of the OGC API - Tiles

This standard does not specify the need for any additional query parameter in the GET request.

==== Response

A successful GET response is described in the tileset class of the OGC API - Tiles
