[[rc_background]]
== Requirements Class "Background"

=== Overview

[[background-overview]]

include::requirements/requirements_class_background.adoc[]

The Background requirement class describes how to define the background of the map is represented.

=== Map operation

The Maps API core requirements class defines how to get a map. The Map operation requirements class specifies parameters supporting customization of the background of the map.

==== Parameters `transparent` and `bgcolor`
The `transparent` and `bgcolor` parameters indicate how the absence of data will be represented in the map, what color will show underneath any non-opaque layer, and allow for the map to be overlaid with other maps without completely obscuring the lower layers.

include::requirements/background/REQ_bgcolor-definition.adoc[]

include::recommendations/background/REC_bgcolor-definition.adoc[]

The list of https://www.w3.org/wiki/CSS/Properties/color/keywords[W3C web color names] which can be specified instead of a hexadecimal value can be found in <<annex_bgcolor>>

include::recommendations/background/PER_bgcolor-alpha.adoc[]

include::requirements/background/REQ_transparent-definition.adoc[]

NOTE: When not specified, the value of `transparent` defaults to `true` when `bgcolor` is not used, but to `false` when used together with `bgcolor`.  
For formats with an alpha channel, explicitly setting `transparent=true` together with a `bgcolor` allow for defining the color value to use for the RGB channels where there is no data. Zero (0) will be used for the alpha channel.
For formats reserving a color to define transparency (color key), the combination supports selecting a color that does not interfere with the actual values and colors in the map.

NOTE: The `opaque` attribute of layer element in the GetCapabilities response in WMS is deprecated and is not specified by the Maps API.

==== Response
A successful GET response is described in the core class (https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core)

include::requirements/background/REQ_map-success.adoc[]
