[[rc_background]]
== Requirement Class "Background"

=== Overview

[[background-overview]]

include::requirements/requirements_class_background.adoc[]

This requirement class describes how to define the background of the map for the areas that has no data.

=== Map operation

The core requirements class of this standard defines how to get a map. This requirements class specifies parameters allowing to customize the background of the map.

==== Parameters `transparent` and `bgcolor`
The `transparent` and `bgcolor` parameters indicate how the absence of data will be represented in the map, what color will show underneath any non-opaque layer, and allow for the map to be overlaid with other maps without completely obscuring the lower layers.

include::requirements/background/REQ_bgcolor-definition.adoc[]

The list of W3C color names which can be specified instead of a hexadecimal value is shown in the following table:

.Named web color enumeration
[width="90%",options="header"]
|===
|  Name                |   Hexadecimal |Value (r, g, b)
|  black               |    `0x000000` |   0,   0,   0 |
   dimGray             |    `0x696969` | 105, 105, 105 |
   dimGrey             |    `0x696969` | 105, 105, 105 |
   gray                |    `0x808080` | 128, 128, 128 |
   grey                |    `0x808080` | 128, 128, 128 |
   darkGray            |    `0xa9a9a9` | 169, 169, 165 |
   darkGrey            |    `0xa9a9a9` | 169, 169, 165 |
   silver              |    `0xc0c0c0` | 192, 192, 192 |
   lightGray           |    `0xd3d3d3` | 211, 211, 211 |
   lightGrey           |    `0xd3d3d3` | 211, 211, 211 |
   gainsboro           |    `0xdcdcdc` | 220, 220, 220 |
   whiteSmoke          |    `0xf5f5f5` | 245, 245, 245 |
   white               |    `0xffffff` | 255, 255, 255 |
   rosyBrown           |    `0xbc8f8f` | 188, 143, 143 |
   indianRed           |    `0xcd5c5c` | 205,  92,  92 |
   brown               |    `0xa52a2a` | 165,  42,  42 |
   fireBrick           |    `0xb22222` | 178,  34,  34 |
   lightCoral          |    `0xf08080` | 240, 128, 128 |
   maroon              |    `0x800000` | 128,   0,   0 |
   darkRed             |    `0x8b0000` | 139,   0,   0 |
   red                 |    `0xff0000` | 255,   0,   0 |
   snow                |    `0xfffafa` | 255, 250, 250 |
   mistyRose           |    `0xffe4e1` | 255, 228, 225 |
   salmon              |    `0xfa8072` | 250, 128, 114 |
   tomato              |    `0xff6347` | 255,  99,  71 |
   darkSalmon          |    `0xe9967a` | 233, 150, 122 |
   coral               |    `0xff7f50` | 255, 127,  80 |
   orangeRed           |    `0xff4500` | 255,  69,   0 |
   lightSalmon         |    `0xffa07a` | 255, 160, 122 |
   sienna              |    `0xa0522d` | 160,  82,  45 |
   seaShell            |    `0xfff5ee` | 255, 245, 238 |
   chocolate           |    `0xd2691e` | 210, 105,  30 |
   saddleBrown         |    `0x8b4513` | 139,  69,  19 |
   sandyBrown          |    `0xf4a460` | 244, 164,  96 |
   peachPuff           |    `0xffdab9` | 255, 218, 185 |
   peru                |    `0xcd853f` | 205, 133,  63 |
   linen               |    `0xfaf0e6` | 250, 240, 230 |
   bisque              |    `0xffe4c4` | 255, 228, 196 |
   darkOrange          |    `0xff8c00` | 255, 140,   0 |
   burlyWood           |    `0xdeb887` | 222, 184, 135 |
   tan                 |    `0xd2b48c` | 210, 180, 140 |
   antiqueWhite        |    `0xfaebd7` | 250, 235, 215 |
   navajoWhite         |    `0xffdead` | 255, 222, 173 |
   blanchedAlmond      |    `0xffebcd` | 255, 235, 205 |
   papayaWhip          |    `0xffefd5` | 255, 239, 213 |
   moccasin            |    `0xffe4b5` | 255, 228, 181 |
   orange              |    `0xffa500` | 255, 165,   0 |
   wheat               |    `0xf5deb3` | 245, 222, 179 |
   oldLace             |    `0xfdf5e6` | 253, 245, 230 |
   floralWhite         |    `0xfffaf0` | 255, 250, 240 |
   darkGoldenrod       |    `0xb8860b` | 184, 134,  11 |
   goldenrod           |    `0xdaa520` | 218, 165,  32 |
   cornsilk            |    `0xfff8dc` | 255, 248, 220 |
   gold                |    `0xffd700` | 255, 215,   0 |
   khaki               |    `0xf0e68c` | 240, 230, 140 |
   lemonChiffon        |    `0xfffacd` | 255, 250, 205 |
   paleGoldenrod       |    `0xeee8aa` | 238, 232, 170 |
   darkKhaki           |    `0xbdb76b` | 189, 183, 107 |
   beige               |    `0xf5f5dc` | 245, 245, 220 |
   lightGoldenRodYellow|    `0xfafad2` | 250, 250, 210 |
   olive               |    `0x808000` | 128, 128,   0 |
   yellow              |    `0xffff00` | 255, 255,   0 |
   lightYellow         |    `0xffffe0` | 255, 255, 224 |
   ivory               |    `0xfffff0` | 255, 255, 240 |
   oliveDrab           |    `0x6b8e23` | 107, 142,  35 |
   yellowGreen         |    `0x9acd32` | 154, 205,  50 |
   darkOliveGreen      |    `0x556b2f` |  85, 107,  47 |
   greenYellow         |    `0xadff2f` | 173, 255,  47 |
   chartreuse          |    `0x7fff00` | 127, 255,   0 |
   lawnGreen           |    `0x7cfc00` | 124, 252,   0 |
   darkSeaGreen        |    `0x8fbc8f` | 143, 188, 139 |
   forestGreen         |    `0x228b22` |  34, 139,  34 |
   limeGreen           |    `0x32cd32` |  50, 205,  50 |
   lightGreen          |    `0x90ee90` | 144, 238, 144 |
   paleGreen           |    `0x98fb98` | 152, 251, 152 |
   darkGreen           |    `0x006400` |   0, 100,   0 |
   green               |    `0x008000` |   0, 128,   0 |
   lime                |    `0x00ff00` |   0, 255,   0 |
   honeyDew            |    `0xf0fff0` | 240, 255, 240 |
   seaGreen            |    `0x2e8b57` |  46, 139,  87 |
   mediumSeaGreen      |    `0x3cb371` |  60, 179, 113 |
   springGreen         |    `0x00ff7f` |   0, 255, 127 |
   mintCream           |    `0xf5fffa` | 245, 255, 250 |
   mediumSpringGreen   |    `0x00fa9a` |   0, 250, 154 |
   mediumAquaMarine    |    `0x66cdaa` | 102, 205, 170 |
   aquamarine          |    `0x7fffd4` | 127, 255, 212 |
   turquoise           |    `0x40e0d0` |  64, 224, 208 |
   lightSeaGreen       |    `0x20b2aa` |  32, 178, 170 |
   mediumTurquoise     |    `0x48d1cc` |  72, 209, 204 |
   darkSlateGray       |    `0x2f4f4f` |  47,  79,  79 |
   darkSlateGrey       |    `0x2f4f4f` |  47,  79,  79 |
   paleTurquoise       |    `0xafeeee` | 175, 238, 238 |
   teal                |    `0x008080` |   0, 128, 128 |
   darkCyan            |    `0x008b8b` |   0, 139, 139 |
   aqua                |    `0x00ffff` |   0, 255, 255 |
   cyan                |    `0x00ffff` |   0, 255, 255 |
   lightCyan           |    `0xe0ffff` | 224, 255, 255 |
   azure               |    `0xf0ffff` | 240, 255, 255 |
   darkTurquoise       |    `0x00ced1` |   0, 206, 209 |
   cadetBlue           |    `0x5f9ea0` |  95, 158, 160 |
   powderBlue          |    `0xb0e0e6` | 176, 224, 230 |
   lightBlue           |    `0xadd8e6` | 173, 216, 230 |
   deepSkyBlue         |    `0x00bfff` |   0, 191, 255 |
   skyBlue             |    `0x87ceeb` | 135, 206, 235 |
   lightSkyBlue        |    `0x87cefa` | 135, 206, 250 |
   steelBlue           |    `0x4682b4` |  70, 130, 180 |
   aliceBlue           |    `0xf0f8ff` | 240, 248, 255 |
   dodgerBlue          |    `0x1e90ff` |  30, 144, 255 |
   slateGray           |    `0x708090` | 112, 128, 144 |
   slateGrey           |    `0x708090` | 112, 128, 144 |
   lightSlateGray      |    `0x778899` | 119, 136, 153 |
   lightSlateGrey      |    `0x778899` | 119, 136, 153 |
   lightSteelBlue      |    `0xb0c4de` | 176, 196, 222 |
   cornflowerBlue      |    `0x6495ed` | 100, 149, 237 |
   royalBlue           |    `0x4169e1` |  65, 105, 225 |
   midnightBlue        |    `0x191970` |  25,  25, 112 |
   lavender            |    `0xe6e6fa` | 230, 230, 250 |
   navy                |    `0x000080` |   0,   0, 128 |
   darkBlue            |    `0x00008b` |   0,   0, 139 |
   mediumBlue          |    `0x0000cd` |   0,   0, 205 |
   blue                |    `0x0000ff` |   0,   0, 255 |
   ghostWhite          |    `0xf8f8ff` | 248, 248, 255 |
   slateBlue           |    `0x6a5acd` | 106,  90, 205 |
   darkSlateBlue       |    `0x483d8b` |  72,  61, 139 |
   mediumSlateBlue     |    `0x7b68ee` | 123, 104, 238 |
   mediumPurple        |    `0x9370db` | 147, 112, 219 |
   blueViolet          |    `0x8a2be2` | 138,  43, 226 |
   indigo              |    `0x4b0082` |  75,   0, 130 |
   darkOrchid          |    `0x9932cc` | 153,  50, 204 |
   darkViolet          |    `0x9400d3` | 148,   0, 211 |
   mediumOrchid        |    `0xba55d3` | 186,  85, 211 |
   thistle             |    `0xd8bfd8` | 216, 191, 216 |
   plum                |    `0xdda0dd` | 221, 160, 221 |
   violet              |    `0x40e0d0` | 238, 130, 238 |
   purple              |    `0x800080` | 128,   0, 128 |
   darkMagenta         |    `0x8b008b` | 139,   0, 139 |
   magenta             |    `0xff00ff` | 255,   0, 255 |
   fuschia             |    `0xff00ff` | 255,   0, 255 |
   orchid              |    `0xda70d6` | 218, 112, 214 |
   mediumVioletRed     |    `0xc71585` | 199,  21, 133 |
   deepPink            |    `0xff1493` | 255,  20, 147 |
   hotPink             |    `0xff69b4` | 255, 155, 180 |
   lavenderBlush       |    `0xfff0f5` | 255, 240, 245 |
   paleVioletRed       |    `0xdb7093` | 219, 112, 147 |
   crimson             |    `0xdc143c` | 220,  20,  60 |
   pink                |    `0xffc0cb` | 255, 192, 203 |
   lightPink           |    `0xffb6c1` | 255, 182, 193
|===

include::recommendations/background/PER_bgcolor-alpha.adoc[]

include::requirements/background/REQ_transparent-definition.adoc[]

NOTE: When not specified, the value of `transparent` defaults to `true` when `bgcolor` is not used, but to `false` when used together with `bgcolor`.
When explicitly setting `transparent=true` together with a `bgcolor`, for formats with an alpha channel, it allows defining the color value to use for the RGB channels where there is no data, while 0 will be used for the alpha channel.
For formats reserving a color to define transparency (color key), the combination allows selecting a color that does not interfere with the actual values and colors in the map.

NOTE: The `opaque` attribute of layer element in the GetCapabilities response in WMS has been deprecated and is not specified by this API.

==== Response
A successful GET response is described in the core class (http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core)

include::requirements/background/REQ_map-success.adoc[]
