== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

This document also uses terms defined in the OGC Standard for Modular specifications (https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the 'ModSpec'. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

For the purposes of this document, the following additional terms and definitions apply.

=== *coordinate reference system*
coordinate system that is related to the real world by a datum (source: ISO 19111)


=== *coordinate system*
set of mathematical rules for specifying how coordinates are to be assigned to points (source: ISO 19111)


=== *geographic information*
information concerning phenomena implicitly or explicitly associated with a location relative to the Earth (source: ISO 19101)


=== *map*
portrayal of geographic information as a digital image file suitable for display on a computer screen (source: OGC 06-042)


=== *portrayal*
presentation of information to humans (source: ISO 19117)


=== *Web API*
An Application Programming Interface (API) using an architectural style that is founded on the technologies of the Web (source: OGC 17-069r3)

NOTE: See https://www.w3.org/TR/dwbp/#accessAPIs[Best Practice 24: Use Web Standards as the foundation of APIs] (W3C Data on the Web Best Practices) for more detail.
