[[rc_display_resolution]]
== Requirement Class "Display Resolution"

=== Overview

[[maps-display-resolution-overview]]

include::requirements/requirements_class_display_resolution.adoc[]

This requirement class describes how to scale a map by specifying a set of parameters that will define its size (width and height) in pixels of a displaying device that indirectly defines que scale of the map.

=== Map Operation

This requirements class specifies the `mm-per-pixel` parameter to accurately interpret scale denominators and symbology rules.

==== Parameter `mm-per-pixel`
The width and height of the image to be presented in the display device is not actually controlling the scale because it is provided in pixel units. What controls the scale is the ratio between the size of features represented in the map and the size of the same features in the reality. One way to determine the scale is to divide the actual size of the display device in physical units (e.g. millimeters) by the actual size of the extent of the map (e.g. in meters).
include::requirements/display-resolution/REQ_mm-per-pixel-definition.adoc[]

With this parameter, the server is able to know how big the map will be presented or printed and react accordingly.
For example, if the server receives a very small value, the server could decide to represent linear elements wider than for normal values (preventing to create a representation of linear features that is going to result in lines that are too thin to be correctly perceived).

==== Response
A successful GET response is described in the core class (http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core)

include::requirements/display-resolution/REQ_map-success.adoc[]

==== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the parameters values for `mm-per-pixel` are out-of-range, the status code of the response will be `400`.
If map is not provided due to lack of data in the area, the status code of the response will be `204`.
