== Conventions
This section provides details of conventions used in this document.

=== Identifiers

The normative provisions in this standard are denoted by the URI `http://www.opengis.net/spec/ogcapi-maps-1/1.0`.

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== Link relations

To express relationships between resources, https://tools.ietf.org/rfc/rfc8288.txt[RFC 8288 (Web Linking)] is used.

The following https://www.iana.org/assignments/link-relations/link-relations.xhtml[IANA link relation types] are used in this document:

* **alternate**: Refers to a substitute for this context.

* **self**: Conveys an identifier for the link’s context.

* **item**: The target IRI points to a resource that is a member of the collection represented by the context IRI.

* **service-desc**: Identifies service description for the context that is primarily intended for consumption by machines. (Web API definitions are considered service descriptions)

* **service-doc**: Identifies service documentation for the context that is primarily intended for human consumption.

In addition, the following link relation type is used for which no applicable registered link relation type could be identified:

* **http://www.opengis.net/def/rel/ogc/1.0/map**: Refers to a resource that is map representation of another geospatial resource (e.g. a collection)

Used in combination with _OGC API - Tiles - Part 1: Core_, other link relation types will be used, including:

* **http://www.opengis.net/def/rel/ogc/1.0/tilesets-map**: The target IRI points to a resource that describes how to provide tile sets of the context resource in map format.

Used in combination with _OGC API - Styles - Part 1: Core_, other link relation types will be used, including:

* **http://www.opengis.net/def/rel/ogc/1.0/styles**: The target IRI points to a resource that describes how to provide styles of the context resource that internally can contain links to maps.

Used in combination with _OGC API - Features - Part 1: Core_ or _OGC API - Common - Part 1: Core_, other link relation types will be used, including:

* **http://www.opengis.net/def/rel/ogc/1.0/conformance**: Refers to a resource that identifies the specifications that the link's context conforms to.

Used in combination with _OGC API - Features Part 1: Core_ or _OGC API - Common Part 2: Geospatial data_, other link relation types will be used, including:

* **http://www.opengis.net/def/rel/ogc/1.0/data**: Refers to the list of collections available for a dataset.

Each resource representation includes an array of links. Implementations are free to add additional links for all resources provided by the Web API.

=== Use of HTTPS

For simplicity, this document in general only refers to the HTTP protocol. This is not meant to exclude the use of HTTPS and simply is a shorthand notation for "HTTP or HTTPS." In fact, most servers are expected to use https://tools.ietf.org/html/rfc2818[HTTPS], not https://www.ietf.org/rfc/rfc2616.txt[HTTP].
