[[rc_projection]]
== Requirement Class "Custom Projection CRS"

[[maps-projection-overview]]
=== Overview

include::requirements/requirements_class_projection.adoc[]

The Custom Projection CRS requirements class defines the ability for clients to specify a custom projection CRS based on parameters defining a projection operation method, values for corresponding parameters, as well as a datum.
This class also provides a parameter facilitating the task of selecting a projection center across different projections, for which the relevant latitude and longitude parameters differ.
Angles are specified in degrees, whereas identifiers for methods, parameters and datums can be specified as URIs or safe CURIEs.
Additionally, this requirements class defines a resource at `/projectionsAndDatums` listing the available operation methods and their associated parameters, as well as the possible datums that can be used as values for these parameters.

=== Operation

==== Parameter `crs-proj-method`
The operation method refers mainly to the equations that relates geographic coordinates to projected coordinates and vice-versa.

include::requirements/projection/REQ_crs-proj-method.adoc[]

==== Parameter `crs-proj-params`
The operation method may have some parameters, such as the standard parallel, to set. This query parameter supports setting those values. In some simple cases this query parameter might not be necessary, and clients can consider using `crs-proj-center` instead.

include::requirements/projection/REQ_crs-proj-params.adoc[]

==== Parameter `crs-proj-center`

To facilitate the task of centering a custom projection on the area of interest, with parameters varying greatly between projections, the `crs-proj-center` parameter automatically sets the most appropriate parameters
for the specified center latitude and longitude.

include::requirements/projection/REQ_crs-proj-center-definition.adoc[]

NOTE: For some projections where there is not a clear single center latitude parameter, such as those with multiple standard parallels, clients should use `crs-proj-params` to unambiguously set each parameter instead.

==== Parameter `crs-datum`

include::requirements/projection/REQ_crs-datum.adoc[]

==== Response headers

include::requirements/projection/REQ_response-headers.adoc[]

Example of a request and associated response headers:

```
/map?
   crs-proj-method=[epsg-method:9840]&
   crs-proj-center=Lat(30),Lon(40)&
   crs-datum=[epsg-datum:6326]
```

```
Content-Crs-Method: <https://www.opengis.net/def/method/EPSG/0/9840>
Content-Crs-Method-Params: <https://www.opengis.net/def/parameter/EPSG/0/8801>=30; <https://www.opengis.net/def/parameter/EPSG/0/8802>=40
Content-Crs-Datum: <https://www.opengis.net/def/datum/EPSG/0/6326>
Content-Bbox: -1000,-800,1000,800
```

==== Response

A successful GET response is described in the Maps API core class (https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core).

==== Error conditions

A general summary of the HTTP status codes can be found in https://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in the https://docs.ogc.org/is/19-072/19-072.html[OGC API – Common – Part 1: Core] Standard.

If the parameter value for the parameters is not valid, the status code of the response will be `400`.

=== Available projections

==== Available projections operation

The resource at `/projectionsAndDatums` supports a `GET` operation, with JSON as an available representation, returning a list of the supported projection operation methods and their associated parameters,
as well as a list of available datums, applying to all map retrieval operations of the API.

include::requirements/projection/REQ_projections-resource.adoc[]

==== Available projections response

The custom projections resource includes a `methods` property listing the available projections operation methods,
corresponding to the valid values for the `crs-proj-method` query parameter, and their associated parameters,
corresponding to the valid values for the `crs-proj-params` parameters.

The custom projections resource also includes a `datums` property listing the available datums corresponding to the valid values for the `crs-datum` query parameter.

include::requirements/projection/REQ_projections-response.adoc[]

.Example JSON response for `/projectionsAndDatums` resource listing available projections, parameters and datums
====
[source,json]
----
{
   "methods":
   {
      "[epsg-method:9802]":
      {
         "title": "Lambert Conic Conformal",
         "description": "Lambert Conic Conformal projection (2 standard parallels)",
         "parameters":
         {
            "[epsg-parameter:8823]": { "$ref": "#/parameters/[epsg-parameter:8823]" },
            "[epsg-parameter:8824]": { "$ref": "#/parameters/[epsg-parameter:8824]" },
         },
         "centerLatParam": "[epsg-parameter:8823]"
      },
      "[epsg-method:9805]":
      {
         "title": "Mercator",
         "description": "Mercator projection",
         "parameters":
         {
            "[epsg-parameter:8823]": { "$ref": "#/parameters/[epsg-parameter:8823]" },
            "[epsg-parameter:8802]": { "$ref": "#/parameters/[epsg-parameter:8802]" }
         },
         "centerLatParam": "[epsg-parameter:8823]",
         "centerLonParam": "[epsg-parameter:8802]"
      },
      "[epsg-method:9807]":
      {
         "title": "Transverse Mercator",
         "description": "Transverse Mercator projection",
         "parameters":
         {
            "[epsg-parameter:8801]": { "$ref": "#/parameters/[epsg-parameter:8801]" },
            "[epsg-parameter:8802]": { "$ref": "#/parameters/[epsg-parameter:8802]" }
         },
         "centerLatParam": "[epsg-parameter:8801]",
         "centerLonParam": "[epsg-parameter:8802]"
      },
      "[epsg-method:9820]":
      {
         "title": "Lambert Azimuthal Equal Area",
         "description": "Lambert Azimuthal Equal Area projection",
         "parameters":
         {
            "epsg-parameter:8801": { "$ref": "#/parameters/[epsg-parameter:8801]" },
            "epsg-parameter:8802": { "$ref": "#/parameters/[epsg-parameter:8802]" }
         },
         "centerLatParam": "[epsg-parameter:8801]",
         "centerLonParam": "[epsg-parameter:8802]"
      },
      "[epsg-method:9829]":
      {
         "title": "Polar Stereographic",
         "description": "Polar Stereographic projection",
         "parameters":
         {
            "[epsg-parameter:8832]": { "$ref": "#/parameters/[epsg-parameter:8832]" },
            "[epsg-parameter:8833]": { "$ref": "#/parameters/[epsg-parameter:8833]" },
         },
         "centerLatParam": "[epsg-parameter:8832]",
         "centerLonParam": "[epsg-parameter:8833]"
      },
      "[epsg-method:9840]":
      {
         "title": "Orthographic",
         "description": "Orthographic projection",
         "parameters":
         {
            "epsg-parameter:8801": { "$ref": "#/parameters/[epsg-parameter:8801]" },
            "epsg-parameter:8802": { "$ref": "#/parameters/[epsg-parameter:8802]" }
         },
         "centerLatParam": "[epsg-parameter:8801]",
         "centerLonParam": "[epsg-parameter:8802]"
      },
      "mollweide":
      {
         "title": "Mollweide",
         "description": "Mollweide projection",
         "parameters":
         {
            "epsg-parameter:8802": { "$ref": "#/parameters/[epsg-parameter:8802]" }
         },
         "centerLonParam": "[epsg-parameter:8802]"
      }
   },
   "parameters":
   {
      "[epsg-parameter:8801]": { "title": "Latitude of natural origin" },
      "[epsg-parameter:8802]": { "title": "Longitude of natural origin" },
      "[epsg-parameter:8823]": { "title": "Latitude of 1st standard parallel" },
      "[epsg-parameter:8824]": { "title": "Latitude of 2nd standard parallel" },
      "[epsg-parameter:8832]": { "title": "Latitude of standard parallel" },
      "[epsg-parameter:8833]": { "title": "Longitude of origin" }
   },
   "datums":
   {
      "[epsg-datum:6230]":
      {
         "title": "European Datum 1950",
         "description": "European Datum 1950",
         "ellipsoid": "[epsg-ellipsoid:7022]"
      },
      "[epsg-datum:6326]":
      {
         "title": "WGS84",
         "description": "World Geodetic System 1984 ensemble",
         "ellipsoid": "[epsg-ellipsoid:7030]"
      }
   }
}
----
====
