[[rc_maps_core]]
== Requirement Class "Core"

=== Overview

[[maps-core-overview]]

include::requirements/requirements_class_core.adoc[]

This core specifies a map resource: a resource that represents the geospatial data as a rendered map. Requesting a map resource, as defined in this core, results in retrieving a generic map as a graphical representation of the data in the API. With only the core, the representation is not constrained almost in any way by the client, so the server is free to return a total or a partial representation of the resource of an arbitrary size. Additional requirement classes will add query parameters to personalize the server behavior to the client needs. These requirement classes will define specific parameters that will allow for the client to control the map size and resolution of the map (width, height, bounding box and CRS) and well as the background of the map. In addition, an orthogonal requirement class will define how a map resource can be retrieved as tiles by applying the OGC API - Tiles.

A map resource can be obtained from a non map resource by adding `/map` to the resource URI. The core does not specify to which resources `/map` is applicable. However, a list of common places in the API, where maps can commonly be obtained is present in the following table as a recommendation. Additional requirements classes will better define these possibilities.

[#Common-map-resources-in-the-api,reftext='{table-caption} {counter:table-num}']
.Common map resources in an geospatial API
[width = "100%",options="header"]
|===
|Resource	Path |Description
|/map |A map representing dataset behind the API in the default style
|/styles/{styleId}/map |A map representing dataset behind the API in the `styleId` style.
|/collections/{collectionId}/map | A map representing `collectionId` in the default style
|/collections/{collectionId}/styles/{styleId}/map | A map representing `collectionId` in the `styleId` style
|===

NOTE: There is no mandatory dependency of this core on OGC API - Commons. This allows for non-OGC APIs to implement this core without the need to comply to the OGC API common structure (landing page, conformance, API description). However, it expected that many implementations will specify a dependency on OGC API - Commons in their conformance page.

=== Map resource

A map distribution of a geospatial resource is a pictorial representation of it. To create a pictorial representation, a style is added to the data in the geospatial resource by a portrayal engine and following portrayal rules. This style can be internal (default style) or can be governed by the client.

This section defines the core resource of the OGC API - Maps standard: a map representation for a geospatial resources. To keep the core of the OGC API - Maps standard simple, the core only includes a mechanism to retrieve an map of an arbitrary size and from the extent the server considers optimal.

==== Operation
include::requirements/core/REQ_map-op.adoc[]

==== Response
include::requirements/core/REQ_map-response.adoc[]

==== Recommendations

include::recommendations/core/REC_map-op.adoc[]

include::recommendations/core/REC_content-crs.adoc[]

include::recommendations/core/REC_link-relation-type.adoc[]

A map resource may be retrieved as a map subset or a tile subsets. Retrieving the map without subsetting or tiling has a limited use.

NOTE: The desired encoding is selected using HTTP content negotiation. In addition to the parameters specified by the core, other parameters should be added.

NOTE: HTTP content negotiation replaces the FORMAT= parameters in WMS. However, for convenience, some implementations can implement a f= parameter for circumstances where content negotiation is not possible or available (e.g. testing the API in a web browser by using a URL embed in a HTML IMG SRC tag)

=== Declaration of conformance classes
To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the conformance classes it implements and conforms to.

The conformance page mainly consists of a list of links.

include::requirements/core/REQ_conformance-success.adoc[]

If the server declares also conformity to OGC API - Common - Part 1: Core or to OGC API - Features - Part 1: Core, then it has to consider the OGC API requirements for declaring conformance, i.e. the use of a the conformance page. In the JSON format the conformance page is an array of links following the link schema defined in the OGC API - Common - Part 1: Core or in OGC API - Features - Part 1: Core. Below is an example fragment of a conformance information page of an API conformant to OGC API - Common and OGC API - Maps.

[[ConformancePageMapsCore]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core"
  ]
}
=================
