== Scope

This Standard specifies how to access maps and map tiles in a manner independent of the underlying data store. The API defined by this Standard can be described and documented using the https://www.openapis.org/[OpenAPI] specification and specifies resources for discovering and retrieving maps from a Web API.

Specifically, this _OGC API - Maps_ Standard supports the following:

* discovery operations that allow the API to be interrogated to determine its capabilities and to retrieve information (metadata) about this distribution of maps. This includes the API definition (if also implementing _OGC API - Common - Part 1: Core_), as well as metadata about the map layers provided through the API and the Coordinate Reference Systems supported by the API,
* retrieval operations that allow a client application to retrieve a map, using a default or pre-defined style, for an arbitrary geospatial resource, an OGC API dataset or an OGC API collection of geospatial data,
* parameters for specifying the background and transparency of the map,
* parameters for specifying the scale of the map,
* a parameter for specifying the pixel size of the device or medium on which the map is intended to be displayed,
* parameters for retrieving only a subset of the map,
* a parameter for specifying a particular orientation for the map,
* parameters for specifying a Coordinate Reference System for the map by reference or using a projection operation method, parameters for that method and a datum.
