[[rc_scaling]]
== Requirement Class "Scaling"

=== Overview

[[maps-scaling-overview]]

include::requirements/requirements_class_scaling.adoc[]

The Scaling requirement class describes how to scale a map for display by specifying a set of parameters that will define its size (width and height) in pixels of a display device that indirectly defines the scale of the map.

=== Map Operation

The Maps API _core_ requirements class defines how to retrieve a map. The Scaling requirements class specifies two alternative mechanisms for specifying the scale of the map, either implicitly by providing output dimensions using
`width` and `height` parameters, or explicitly by providing a `scale-denominator` parameter.

==== Parameters `width` and `height`
The width and height parameters indicate the size of the viewport in rows and columns where the map is to be displayed. If the format of the response is a raster image, the number of columns and rows of the responded image will commonly match the width and height of the viewport.

include::requirements/scaling/REQ_width-definition.adoc[]

include::requirements/scaling/REQ_height-definition.adoc[]

NOTE: The `width` and `height` parameters are also defined by the Maps API _spatial subsetting_ requirements class.
The parameter takes this resampling (scaling) role in requests not using either of the `scale-denominator` parameter (defined in this requirements class),
or the `center` parameter (defined in the _spatial subsetting_ requirements class), or when the _spatial subsetting_ requirements class is not supported.
In combination with a bounding box and display resolution (either the default of 0.28 mm/pixel or one specified by `mm-per-pixel` parameter from the _display resolution_ conformance class),
the `width` and `height` parameters define the scale of the map.

include::recommendations/scaling/REC_dimensions.adoc[]

==== Parameter `scale-denominator`
A client can specify the desired scale of the map as a scale denominator value using a `scale-denominator` parameter.
Given a selected unit of measure, the scale denominator specifies how many of these units in the real world correspond to a distance of one unit on the map as printed or displayed.

NOTE: The correspondence between real world units and display units depends on the display resolution for which a default 0.28 mm/pixel is assumed, unless a client specifies otherwise through the <<rc_display-resolution, display resolution requirements class>>.

NOTE: The `scale-denominator` is the only way to specify scaling when requesting a spatial subset using a `center` point.

include::requirements/scaling/REQ_scale-denominator-definition.adoc[]

include::recommendations/scaling/REC_symbology.adoc[]

==== Response
A successful GET response is described in the Maps API core class (https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core)

include::recommendations/scaling/REC_map-success-scale.adoc[]

==== Error conditions

A general summary of the HTTP status codes can be found in https://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in the https://docs.ogc.org/is/19-072/19-072.html[OGC API – Common – Part 1: Core] Standard.

If the parameters values for `width` or `height` are out-of-range, the status code of the response will be `413` (Payload too big).
If a map is not provided due to lack of data in the area, the status code of the response will be `204` or `404`.

[[scaling-aspect-ratio]]
=== Scale and aspect ratio considerations (informative)

Since all parameters for map requests are optional, implementations must fill in missing parameters by using default values or computing appropriate values based on the parameters provided by the client
and the specifics of the resource for which a map is being retrieved.
Implementations supporting the "Scaling" requirement class should compute these values in a way that respects the scale of the map in all dimensions, and thus the aspect ratio of physical features being represented.

For a non-global map, and for implementations supporting both "Scaling" and "Subsetting" where clients can request a subset of the map for a small local region,
implementations should consider the *local* scale of the map. For example, the applicable scale at the center, or most equatorial latitude of the map. This is as opposed to the global scale (e.g., at the equator). In addition, implementations should aim for the map scale to apply evenly to all dimensions. Consider a CRS such as Plate Carrée projection (CRS84 or EPSG:4326). When filling in an unspecified `bbox` and/or `width` and `height` parameters,
this is possible by applying a different linear scaling for the horizontal and vertical dimensions between the CRS units and the pixel dimensions, based on the most equatorial latitude included in the subset.

Another example is using a World Mercator projection (EPSG:3395). Although the CRS unit is "meters", they are only true meters at the equator.
When computing a bounding box extending away from a `center` and a `scale-denominator`, the ratio between the CRS unit meters and true physical meters should be considered
in order to accurately reflect the requested scale.

The ideal aspect ratio to maintain is the `physical_width / physical_height` = `width / height`, whereas `physical_width` and `physical_height` refer to the length of features
in the horizontal and vertical dimensions respectively, and `width` and `height` are the dimensions of the returned map in pixels.

In the case of a Plate Carrée CRS, a simple way to accurately reflect the two-dimensional scale is to use the most equatorial latitude contained in the map response as the standard parallel of the equirectangular projection.
This effectively implies scaling the horizontal distances of the Plate Carrée projection (assuming a standard parallel at 0°N) units by the cosine of that most equatorial latitude in order to get a more accurate physical horizontal distance.

In the case of a World Mercator CRS, an implementation could compute the number of CRS units separating one degree of longitude at the center latitude and compare that with the actual
number of physical meters, based on the `cos(lat)` scaling mentioned above, and the length of a degree in meters (WGS84 semi-major axis of 6,378,137 m * Pi / 180, or 111,319.4907932735805 m).

For slightly more accurate calculations, the WGS84 ellipsoid, can be taken into account using the following polynomial equations (from https://en.wikipedia.org/wiki/Geographic_coordinate_system#Length_of_a_degree[Wikipedia]):

```
metersPerDegLat = 111132.92 - 559.82 * cos(2*lat) + 1.175 * cos(4*lat) - 0.0023 * cos(6*lat)
metersPerDegLon = 111412.84 * cos(lat) - 93.5 * cos(3*lat) + 0.118 * cos(5*lat)
```

If maintaining the aspect ratio between physical units proves too difficult, implementations could fall back to maintaining the CRS unit aspect ratio instead. This way they ensure that
`(maxx - minx)/(maxy - miny) = width / height`, where `minx, miny` are the lower bounds of the output CRS unit space in the returned map,
`maxx, maxy` the upper bounds of that output CRS unit space on the map, and `width` and `height` are the dimensions of the returned map in pixels.

When neither width nor height is provided or implied, a good practical approach is to default to a reasonable size which is neither too low resolution, nor requiring too much computation power from the server.

When only one of the two dimension parameters is provided and no specific bounding box is requested, the value of the other could be used to return a square map by default.

When a bounding box is requested, the other dimension should be computed so as to preserve the aspect ratio.

When both dimensions are provided, but no bounding box, those dimensions should be used together with the default or requested center, and the scale denominator should be used to compute the bounding box.

Refer to the guidance for implementers provided in a <<overview-subsetting-and-scaling,section of the overview>> on the interactions of subsetting and scaling parameters. This
includes the specific combinations of parameters that can be provided based on which requirement classes are implemented, and which parameter assume default values or should be computed in each case.

When `bbox`, `width` and `height` are all provided, as in OGC Web Map Service (WMS), the client enforces a specific aspect ratio, and these recommendations are not relevant.
However, in general circumstances (e.g., 2D representations on a screen), the client should try to provide parameters that preserve the aspect ratio.

CAUTION: Due to the inherent difficulty in implementing the computations correctly for all CRSs and some degree of variability based on how these calculations are performed, implementations may compute missing parameters for the same request differently.
Clients should therefore always consider the `Content-Bbox:` response header and the actual dimensions of the returned map when geo-referencing and displaying images returned by the Maps API.
For identical responses to the same request across different implementations, clients should always provide a `bbox` (or its `subset` equivalent), `width` and `height` parameters (as in classic WMS requests). This is
rather than the `scale-denominator` and `center` parameters, which are primarily intended for convenience directly accessing a Maps API, such as from a Web browser.
For the purpose of overlaying map responses from different implementations, a client which does not itself geo-reference the output based on the `Content-Bbox:` response header
should always request maps using the `bbox`, `width` and `height` parameters.

See also detailed step-by-step examples in an annex of computations to <<dimensions-calculation-examples,infer dimensions>> and <<bbox-calculation-examples,infer bounding boxes>> based on specified parameters.

[[ScalingServiceMetadata]]
=== Service Metadata
The OGC API - Common Standard describes a mechanism to expose service-metadata for the API. See: OGC API - Common - Part 1: Core [OGC 19-072r1] Annex B.4 (2021)

include::recommendations/scaling/REC_max-width-height.adoc[]

NOTE: The attributes `maxWidth`, `maxHeight` and `maxPixels` are intended to limit server workload, by providing limitations in the size of the output. If the `width` and `height` limits are defined in relation to the size of a common device screen, Maps API implementations should consider that new devices are being built with more and more pixels and a reasonable limit from the current year may be too restrictive for devices emerging in the next year.

Example of the OpenAPI service metadata section:
----
info:
  title: My Web API
  version: 1.0.0
  description: This example shows population of an OpenAPI Info element with identifying
    metadata for both the service and the service provider.
  x-OGC-limits:
    maps:
      maxWidth: 2048
      maxHeight: 2048
      maxPixels: 10000000
----
