[[rc_geoDataResourceMaps]]
== Requirement Class "Geospatial Data Map"

=== Overview

include::requirements/requirements_class_geodata-map.adoc[]

This requirements class specifies how to get maps from particular resources that contains geodata. Common resources that can contain geodata are the ones at the endpoint /collections/{collectionId} defined by OGC API - Common or OGC API - Features 1.0.

=== General
include::recommendations/geodata/REC_api-common.adoc[]

This building block stays flexible and does not require to implement OWS Common, allowing for other API architectures outside the OGC API framework to adopt it. However, a server under the OGC APIs is expected to implement OGC API Common. If so, in practice, this means that the landing page and the conformance page follow OGC API - Common core and collections requirement classes will be used. Temporarily, it is also possible to combine this building block with OGC API features v1 that is not tied to OWS Common.

=== Geospatial data resources
This standard does not specify how geospatial resources are exposed in the API and if they have the possibility to be retrievable as geospatial data (e.g. feature items). This standard expect that other OGC API family standards will define how to expose these geospatial resources. Examples of standards that can expose geospatial resources are:

* OGC API - Features v1 includes the definition of collections and each collection is available in the /collections/{collectionId} path.
* OGC API - Common collections extension provides a similar mechanism.
* OGC API - Process exposes processes that may result in other paths in the API giving access to geospatial resources.

These geospatial resources can be modified or complemented by other resources creating new endpoints indirectly giving access to the modified or complemented resources. Other OGC API family standards will define this mechanisms. Examples of standards doing that are:

* OGC API - Styles defines how to complement a geospatial resource by adding a style to it. The new resource is an overlap of both resources

NOTE: The concept of geospatial resource path substitutes the concept of "layer" in WMS but it intends to give a better integration between data visualization and data access.

include::requirements/geodata/REQ_desc-links.adoc[]

include::recommendations/geodata/PER_desc-links.adoc[]

include::requirements/geodata/REQ_desc-crs.adoc[]

include::recommendations/geodata/REC_storage-epoch.adoc[]

.Fragment of a collection with a links array with one item of the array pointing to a map.
=================
[source,JSON]

  "id": "buildings",
  "title": "Buildings in the city of Bonn",
  "description": "This collection contains buildings",
  "attribution": "OpenStreetMap",
  "extent": {
    ...
  },
  "crs": ["EPSG:32631", "EPSG:23031", "EPSG:4326"],
  "storageCrs": "EPSG:32631",
  "storageCrsExtent": {
    "spatial" : {
         "bbox" : [ [ 47736, 4421022, 797736, 4734022 ] ]
    }
  },
  "storageCrsCoordinateEpoch": 2022.3,
  "links": [
    ...
    {
      "href": "http://data.example.com/collections/buildings/map",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/map",
      "type": "image/png",
    }
  ]
}
=================

NOTE: In WMS layers have a hierarchical dependency. At the time of writing this standard neither OGC API - Features v1 nor OGC API - Common do not consider this possibility.

=== Geospatial Data Resource Map
The maps core defines a `map` resource that is associated with an operation that contains the necessary information to later formulate a map request. Nevertheless, the core does not  specify how to retrieve a map resource representing another resource. This section offers one possible path to do that from a geospatial data resource offered by the API.

==== Map path

include::requirements/geodata/REQ_operation.adoc[]

This standard does not specify any additional query parameter in the GET request. Other extensions of this map standards will define how to get a subset of a map resource.

==== Response

A successful GET response is described in the core class (http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core)

A successful response is a map that represents the geodata resource.
