<<rc_spatial partitioning>>
== Requirement Class "Maps spatial partitioning"

=== Overview

[[maps-spatial-partitioning-overview]]

include::requirements/requirements_class_spatial-partitioning.adoc[]

This extension describes how to subset a map by specifying a bounding box (in a CRS). Another way to subset a map is provided by another requirements class is to make it accessible as tiles.

=== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of links. OGC API - Common already requires some links.

include::requirements/bbox/REQ_conformance-success.adoc[]

In the conformance page (typically in JSON format) the links follow the link schema defined in the OGC API - Common. The following is an example fragment of the response of an implementation of the OGC API – Maps draft specification with the maps extension conformance information page.

[[ConformancePageMapsSpatialPartitioning]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core"
    "http://www.opengis.net/spec/ogcapi-maps-2/1.0/req/bbox"
  ]
}
=================

=== Map resource
The _OGC API - Maps - Part 1: Core_ defines the map resource. The core also defines a minimum set of metadata to enable a client application to formulate a map request.

This class defines the extension to the core to formulate a bounding box subset.

The geospatial resource may expose a geospatial extent. This does not precluded that the map resource presents its own extent that will be similar or smaller to the geospatial extent resource (the API may opt to expose only a part of the geospatial resource as a map subsets)

==== Operation

The core of Part 1 defines how to get a map. This standard specifies the parameters needed to subset a map by bounding box

==== Parameter crs
This parameter has two missions: it indicates the CRS of the data rendered in the map and it is the CRS of the coordinates of the bbox parameter.
include::requirements/bbox/REQ_crs-definition.adoc[]

==== Parameter bbox
This parameter indicates the bounding box of the subset of the map to retrieved (in the crs coordinates). In this OGC API extension the `bbox` parameter values are defined considering the exterior edges of the pixels of the viewport defined by the width and height. In other words, the relation of the Bounding Box to the map pixel matrix is that the bounding box goes around the "outside" of the pixels of the map rather than through the centers of the map's border pixels (as many times done in coverages). In this context, individual pixels represent a cell area on the ground.

include::requirements/bbox/REQ_bbox-definition.adoc[]

NOTE: This parameter use the comma (",") as the separator between the coordinates. Additional white space will not be used to delimit list items. The comma character should not be escaped (IETF RFC 2396).

include::recommendations/bbox/PER_map-op.adoc[]

==== Parameters transparency and bgcolor
These parameters are defined at the OGC API - maps; core and are not modified by this extension

==== Response

A successful response to a map GET operation will be consistent with the media type of resource requested.

include::requirements/bbox/REQ_map-success.adoc[]


Normally, the content partially outside the map bounding box will be clipped at the extent of the bounding box. This can be done efficiently when map subsets are in raster format (e.g. map tiles). However, maps containing features in vector format may not clip features that are partially outside to ensure continuity of features or for performance.

==== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the parameter value `crs` is not available by the server for this resource or the parameters value `bbox` is out-of-range, or the map is not provided due to lack of data in the area, the status code of the response will be `404`.
