[[rc_tilesets]]
== Requirement Class "Map Tilesets"

=== Overview

[[maps-tilesets-overview]]

include::requirements/requirements_class_tilesets.adoc[]

This requirements class describes how to provide access to a map as tilesets in combination with the _OGC API - Tiles Standard.
However, the approach will not benefit from cache mechanisms. Instead, a map can be retrieved as tiles in a predefined TileMatrixSet.

NOTE: The concept of map tiles substitutes the WMTS 1.0 usage of tiles. WMTS was focused on map tiles (tiles that are rendered using a style).

=== Map
A map resource can be accessed as tiles if the API exposes a link to map tilesets in the resource that is available as map tiles.

include::requirements/tilesets/REQ_desc-links.adoc[]

.Fragment of a collection description document with a links array with one item of the array pointing to a list of map tilesets.
=================
[source,JSON]

{
    "links": [
    ...
    {
      "href": "http://data.example.com/collections/buildings/map/tiles",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/tilesets-map",
      "type": "application/json"
    }
  ]
}
=================

=== Map Tileset
A tileset contains the necessary metadata to enable a client application to formulate a tile request from a single geospatial data resource.

==== Operation

The operations to retrieve a list of tilesets, individual tilsets and individual tiles are described respectively in the Tilesets List, TileSet and Core
requirements classes of the _OGC API - Tiles_ Standard.

This requirements class does not specifies that the query parameters of the GET request to individual map tiles support as additional parameters
the ones defined in the _background_, _display resolution_ and _general subsetting_ requirements classes, when either of those requirement class is supported.

==== Response

Successful GET responses to requests for a list of map tilesets, an individual map tileset, and map tiles are described in the corresponding requirements
class of the _OGC API - Tiles_ Standard.
