[[rs_spatial-subsetting-by-center-point]]
== Requirement Class "Maps spatial subsetting by center point"

=== Overview

[[maps-spatial-subsetting-overview]]

include::requirements/requirements_class_spatial-subsetting.adoc[]

The core requirements class of this standard defines the map resource. The core also defines a minimum set of metadata to enable a client application to formulate a map request. This extension describes how to create and arbitrary subset of map. An alternative way to subset a map by referring to predefined boundaries is provided by <<rc_maps_tileSets-list>> that make a map accessible as tiles.

This class defines a extension to the core to formulate a 2D subset of a map that involves the definition of a center point and a scale. This mechanism is useful for cases where precisely defining the scale of the map is more important than defining the exact coordinate interval.

There is another way to subset a map that involves specifying two coordinate intervals. This mechanism is useful for clients that require precise control of the coordinate intervals they would like to show and it is described in <<rs_spatial-subsetting-by-coord-intervals>>

=== CRS for subsetting
The same consideration for CRS subsetting in <<rs_spatial-subsetting-by-coord-intervals>> apply here. See <<maps-spatial-subsetting-crs>>

==== Parameter TBD-crs

include::requirements/subsetting/REQ_bbox-crs-definition.adoc[]

NOTE: The `TBD-crs`, `subset-crs` and `bbox-crs` are defined identically except they are affecting `TBD`, `subset` and `bbox` parameters respectively (see <<rs_spatial-subsetting-by-coord-intervals>>).

==== CURIE permission

include::recommendations/subsetting/PER_subset-crs-curie.adoc[]

=== Subsetting coordinates and scale

==== Parameter TBD (center point)
This parameter defines how to subset a map by bounding box (in the bbox-crs coordinates). The `bbox` parameter values are defined considering the exterior edges of the pixels of the viewport defined by the width and height. In other words, the relation of the Bounding Box to the map pixel matrix is that the bounding box goes around the "outside" of the pixels of the map rather than through the centers of the map's border pixels (as many times done in coverages). In this context, individual pixels represent a cell area on the ground.

include::requirements/subsetting/REQ_bbox-definition.adoc[]

NOTE: This parameter use the comma (",") as the separator between the coordinates. Additional white space will not be used to delimit list items. The comma character should not be escaped (IETF RFC 2396).

==== Parameter TBD (scale)
The behavior of the subset parameter is imported from the OGC API - Common subset module. The entire module is reproduced here.
However, some considerations may not apply, and the generic behavior is limited by the CRS axis abbreviations.

include::api_modules/subset/requirements_module_subset.adoc[]

include::requirements/subsetting/REQ_subset-coordinates.adoc[]

include::recommendations/subsetting/REC_subset-crs-axis-names.adoc[]

=== Response

A successful GET response is described in the core class (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core).

include::requirements/subsetting/REQ_map-success.adoc[]

Normally, the content partially outside the map bounding box will be clipped at the extent of the bounding box. This can be done efficiently when map subsets are in raster format (e.g. map tiles). However, maps containing features in vector format may not clip features that are partially outside to ensure continuity of features or for performance.

include::recommendations/subsetting/REC_map-outside-bounds.adoc[]

include::recommendations/subsetting/PER_map-outside-bounds.adoc[]

NOTE: As defined in the core requirements class, the ogcapi-bbox and the content-crs reports the actual bounding box of the data returned.


=== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the CRS in the parameter value `bbox-crs` or `subset-crs` is not supported by the server for this resource, the parameter value is out-of-range, or the map is not provided due to lack of data in the area, the status code of the response will be `404`.
