== Requirement Class "Dataset Maps"

=== Overview

[[dataset-maps-overview]]

include::requirements/requirements_class_dataset.adoc[]

The map core and the map metadata, define how to get a map from a resource but they do nor detail which resources can be "mapped". This requirements class defines how to get a map resource from the dataset (or datasets) represented by the services. In other words it provides the path to get a map resource from the dataset behind the API. This is achieved by using by adding the map path to the root (a.k.a. the landing page) of the service.

=== General
include::recommendations/dataset/REC_api-common.adoc[]

This building block stays flexible and does not require implementation OGC API - Common, allowing for other API architectures outside the OGC API framework to adopt it. However, a server under the OGC APIs is expected to implement OGC API - Common. If so, in practice, this means that the landing page and the conformance page follow OGC API - Common core and collections requirement classes when used. Temporarily, it is also possible to combine this building block with http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] that is not tied to OGC API - Common.

=== Dataset API landing page

The landing page provides links to start exploring the resources offered by the API. It mainly consists of a list of links to `root` resources. This standard extension requires a new link in the landing page for getting a dataset map

==== Response

include::requirements/dataset/REQ_landingpage.adoc[]

In the landing page, in JSON format, the links follow the link schema defined in the OGC API - Common or in OGC API - Features v1. Below you can find an example fragment of the response to an OGC API - Maps landing page showing the link to root tiles.

[[landingPageTilesRoot]]
.API Landing Page fragment that advertises dataset maps
=================
[source,JSON]
----
{
  links: [
    ...,
    {
       "href": "http://data.example.org/tiles",
       "rel": "tiles",
       "type": "application/json",
       "title": "Link to information on map tilesets from the dataset",
    }
  ]
}
----
=================

=== Declaration of conformance classes

==== Response

The conformance page mainly consists of a list of links. OGC API - Common already requires some links.

include::requirements/dataset/REQ_conformance-success.adoc[]

In the conformance page (typically in JSON format) the links follow the link schema defined in the OGC API - Common. The following is an example fragment of the response of an OGC API - Maps conformance information page

[[ConformancePageMapsCollection]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core"
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/dataset"
  ]
}
=================

=== Dataset maps
The maps core defines a `map` resource that is associated with an operation that contains the necessary information to later formulate a map request. Nevertheless, the core does not does not specify how to retrieve a map resource description. This section offers one possible path to do that from the dataset represented by the API.

==== Map path

include::requirements/dataset/REQ_operation.adoc[]

The request of this operation has no parameters.

==== Response
A successful response to a map request is a map.
The response is expected to represent the dataset as a whole. In a Web API providing access to  a complex dataset formed by several geospatial data resources, there are reasons for being selective in the amount of information included. This can be achieved by applying a manual filter currently described in a OGC API - Tiles - Part 1 or as an automatic decision by the server side.

include::recommendations/dataset/REC_geodata-selection.adoc[]

include::recommendations/dataset/PER_geodata-selection.adoc[]
