[[rc_collection-map]]
== Requirement Class "Collection Map"

=== Overview

include::requirements/requirements_class_collection-map.adoc[]

This requirements class specifies how to get maps from particular resources that contains geodata. Common resources that can contain geodata are the ones at the endpoint `/collections/{collectionId}` defined by _OGC API - Common_ or _OGC API - Features_ 1.0 Standard.

=== General
include::recommendations/collection-map/REC_api-common.adoc[]

The Collection Maps requirements class depends on the _OGC API - Common - Part 2 - Geospatial data_ "collections" requirement classes
but remains flexible and does not require using _OGC API - Common - Part 1: Core_. This allows for other API architectures outside the OGC API framework to implement OGC API – Maps requirements classes.
However, OGC API servers are normally expected to implement _OGC API - Common - Part 1_.
If so, in practice, this means that the landing page and the conformance page follow _OGC API - Common - Part 1: Core_.
It is also possible to combine this building block with _OGC API - Features_ version 1.0 that is not tied to _OGC API - Common_, which can also be substituted for the _OGC API - Common - Part 2_ dependency.

=== Geospatial data resources
The Maps API standard does not specify how geospatial resources are exposed in the API or if they can be retrieved as raw geospatial data (e.g., feature items or coverage cell values). The Maps API standard expects that other OGC API standards will define how to expose additional access mechanisms for these geospatial resources. 
Examples of such standards, all of which also implement _OGC API - Common - Part 2: Geospatial data_ defining the `/collections` and `/collections/{collectionId}` paths, are:

* _OGC API - Tiles_ (coverage tiles and vector tiles)
* _OGC API - Features_
* _OGC API - EDR_
* _OGC API - Processes - Part 3: Workflows and Chaining_ ("Collection Output" requirements class)

These geospatial resources can be modified or complemented by other resources creating new endpoints indirectly giving access to the modified or complemented resources. Other OGC API family standards will define these mechanisms. Examples of OGC standards doing that are:

* _OGC API - Styles_ defines how to complement a geospatial resource by adding a style to it. The new resource is an overlap of both resources

NOTE: The concept of geospatial resource path substitutes the concept of "layer" in WMS but it intends to give a better integration between data visualization and data access.

include::requirements/collection-map/REQ_desc-links.adoc[]

include::recommendations/collection-map/PER_desc-links.adoc[]

include::requirements/collection-map/REQ_desc-crs.adoc[]

include::recommendations/collection-map/REC_storage-epoch.adoc[]

.Fragment of a collection with a links array with one item of the array pointing to a map.
=================
[source,JSON]

  "id": "buildings",
  "title": "Buildings in the city of Bonn",
  "description": "This collection contains buildings",
  "attribution": "OpenStreetMap",
  "extent": {
    ...
  },
  "crs": ["[EPSG:32631]", "[EPSG:23031]", "[EPSG:4326]"],
  "storageCrs": "[EPSG:32631]",
  "storageCrsExtent": {
    "spatial" : {
         "bbox" : [ [ 47736, 4421022, 797736, 4734022 ] ]
    }
  },
  "storageCrsCoordinateEpoch": 2022.3,
  "links": [
    ...
    {
      "href": "https://data.example.com/collections/buildings/map",
      "rel": "https://www.opengis.net/def/rel/ogc/1.0/map",
      "type": "image/png",
    }
  ]
}
=================

NOTE: In the WMS Standard, layers have a hierarchical dependency. At the time of writing this standard, neither _OGC API - Features_ v1 nor _OGC API - Common_ define such a concept.
However, there is a draft proposal to establish a hierarchical relation between collections based on a `parent` property and/or an `up` link relation type in the collection description.
If a collection represented a hierarchy, then the <<rc_collections-selection, Collections Selection>> requirements class could allow the selection of a subset of the collections it consists of to be included using the `collections` parameter.

=== Geospatial Data Resource Map
The core requirement class defines a map resource that is associated with an operation that contains the necessary information to later formulate a map request. Nevertheless, the Maps API core does not specify how to retrieve a map resource representing another resource. This section provides one possible workflow to support that use case from a geospatial data resource offered by an implementation of the Maps API.

==== Map path

include::requirements/collection-map/REQ_operation.adoc[]

This requirements class does not specify any additional query parameter for the GET request.

==== Response

A successful GET response is described in the Maps API core class (https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core).

A successful response is a map that represents the collection of geospatial data resource.
