[[rc_scaling]]
== Requirement Class "Scaling"

=== Overview

[[maps-scaling-overview]]

include::requirements/requirements_class_scaling.adoc[]

This requirement class describes how to scale a map by specifying a set of parameters that will define its size (width and height) in pixels of a displaying device that indirectly defines the scale of the map.

=== Map Operation

The _core_ requirements class of this standard defines how to retrieve a map.
This requirements class specifies two alternative mechanisms to specify the scale of the map, either implicitly by providing output dimensions using
`width` and `height` parameters, or explicitly by providing a `scale-denominator` parameter.

==== Parameters `width` and `height`
These parameters indicate the size of the viewport in rows and columns where the map is going to be shown. If the format of the response is a raster image, the number of columns and rows of the responded image will commonly match the width and height of the viewport.

include::requirements/scaling/REQ_width-definition.adoc[]

include::requirements/scaling/REQ_height-definition.adoc[]

NOTE: The `width` and `height` parameters are also defined by the _spatial subsetting_ requirements class.
The parameter takes this resampling (scaling) role in requests not using either of the `scale-denominator` parameter (defined in this requirements class),
or the `center` parameter (defined in the _spatial subsetting_ requirements class), or when the _spatial subsetting_ requirements class is not supported.
The `width` and `height` parameters define the scale of the map, in combination with either the default 0.28 mm/pixel default display resolution, or the resolution
specified by the _display resolution_ conformance class (`mm-per-pixel` parameter).

==== Parameter `scale-denominator`
A client can specify the desired scale of the map as a scale denominator value using a `scale-denominator` parameter.
The scale denominator specifies to how many units in the real world one of the same unit on the map corresponds, as printed or displayed.

NOTE: This correspondence depends on the display resolution for which defaults 0.28 mm/pixel is assumed, unless a client specifies otherwise through the <<rc_display-resolution, display resolution requirements class>>.

NOTE: The `scale-denominator` is the only way to specify scaling when requesting a spatial subset using a `center` point.

include::requirements/scaling/REQ_scale-denominator-definition.adoc[]

==== Aspect ratio considerations
If a client provides both width (w) and height (h) the server will adopt them even if the aspect ratio between (maxx-minx)/(maxy-miny) and w/h are different (resulting in a non square pixel). However, in general circumstances (e.g 2D representations in the screen), the client should make an effort to provide parameters that preserve the aspect ratio. The client is allowed to provide only one of the values in width and height and the server should figure out the other one to maintain the aspect ratio.

include::recommendations/scaling/REC_width-definition.adoc[]

include::recommendations/scaling/REC_height-definition.adoc[]

include::recommendations/scaling/PER_no-width-height-definition.adoc[]

==== Response
A successful GET response is described in the core class (http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core)

include::recommendations/scaling/REC_map-success-scale.adoc[]

==== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the parameters values for `width` or `height` are out-of-range, the status code of the response will be `413` (Payload too big).
If map is not provided due to lack of data in the area, the status code of the response will be `204`.

=== Service Metadata
The OGC API Common describes a mechanism to expose service-metadata for the API. See: http://docs.opengeospatial.org/DRAFTS/19-072.html#service-metadata-examples

include::recommendations/scaling/REC_max-width-height.adoc[]

NOTE: The attributes maxWidth, maxHeight and maxPixels are intended to limit the work load of the server, by providing limitations in size of the output. If your width and height parameters are defined in relation to the size of a common device screen, please consider that new devices are being build with more and more pixels and a reasonable limit last year may be too restrictive with devices emerging this year.
