[[rc_oas30_definition]]
== Requirement Class "OpenAPI Specification 3.0" API definition

=== Overview

include::requirements/requirements_class_oas30.adoc[]

This requirements class defines particularities of providing a definition of a Web API implementing this standard using OpenAPI Specification version 3.0.

=== Web API OpenAPI description

The OpenAPI definition provides a description of the complete list of API resources. Reading this description, an application will have the full picture of the resources that the API provides, how to retrieve them, and what responses are expected for successful and unsuccessful requests. Without this API description an application will be forced to traverse all links starting by the landing page to get an equivalent full list of resources.

The _OGC API - Common - Part 1: Core_ (_oas30_) requirement class provides many details on general requirements that this requirements class adopts by dependency. In addition extra requirements are provided. Also, the _OGC API - Common_ requirement class provides details on how to request an API definition.

==== Response

===== Completeness
The OpenAPI definition resulting as a response of this request need to take into consideration the relevant resources specified in this standard.

include::requirements/oas30/REQ_completeness.adoc[]

===== Reusable API components

Reusable components for creating OpenAPI definitions for implementations of this OGC API can be found in http://schemas.opengis.net/ogcapi/maps/part1/1.0/openapi

NOTE: While this specification is in draft status, the components are available from https://github.com/opengeospatial/ogcapi-maps/tree/master/openapi .

A server implementations of this OGC API can use the content in the openapi folder to generate a response for the openapi description. The _ogcapi-maps-1.yaml_ includes paths and components. An implementation should only include the paths that are implemented and remove the references to the rest. The components part includes parameters, responses and schemas that can be reused as-is. The `api` folder contains JSON files that are templates with enumerated values for collections (all, coverages or vector), styles. A particular implementation of this API should enumerate the actual resources exposed by the API in the same way. The server can select to dynamically implement responses to /api/* (where * is replaced by all-collections, styles,... ) or hardcode the /api/* files with the actual list of resource identifiers in the enumerations.

To improve performance, the whole content of this folder can be bundled in a single document by executing a tool such as _swagger-cli_. This can be served for the OGC API - Common - Part 1 `service-desc` link from the landing page.
