== Conformance

Conformance with this standard shall be checked using all the relevant tests specified in <<annex-ats, Annex A (normative)>> of this document if the respective conformance URLs listed in <<table_conformance_urls>> is present in the conformance response.
The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

The standardization targets of all conformance classes are "Web APIs".

The _OGC API - Maps - Part 1: Core_ Standard defines twenty-three **(23)** conformance classes, each corresponding to one requirements class.

The core conformance class is the only mandatory class. All other conformance classes are optional and depend on the _core_.

These classes act as building blocks that should be implemented in combination with other more fundamental classes that provide support for
documenting and formally describing a Web API (e.g., OpenAPI), listing supported conformance classes and listing available geospatial resources.
Possible alternatives for these fundamental classes are _OGC API - Common Part 1: Core_, _OGC API - Features Part 1: Core_ or any other non-OGC classes
that provide equivalent or alternative functionality.

The _OGC API - Maps - Part 1: Core_ Standard is intended to define a minimal set of functions for a useful API for fine-grained access to retrieve maps. 
Additional classes may be specified in future parts of the _OGC API - Maps_ series to add more capabilities or as vendor-specific extensions.

=== Requirements classes defining resources

*<<rc_core>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core)

The _Maps API_ Core specifies requirements that any Web API implementation instance of the Maps API Standard must implement to claim conformance with the _OGC API - Maps - Part 1: Core_ Standard.
This requirements class defines an operation to retrieve a map but does not define any query parameters to customize the map.

.Example request:
```
.../map
```

*<<rc_tilesets>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/tilesets)

The _map tilesets_ requirements class defines a mechanism to list available map tilesets (sets of tiles resulting from tiling data according to a particular tiling scheme, from https://www.opengis.net/doc/IS/tms/2.0[OGC 17-083r4 Two Dimensional Tile Matrix Set and Tile Set Metadata]) supported by the Web API instance and retrieve tiles (see definition in https://www.opengis.net/doc/IS/tms/2.0[OGC 17-083r4]) of the map representation.

.Example requests:
```
.../map/tiles
.../map/tiles/WorldCRS84Quad
.../map/tiles/WorldCRS84Quad/0/0/0
```

NOTE: Despite the use of `.../map/tiles` path templates in these examples which may become common in implementations of _OGC API - Maps_,
these exact paths are only examples and are not required by _OGC API - Tiles_ or by this _Maps API_ Standard.
Other paths are possible provided they are correctly described in the API description of the Web API and the links between resources.

NOTE: The "Custom Projection CRS" requirements class is not included in this sub-section because its primary focus is not defining resources, but the Custom Projection requirements class also specifies a /projectionsAndDatums resource listing values available for the parameters it defines.

=== Requirements classes defining parameters

These requirements classes of the _Maps API_ define parameters that can be used together with any map resource.

NOTE: In the effort to make OGC API Standards more consistent, some parts of these requirements classes are expected to be imported by a future part of  OGC API - Common or be registered in the building blocks registry. A future revision of OGC API - Maps could reference them and ensure consistency with the relevant common requirements.

*<<rc_background>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/background)

The _background_ requirements class defines how to request a particular background color (`bgcolor`) and to specify whether areas of the map with no data are `transparent`.

.Example requests:
```
.../map?bgcolor=0x001122
.../map?transparent=false
```

*<<rc_collections-selection>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/collections-selection)

The _collection selection_ requirements class defines how to list specific geospatial data collection resources from which to retrieve maps.

.Example request:
```
.../map?collections=buildings,roads,...
```

*<<rc_scaling>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/scaling)
The _scaling_ requirements class defines how to retrieve a resampled map. This is done by specifying a `width` and/or `height` parameter (in pixels),
or a `scale-denominator` parameter.

.Example requests:
```
.../map?width=1024&height=512
.../map?scale-denominator=20000
```

NOTE: When implementing both this _scaling_ requirements class and the _spatial subsetting_ requirements class,
the `width` and `height` can only be used for specifying the scale when a `bbox` or `subset` is also used for spatial subsetting,
as otherwise they take on a subsetting role. When neither `bbox` nor `subset` is used for spatial subsetting,
the `scale-denominator` parameter must be used to specify the scale.

*<<rc_display-resolution>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/display-resolution)
The _display resolution_ requirements class defines how to specify the resolution of the display (the size of a pixel in millimeters) using the
`mm-per-pixel` parameter at which the map will be visualized so as to properly interpret scale denominators and apply scale-dependent symbology rules.

.Example request:
```
.../map?mm-per-pixel=0.14
```

*<<rc_spatial-subsetting>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/spatial-subsetting)
The _spatial subsetting_ requirements class defines how to retrieve a spatial subset of a map using either a `bbox` or `subset` parameter.

.Example subsetting requests using bounding box:
```
.../map?bbox=120,30,180,90
.../map?bbox-crs=[EPSG:3857]&bbox=500000,430000,1000000,1000000
```

.Example subsetting requests using subset:
```
.../map?subset=Lat(30:90),Lon(120:180)
.../map?subset-crs=[EPSG:3857]&subset=X(500000:1000000),Y(430000:1000000)
```

This class also specifies how to retrieve a subset of a map using a `center` parameter, together with `width` and `height` parameters.

NOTE: When implementing both this _spatial subsetting_ requirements class and the _scaling_ requirements class,
the `width` and `height` can only be used for specifying the scale when a `bbox` or `subset` is also used for spatial subsetting,
as otherwise they take on a subsetting role. When neither `bbox` nor `subset` is used for spatial subsetting,
the `scale-denominator` parameter must be used to specify the scale.

.Example subsetting requests using center point and dimensions:
```
.../map?center=-120,60&width=1024&height=512
.../map?center-crs=[EPSG:3857]&center=750000,70000&width=1024&height=512
```

*<<rc_datetime>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/datetime)
The _temporal subsetting_ requirements class specifies how to request a temporal subset of the data using the `datetime` parameter,
or the `subset` parameter for the `time` dimension.

.Example requests:
```
.../map?datetime=2018-02-12T23:20:52Z
.../map?subset=time("2018-02-12T23:20:52Z")
```

*<<rc_general-subsetting>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/general-subsetting)
The _general subsetting_ requirements class specifies how to request a subset of dimensions of the data besides the spatial and temporal dimensions
using the `subset` parameter.
This parameter also implies adopting a consistent way to describe all dimensions of the data in the collection's extent description.

.Example request:
```
.../map?subset=atm_pressure_hpa(500)
```

*<<rc_crs>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/crs)
The _CRS by reference_ requirements class defines how to specify the output CRS of the map by referencing a URI (or CURIE) for a CRS definition.

.Example request:
```
.../map?crs=[EPSG:3031]
```

*<<rc_orientation>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/orientation)
The _orientation_ requirements class defines how to specify an angle (expressed in degrees) for re-orienting how the map is displayed (`orientation`).

.Example orientation request:
```
.../map?orientation=40
```

*<<rc_projection>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/projection)
The _custom projection CRS_ requirements class defines how to specify a custom CRS through a projection, including the coordinate operation method (`crs-proj-method`)
and associated parameters (`crs-proj-params`), as well as a datum (`crs-datum`).
This class also defines a `crs-proj-center` parameter for facilitating the selection of the most likely parameters to center the projection on an area of interest.

.Examples of an orthographic projection request:
```
.../map?
   crs-proj-method=[epsg-method:9840]&
   crs-proj-center=Lat(40),Lon(-120)
```

.Examples of a Lambert Conic Conformal projection with two standard parallels request:
```
.../map?
   crs-proj-method=[epsg-method:9802]&
   crs-proj-params=[epsg-parameter:8823](40),[epsg-parameter:8824](90)&
   crs-datum=[epsg-datum:6230]
```

NOTE: This "Custom Projection CRS" requirements class also defines a `/projectionsAndDatums` resource listing values available for the parameters it defines.

=== Requirements classes defining origins

*<<rc_collection-map>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/collection-map)

The _collection map_ requirements class specifies how to retrieve maps from a specific geospatial data resource.

.Example request:
```
/collections/buildings/map
```

*<<rc_dataset-map>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/dataset-map)

The _dataset map_ requirements class specifies how to retrieve maps for a whole dataset potentially made up of multiple geospatial data resources.
Any Web API implementing this requirements class must support *dataset* maps following this _OGC API - Maps Part 1: Core_ Standard.
Dataset maps may combine content from multiple geospatial resources, regardless of whether those are available separately (as maps or otherwise).

.Example request:
```
/map
```

*<<rc_styled-map>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/styled-map)

The _styled map_ requirements class specifies how to retrieve maps for a styled resource.

.Example request:
```
.../styles/night/map
```

=== Requirements classes defining representations
*<<rc_data_encodings>>*

The _Maps API_ Standard does not mandate a specific encoding or format for representing maps.
Requirements classes are provided for the following common map formats.

*<<rc_png,PNG>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/png)

_Media type_: `image/png`

*<<rc_jpeg,JPEG>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/jpeg)

_Media type_: `image/jpeg`

*<<rc_jpegxl,JPEG XL>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/jpegxl)

_Media type_: `image/jxl`

*<<rc_tiff,TIFF>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/tiff)

_Media type_: `image/tiff`

*<<rc_svg,SVG>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/svg)

_Media type_: `image/svg+xml`

*<<rc_html,HTML>>* (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/html)

_Media type_: `text/html`

The Standard remains flexible and extensible for using other formats that users and providers might need
through HTTP content negotiation.

That said, this Standard includes recommendations to support, where practical, HTML.

*<<rc_api_operations>>*  (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/api-operations)

The _API Operations_ requirements class specifies requirements to fully describe the _Maps API_ operations and use specific operation identifier suffixes when providing an API definition.
This requirements class is intended to be used in conjunction with other conformance classes for a specific API definition language and/or version, such as the OpenAPI 3.0 requirement class defined in
_OGC API - Common - Part 1: Core_, or another eventual requirement class for OpenAPI 3.1.

*<<rc_api_cors>>*  (https://www.opengis.net/spec/ogcapi-maps-1/1.0/req/cors)

The _CORS_ requirements class specifies a requirement to implement CORS to support JavaScript clients (e.g. Web Browser applications) from a domain different from the OGC API - Maps endpoint.

All requirements classes and conformance classes described in this Standard are owned by the standard(s) identified.

=== Summary of conformance URIs

[#table_conformance_urls,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="30,70",options="header"]
|===
| Corresponding requirements class | Conformance class URI
| <<rc_core>>                  | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core
| <<rc_tilesets>>              | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/tilesets
| <<rc_background>>            | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/background
| <<rc_collections-selection>> | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collections-selection
| <<rc_scaling>>               | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/scaling
| <<rc_display-resolution>>    | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/display-resolution
| <<rc_spatial-subsetting>>    | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/spatial-subsetting
| <<rc_datetime>>              | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/datetime
| <<rc_general-subsetting>>    | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/general-subsetting
| <<rc_crs>>                   | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/crs
| <<rc_orientation>>           | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/orientation
| <<rc_projection>>            | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/projection
| <<rc_collection-map>>        | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collection-map
| <<rc_dataset-map>>           | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/dataset-map
| <<rc_styled-map>>            | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/styled-map
| <<rc_png,PNG>>               | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/png
| <<rc_jpeg,JPEG>>             | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/jpeg
| <<rc_jpegxl,JPEG XL>>        | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/jpegxl
| <<rc_tiff,TIFF>>             | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/tiff
| <<rc_svg,SVG>>               | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/svg
| <<rc_html,HTML>>             | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/html
| <<rc_api_operations>>        | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/api-operations
| <<rc_cors,CORS>>             | https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/cors
|===
