== Conventions
This sections provides details and examples for any conventions used in the document. Examples of conventions are symbols, abbreviations, use of XML schema, or special notes regarding how to read the document.

=== Identifiers

The normative provisions in this standard are denoted by the URI `http://www.opengis.net/spec/ogcapi-maps-1/1.0`.

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== Link relations

To express relationships between resources, <<rfc8288,RFC 8288 (Web Linking)>> is used.

The following <<link-relations,registered link relation types [IANA]>> may be used by implementation of this document.

* **collection**: The target IRI points to a resource which represents the collection resource for the context IRI.

* **describedby**: Refers to a resource providing information about the link's context.

* **next**: Indicates that the link's context is a part of a series, and that the next in the series is the link target.

* **license**: Refers to a license associated with this context.

* **prev**: Indicates that the link's context is a part of a series, and that the previous in the series is the link target.

* **self**: Conveys an identifier for the link's context.

* **service-desc**: Identifies service description for the context that is primarily intended for consumption by machines.

* **service-doc**: Identifies service documentation for the context that is primarily intended for human consumption.

In addition the following link relation types may be used by implementation of this document for which no applicable registered link relation type could be identified in IANA.

* **items**: Refers to a resource that is comprised of members of the collection represented by the link's context.

* **conformance**: Refers to a resource that identifies the specifications that the link's context conforms to.

In addition the following link relation types this document proposes link relations for which no applicable registered link relation type could be identified in IANA.

* **map**: Refers to a resource that is map representation of another geospatial resource (e.g. a collection)

Each resource representation includes an array of links. Implementations are free to add additional links for all resources provided by the API.
