[[rc_general-subsetting]]
== Requirements Class "General Subsetting"

=== Overview

[[maps-general-subsetting-overview]]

include::requirements/requirements_class_general_subsetting.adoc[]

The General Subsetting requirements class defines the way a subset of the map resource in additional dimensions beyond spatial and temporal can be specified using the `subset` parameter.
This functionality is defined as common building blocks shared with other OGC API Standards.

=== Describing the extent of the additional dimensions

When implementing the General Subsetting requirements class, additional dimensions included in an extent description must use a uniform approach to describe the lower and upper bounds of those dimensions based on the `intervals` property. An example is found in a OGC API collection description response described in OGC API - Common: Part 2 and follows the JSON schema in https://github.com/opengeospatial/ogcapi-maps/blob/master/openapi/schemas/common-geodata/collectionInfo.yaml. This is the same as with the temporal dimension.

include::requirements/general-subsetting/REQ_uniform-additional-dimensions.adoc[]

NOTE: The `subset-crs` mentioned in <<rc_spatial-subsetting, Spatial subsetting>> can only be used in combination with a spatial `subset`.

=== `subset` query parameter

The `subset` parameter can be specified as an interval between lower and higher bound values or as a single value. An example of an interval is "between 500.0 and 1013.0 hPa" `subset=pressure(500:1013)`. An example of single value is "750 hPa" `subset=pressure(750)`.
The dimensions that can be used within the value specified for this parameter are the axis abbreviations specified in the CRS definition. 
All additional dimensions listed in the extent as valid dimensions to be used with the subset parameter must be supported. 

include::requirements/general-subsetting/REQ_subset-definition.adoc[]

=== Response
A successful GET response is described in the Maps API core class (https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core).

=== Error conditions

A general summary of the HTTP status codes can be found in the https://docs.ogc.org/is/19-072/19-072.html[OGC API – Common – Part 1: Core] Standard.

If the parameter value for the additional dimensions is outside the domain of the collections, the status code of the response will be `400`.

Otherwise, if the request returns no data (e.g., in combination with other types of subsetting), the status code of the response will be `204` or `404`.
