== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

This document also uses terms defined in the OGC Standard for Modular specifications (https://portal.opengeospatial.org/files/?artifact_id=34762[OGC 08-131r3]), also known as the 'ModSpec'. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

For the purposes of this document, the following additional terms and definitions apply.

=== *coordinate reference system*
coordinate system that is related to the real world by a datum (source: ISO 19111)


=== *coordinate system*
set of mathematical rules for specifying how coordinates are to be assigned to points (source: ISO 19111)


=== *geographic information*
information concerning phenomena implicitly or explicitly associated with a location relative to the Earth (source: ISO 19101)

=== *height*

1. vertical elevation of an object in the real world above a reference point (height above the reference ellipsoid for geographic CRS such as [OGC:CRS84h] and [EPSG:4979]).

2. size in pixels of a viewport along its vertical axis

NOTE: Both the _spatial subsetting_ and _scaling_ requirements classes make use of the `height` query parameter.
In both cases, the parameter refers to the height of the image in pixels, but the effect of specifying a fixed value for the parameter
is different in each case (selecting the portion of the map to return in the image vs. resampling the map to the requested image size).

=== *map*
portrayal of geographic information as a digital representation suitable for display on a rendering device (adapted from OGC 06-042)

=== *map background*
areas of the map having no data to represent. They are commonly left transparent or filled with a background color

=== *portrayal*
presentation of information to humans (source: ISO 19117)

=== *rendering device*
medium or apparatus on which the map being retrieved will be displayed, whether temporarily (e.g., computer screen) or permanently (e.g., paper).

=== *scale*
ratio between the size of a map shown in the rendering device (commonly in expressed in mm or inches) and the equivalent geographic bounding box of a map in the reality (commonly in expressed in meters or miles). Commonly, the ratio is expressed as a fraction, where 1 unit in the rendering device is equivalent to `n` units in the reality (in the same units of measure). In this case, `n` is called scale denominator.

=== *viewport*
portion of a rendering device where information is being visualized

NOTE: For the purpose of this document, the viewport refers to the portion of the map resource response, such as a digital image, where the actual geospatial content of the map is rendered.
It excludes any layout element such as margin, title or legend.
For a two dimensional viewport, its dimensions are named horizontal and vertical, corresponding to the width and height dimensions of the viewport, respectively.

=== *width*

size of in pixels of a viewport along its horizontal axis

NOTE: Both the _spatial subsetting_ and _scaling_ requirements classes make use of the `width` query parameter.
In both cases, the parameter refers to the width of the viewport in pixels, but the effect of specifying a fixed value for the parameter
is different in each case (selecting the portion of the map to return in the image vs. resampling the map to the requested image size).

=== *Web API*
An Application Programming Interface (API) using an architectural style that is founded on the technologies of the Web (source: OGC 17-069r3)

NOTE: See https://www.w3.org/TR/dwbp/#accessAPIs[Best Practice 24: Use Web Standards as the foundation of APIs] (W3C Data on the Web Best Practices) for more detail.
