[[rc_oas30]]
== Requirements Class "OpenAPI Specification 3.0" API definition

=== Overview

include::requirements/requirements_class_oas30.adoc[]

This requirements class defines particularities of providing a definition of a Web API implementing this standard using OpenAPI Specification version 3.0.

=== Web API OpenAPI description

The OpenAPI definition provides a description of the complete list of API resources. Reading this description, an application would have the full picture of the resources that the API provides, how to retrieve them, and what responses are expected for successful and unsuccessful requests. Without this API description an application would be forced to traverse all links, starting with the landing page, to get an equivalent full list of resources.

The (_oas30_) requirement class from _OGC API - Common - Part 1: Core_ provides many details on general requirements that this requirements class adopts by dependency. In addition, extra requirements are provided. Also, the _OGC API - Common_ requirements class provides details on how to request an API definition.

==== Response

===== Completeness
The OpenAPI definition resulting as a response of this request need to take into consideration the relevant resources specified in this standard.

include::requirements/oas30/REQ_completeness.adoc[]

===== Reusable API components

Reusable components for creating OpenAPI definitions for implementations of this OGC API can be found in http://schemas.opengis.net/ogcapi/maps/part1/1.0/openapi

NOTE: While this specification is in draft status, the components are available from https://github.com/opengeospatial/ogcapi-maps/tree/master/openapi .

A server implementations of this OGC API can use the content in the openapi folder to generate a response for the openapi description. The _ogcapi-maps-1.yaml_ includes paths and components. An implementation should only include the paths that are implemented and remove the references to the rest. The components part includes parameters, responses and schemas that can be reused as-is. The `api` folder contains JSON files that are templates with enumerated values for collections, styles and tile matrix sets. A particular implementation of this API should enumerate the actual resources exposed by the API in the same way. The server can select to dynamically implement responses to /api/* (where * is replaced by all-collections, styles,... ) or hardcode the /api/* files with the actual list of resource identifiers in the enumerations.

To improve performance, the whole content of this folder can be bundled in a single document by executing a tool such as _swagger-cli_. This can be served for the _OGC API - Common - Part 1_ `service-desc` link from the landing page.

===== Path Operation Ids

The OpenAPI definition provides to a client application a set of paths that the client can use to interact with the API and get new resources. The OpenAPI description of each path provides a description of what parameters to use in the request and what to expect in the response. However, this standard is not proposing a fixed set of paths so there is an issue identifying the requirements classes pertaining to each path in an API instance. In other words, the OpenAPI description alone does not provide enough information by itself and there is a need to identify the requirements classes pertaining to a resource (a path) and complete the information necessary for the client to implement the necessary logic to generate the request and understand the response. This standard proposes a suffix mechanism to be applied to the `operationId` property of the path to list the requirement classes pertaining to each path. Each path should have a unique operationId suffix, so it is expected that the OpenAPI instance provides a prefix to the proposed suffixes that make each operationId unique.

include::requirements/oas30/REQ_operation-id.adoc[]

[#openapi-operation-id-suffixes,reftext='{table-caption} {counter:table-num}']
.OpenAPI operationId suffixes
[width = "100%",options="header",cols="12%,8%,15%,53%"]
|===
|Origin          |Styled   |Resource       |_operationId_ suffixes^1^
|_root_^5^       |         |Projections    |`getCustomCRSProjections`
4+|_With the origins described in this document_
|DataSet^5^      |         |Map^8^         |`.dataset.getMap`
|DataSet^5^      |         |TileSetsList^4^|`.dataset.map.getTileSetsList`
|DataSet^5^      |         |TileSet^3^     |`.dataset.map.getTileSet`
|DataSet^5^      |         |Tile^2^        |`.dataset.map.getTile`
|DataSet^5^      |Styled^7^|Map^8^         |`.dataset.style.getMap`
|DataSet^5^      |Styled^7^|TileSetsList^4^|`.dataset.style.map.getTileSetsList`
|DataSet^5^      |Styled^7^|TileSet^3^     |`.dataset.style.map.getTileSet`
|DataSet^5^      |Styled^7^|Tile^2^        |`.dataset.style.map.getTile`
|Collection^6^   |         |Map^8^         |`.collection.getMap`
|Collection^6^   |         |TileSetsList^4^|`.collection.map.getTileSetsList`
|Collection^6^   |         |TileSet^3^     |`.collection.map.getTileSet`
|Collection^6^   |         |Tile^2^        |`.collection.map.getTile`
|Collection^6^   |Styled^7^|Map^8^         |`.collection.style.getMap`
|Collection^6^   |Styled^7^|TileSetsList^4^|`.collection.style.map.getTileSetsList`
|Collection^6^   |Styled^7^|TileSet^3^     |`.collection.style.map.getTileSet`
|Collection^6^   |Styled^7^|Tile^2^        |`.collection.style.map.getTile`
4+|_With other potential origins_
|_other_         |         |Map^8^         |`#.getMap`
|_other_         |         |TileSetsList^4^|`#.map.getTileSetsList`
|_other_         |         |TileSet^3^     |`#.map.getTileSet`
|_other_         |         |Tile^2^        |`#.map.getTile`
|_other_         |Styled^7^|Map^8^         |`#.style.getMap`
|_other_         |Styled^7^|TileSetsList^4^|`#.style.map.getTileSetsList`
|_other_         |Styled^7^|TileSet^3^     |`#.style.map.getTileSet`
|_other_         |Styled^7^|Tile^2^        |`#.style.map.getTile`
4+|^1^ '#' represents an optional _origin_ that could be defined in another relevant standard.

^2^ The _Tile_ resource is defined in the _OGC API - Tiles - Part 1: Core_ "Core" requirements class.

^3^ The _TileSet_ resource is defined in the _OGC API - Tiles - Part 1: Core_ "TileSet" requirements class.

^4^ The _TileSetsList_ resource is defined in the _OGC API - Tiles - Part 1: Core_ "TileSets List" requirements class.
Map tilesets are defined in the _Map Tilesets_ requirements class_ and depend on _OGC API - Tiles - Part 1: Core_.

^5^ The _DataSet_ origin is defined in requirements class "Dataset Maps" and depends on _OGC API - Common - Part 1: Core_.

^6^ The _Collection_ origin is defined in requirements class "Collection Maps" and depends on the _Collections_ requirements class defined in _OGC API - Common - Part 2: Geospatial data_

^7^ Styled tilesets rely on the ability to list styles defined in _OGC API - Styles_.

^8^ The _Map_ resource is defined in requirements class "Core".

|===
