[[rc_spatial-subsetting]]
== Requirement Class "Spatial subsetting"

=== Overview

[[maps-spatial-subsetting-overview]]

include::requirements/requirements_class_spatial-subsetting.adoc[]

The Maps API core requirements class defines the map resource.
The Maps API core also defines a minimum set of metadata that enables a client application to formulate a map request.
The Subsetting requirements class adds the ability to request an arbitrary 2D or 3D spatial subset of a map using either a bounding box specified using one of two equivalent syntaxes
(a `bbox` parameter similar to the one in WMS 1.3, as well as a `subset` parameter similar to WCS 2.1),
or as a center point as well as `width` and/or `height` parameters taking into account the scale and the display resolution.

How the third (vertical) spatial dimension is applied to filter the output is left to the implementation and may depend on the nature of the data being represented and/or the negotiated output format.
For example, the server could include features located within a vertical interval as part of a 2D map being rendered.
In a second example, the extent of a 3D perspective view or a 3D model output would include only the subset of the vertical dimension specified.
In a third example, a vertical profile could be returned for a single point or for a path across the other spatial dimensions.
In this last example, the subset mechanism would likely only be used to subset the vertical dimension, while another mechanism would be used to select an arbitrary path in the horizontal dimensions (this standard part does not specify how to provide a path in a map request).

[[maps-spatial-subsetting-crs]]
=== CRS for subsetting
In WMS 1.3 the CRS parameters had two purposes: Indicate the CRS of the data rendered in the map and the CRS of the coordinates of the `bbox` parameter.
In the Maps API Standard, these two objectives have been separated. This section defines the CRS parameters for subsetting.

In this document the CRS for subsetting can have 3 possible values:
* http://www.opengis.net/def/crs/OGC/1.3/CRS84
* `storageCrs` indicated in the collection description.
* the one indicated in the `crs` parameter (the one picked for the map response). This possibility is described in the <<rc_crs, "CRS" requirement class>>.

The CRS advertised in the collection's spatial extent is always in http://www.opengis.net/def/crs/OGC/1.3/CRS84 (for Earth centric data and as required by _OGC API - Features_). At least for _OGC API - Maps_ and _OGC API - Coverages_, a native CRS (also called storage CRS) is defined. The `Content-Crs:` header (see <<maps-core-overview>>) specifies the CRS used in the response to avoid confusion.

NOTE: There is no obligation to provide the maps in http://www.opengis.net/def/crs/OGC/1.3/CRS84.

NOTE: The collection or dataset description will contain a `storageCrs` property indicating the native CRS. If it is not present, then http://www.opengis.net/def/crs/OGC/1.3/CRS84 is assumed. This is specified in the _Collection Map_ and _Dataset Map_ requirements classes.

NOTE: Providing the extent of the collection or dataset in its native CRS (_storage CRS_) is also required, as specified in the _Collection Map_ and _Dataset Map_ requirements classes.

NOTE: A list of supported CRSs will be provided by the collection or dataset, as specified in the _Collection Map_ and _Dataset Map_ requirements classes. The first CRS should be the same as the native CRS (`storageCrs`).

==== Parameter `bbox-crs`

include::requirements/spatial-subsetting/REQ_bbox-crs-definition.adoc[]

==== Parameter `subset-crs`

include::requirements/spatial-subsetting/REQ_subset-crs-definition.adoc[]

==== Parameter `center-crs`

include::requirements/spatial-subsetting/REQ_center-crs-definition.adoc[]

NOTE: For clarification, the default CRS of the `bbox`, `center` and `subset` spatial subsetting parameters is `http://www.opengis.net/def/crs/OGC/1.3/CRS84` and the default output CRS of the map is its native (storage) CRS.

NOTE: The `center-crs`, `subset-crs` and `bbox-crs` are defined identically except they are affecting `center`, `subset` and `bbox` parameters respectively.

==== CURIE permission

include::recommendations/spatial-subsetting/PER_subset-crs-curie.adoc[]

=== Subsetting coordinates

==== Parameter `bbox`
The `bbox` parameter defines how to subset a map using a bounding box (in bbox-crs coordinates). The `bbox` parameter values are defined using the exterior edges of the pixels of the viewport defined by the width and height values. This is because individual pixels (including the ones in the four corners of the viewport) occupy an area on the ground. In other words, the relation of the bounding box to the map pixel matrix is that the bounding box goes around the "outside" of the pixels of the map rather than through the centers of the map's border pixels (as is often the case for coverages where cell values represent a point).

include::requirements/spatial-subsetting/REQ_bbox-definition.adoc[]

NOTE: The `bbox` uses the comma (",") as the separator between the coordinates. Additional white space will not be used to delimit list items. The comma character should not be escaped (IETF RFC 2396).

Example:
`bbox=-180,-90,180,90&bbox-crs=[OGC:CRS84]`

Example of a 3D bounding box:
`bbox=-180,-90,10000,180,90,12000&bbox-crs=[OGC:CRS84h]`

==== Parameter `subset`
The `subset` parameter is a common building block used to select a subset of a geospatial resource shared with other OGC API Standards. This can be specified as an interval between lower and higher bound values or as a single value. An example of an interval is "between 10.0 and 20.0 degrees of latitude" `subset=Lat(10:20)`. An example of single value is "150 meters above main sea level" `subset=h(150)`.
The dimensions that can be used within the value specified for this parameter are the axis abbreviations specified in the CRS definition.

The `subset` parameter is defined as follows:

include::requirements/spatial-subsetting/REQ_subset-definition.adoc[]

While the processing of the `subset` parameter is specific to the resource and operation for which it is applied, there is a general set of requirements which all implementations must address.

include::requirements/spatial-subsetting/REQ_subset-response.adoc[]

include::recommendations/spatial-subsetting/REC_subset-crs-axis-names.adoc[]

==== Parameter `center`, `width` and `height`

The `center` parameter defines the center point of the map in the `center-crs` coordinates from which the `width` and `height` parameters will define a subset,
taking into consideration the scale and display resolution of the map.

include::requirements/spatial-subsetting/REQ_center-definition.adoc[]

NOTE: This parameter use the comma (",") as the separator between the coordinates. Additional white space will not be used to delimit list items. The comma character should not be escaped (IETF RFC 2396).

include::requirements/spatial-subsetting/REQ_subsetting-width-height-definition.adoc[]

=== Response

A successful GET response is described in the Maps API core class (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core).

include::requirements/spatial-subsetting/REQ_map-success.adoc[]

Normally, the content partially outside the map bounding box will be clipped at the extent of the bounding box. This can be done efficiently when map subsets are in raster format (e.g., map tiles). However, maps containing features in vector format may not clip features that are partially outside to ensure continuity of features or for performance.

include::recommendations/spatial-subsetting/REC_map-outside-bounds.adoc[]

include::recommendations/spatial-subsetting/PER_map-outside-bounds.adoc[]

NOTE: As defined in the Maps API core requirements class, the `Content-Bbox:` and the `Content-Crs:` response headers report the actual bounding box of the data returned.

=== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the CRS in the parameter value `bbox-crs`, `subset-crs` or `center-crs` is not supported by the server for this resource, or the parameter value is out-of-range, the status code of the response will be `400`.
If the map is not provided due to lack of data in the area, the status code of the response will be `204` or `404`.
