[[rc_datetime]]
== Requirement Class "Date and Time"

=== Overview

[[maps-datetime-overview]]

include::requirements/requirements_class_datetime.adoc[]

This requirements class defines the way date and time can be used as a parameter to filter the content in the map resource. This conformance class is importing most of the functionality from OGC API - Commons.

=== Describing the temporal extent

Depending on the type of resource, the way the temporal extent and the resolution of the datetime values available for the client to request are described may be different:

* For Geodata maps, the collection description should specify the temporal extent of the resources. Maps can be requested inside this extent. If the extent is specified in a way that instant values are provided (e.g. by listing them or by including a resolution) then it be possible to request maps for these instants.
* For Dataset maps, the landingPage could specify the temporal extent of the dataset. Maps can be requested inside this extent.

=== `datetime` query parameter request and response

The `datetime` parameter is a common building block that is shared with other OGC API Standards.

In the context of this requirements class, the `datetime` parameter selects a time instant or interval of the resource for which a map is requested.

The `datetime` parameter is defined as follows:

include::requirements/datetime/REQ_datetime-definition.adoc[]

While the processing of the `datetime` parameter is specific to the resource and operation for which it is applied, there is a general set of requirements which all implementations must address.

include::requirements/datetime/REQ_datetime-response.adoc[]

"Intersects" means that the time (instant or period) specified in the parameter `datetime` includes a timestamp that is part of the temporal geometry of the resource (again, a time instant or period). For time periods this includes the start and end time.

[width="90%",cols="2,6a"]
|====
| Note | ISO 8601-2 distinguishes open start/end timestamps (double-dot) and unknown start/end timestamps (empty string). For queries, an unknown start/end has the same effect as an open start/end.
|====

.A date-time
=================
February 12, 2018, 23:20:52 UTC:

`datetime=2018-02-12T23%3A20%3A52Z`
=================

For resources with a temporal property that is a timestamp (like `lastUpdate`), a date-time value would match all resources where the temporal property is identical.

For resources with a temporal property that is a date or a time interval, a date-time value would match all resources where the timestamp is on that day or within the time interval.

.Intervals
=================
February 12, 2018, 00:00:00 UTC to March 18, 2018, 12:31:12 UTC:

`datetime=2018-02-12T00%3A00%3A00Z%2F2018-03-18T12%3A31%3A12Z`

February 12, 2018, 00:00:00 UTC or later:

`datetime=2018-02-12T00%3A00%3A00Z%2F..`

March 18, 2018, 12:31:12 UTC or earlier:

`datetime=..%2F2018-03-18T12%3A31%3A12Z`
=================

A template for the definition of the parameter in YAML according to OpenAPI 3.0 is available at link:http://beta.schemas.opengis.net/ogcapi/common/part2/0.1/collections/openapi/parameters/datetime.yaml[datetime.yaml].



=== `subset=datetime` query parameter request and response

The `subset` parameter is a common building block that is shared with other OGC API Standards.
The dimensions that can be included within the value of this parameter are defined by the axis name of the generic datetime in an additional requirement, a permission and a recommendation at the end of this subsection.

The `subset` parameter can be used to select a temporal subset of a geospatial resource, and is defined as follows:

include::requirements/datetime/REQ_subset-definition.adoc[]

While the processing of the `subset` parameter is specific to the resource and operation for which it is applied, there is a general set of requirements which all implementations must address.

include::requirements/datetime/REQ_subset-response.adoc[]

include::requirements/datetime/REQ_datetime-axis.adoc[]

=== Actual date & time response header

include::recommendations/datetime/REC_actual-datetime.adoc[]

=== Closest date & time permission

include::recommendations/datetime/PER_datetime-axis.adoc[]

=== Response
A successful GET response is described in the core class (http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core).

include::requirements/datetime/REQ_map-success.adoc[]

=== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the parameter value for `datetime` is not compatible with what the collections can offer, the status code of the response will be `404`.
