[[rc_collections-selection]]

== Requirements Class "Collection Selection"

=== Overview

include::requirements/requirements_class_collections-selection.adoc[]

[[rm_collections-selection]]

In a deployed Web API incorporating elements of the OGC Maps API Standard that provides access to a complex dataset formed by several geospatial data resources, selecting specific sub-resources of interest when requesting data from this dataset can be useful. The Collection Selection requirements class defines how to include a query parameter when requesting a resource (e.g., dataset tiles) to specify which geospatial data resources (e.g., collections) should be used to generate the response. 

This requirements class is particularly useful in conjunction with the <<rc_dataset-map>> requirements class. However, sub-components of other resource types could be selected using this requirements class. A requirements class equivalent to this one is included in _OGC API - Tiles_.

=== Operation

By default, the geospatial data resources included in the dataset maps responses are unspecified but should represent the dataset as a whole (but not necessarily the entire extent of the dataset content).
This class adds a mechanism to select the geospatial data resources to be used to generate the derived resources (e.g., maps or map tiles).
In practice this enables the capability to generate resources involving more than one geospatial data sub-resource.

[[req_collections-selection_parameter-collections]]
==== Parameter `collections`

include::requirements/collections-selection/REQ_collections-parameter.adoc[]

When this parameter refers to more than one geospatial data resource, this parameter will use the
comma (",") as the separator between the resource identifiers in the list. Additional white space will not be used to delimit list items. If a geospatial data resource identifier includes a space or comma, it shall be escaped using the URL encoding rules (IETF RFC 2396).

[[per_collections-selection_valid-collections]]
include::recommendations/collections-selection/PER_collections-selection.adoc[]

An example request is:

[%unnumbered%]
[source]
----
www.example.com/map?collections=buildings,roads
----

[[req_collections-selection-response]]
==== Response
A successful GET response is described in the core class (https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core)

include::requirements/collections-selection/REQ_collections-response.adoc[]

==== Error conditions

If the value of the parameter `collections` contains a resource id of URI that does not exist on the implementation instance of the Maps API or too many collections are requested, the status code of the response is 400.

If the value of the parameter `collections` has a wrong format or combines one of more geospatial data resources that are not compatible (e.g., they do not have a compatible value specified by other parameters in the request), the status code of the response is 400.

=== Service Metadata

The https://docs.ogc.org/is/19-072/19-072.html[OGC API - Common - Part 1: Core] Standard describes a mechanism to expose service-metadata for the API. See: https://docs.ogc.org/is/19-072/19-072.html#service-metadata-examples

include::recommendations/collections-selection/REC_maxcollections.adoc[]
