== Conformance

This standard defines **20** requirements conformance classes.

The standardization targets of all conformance classes are "Web APIs".

The requirements classes are:

=== Requirements classes defining resources

*<<rc_core>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core)

The Core specifies requirements that all Web APIs have to implement if they are claiming to support maps from a geospatial resource following this _OGC API - Maps Part 1: Core_ standard.
It defines how to retrieve an arbitrary map by building a URI.

.Example request
```
.../map
```

*<<rc_tilesets>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/tilesets)

The _map tilesets_ conformance class defines a mechanism to describe a tileset list and obtain a list of tilesets supported by the map and eventually tiles representing the map

.Example requests
```
.../map/tiles
.../map/tiles/WorldCRS84Quad
.../map/tiles/WorldCRS84Quad/0/0/0
```

=== Requirements classes defining parameters

These conformance classes define Web API parameters that can be used together with any map resource, such as a dataset map or collection map at `.../map`.

*<<rc_background>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/background)

The _background_ conformance class allows requesting a particular background color (`bgcolor`) and whether the areas of the map with no data are `transparent`.

.Example request
```
.../map?bgcolor=0x001122&transparent=true
```

*<<rc_collections-selection>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/collections-selection)

The _collection selection_ conformance class allows to list specific geospatial data collection resources from which to retrieve maps.

.Example request
```
.../map?collections=buildings,roads,...
```

*<<rc_scaling>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/scaling)
The _scaling_ conformance class allows to retrieve a resampled map, by specifying a `width` and/or `height` parameter (in pixels),
or a `scale-demoninator` parameter.

.Example requests
```
.../map?width=1024&height=512
.../map?scale-denominator=20000
```

NOTE: Combining this conformance class with the _spatial subsetting by center point_ conformance class, only the `scale-denominator` parameter is supported to specify the scale
(not `width` and `height`, which take on a subsetting role).

*<<rc_display-resolution>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/display-resolution)
The _display resolution_ conformance class allows the specification of the resolution of the display (the size of a pixel in millimeters) using the
`mm-per-pixel` parameter on which the map will be visualized so as to properly interpret scale denominators and apply scale-dependent symbology rules.

.Example requests
```
.../map?mm-per-pixel=0.14
```

*<<rc_spatial-subsetting>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/spatial-subsetting)
The _spatial subsetting_ conformance class allows to retrieve a spatial subset of a map using either a `bbox` or `subset` parameter.

.Example subsetting requests using bounding box
```
.../map?bbox=120,30,180,90
.../map?bbox-crs=[EPSG:3857]&bbox=500000,430000,1000000,1000000
```

.Example subsetting requests using subset
```
.../map?subset=Lat(30:90),Lon(120:180)
.../map?subset-crs=[EPSG:3857]&subset=X(500000:1000000),Y(430000:1000000)
```

It also allows to retrieve a subset of a map using a `center` parameter, together with `width` and `height` parameters.

NOTE: When combining the `center` parameter with the _scaling_ conformance class, only the scaling `scale-denominator` parameter is supported to specify
the scale (not `width` and `height`, which take on a subsetting role).

.Example subsetting requests using center point and dimensions
```
.../map?center=-120,60&width=1024&height=512
.../map?center-crs=[EPSG:3857]&center=750000,70000&width=1024&height=512
```

*<<rc_datetime>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/datetime)
The _temporal subsetting_ conformance class allows to request a temporal subset of the data using the `datetime` parameter,
or the `subset` parameter for the `time` dimension.

.Example requests
```
.../map?datetime=2018-02-12T23:20:52Z
.../map?subset=time('2018-02-12T23:20:52Z')
```

*<<rc_general-subsetting>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/general-subsetting)
The _general subsetting_ conformance class allows to request a subset of dimensions of the data besides the spatial and temporal dimensions
using the `subset` parameter, and based on adopting a consistent way to describe all dimensions of the data in the collection's extent description.

.Example request
```
.../map?subset=atm_pressure_hpa(500)
```

*<<rc_crs>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/crs)
The _CRS by reference_ conformance class allows to specify the output CRS of the map by referencing a URI (or CURIE) for a CRS definition.

.Example request
```
.../map?crs=[EPSG:3031]
```

*<<rc_projection>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/projection)
The _projection_ conformance class allows to specify a custom CRS through a projection, including the coordinate operation method (`crs-proj-method`)
and associated parameters (`crs-proj-params`), as well as a datum (`crs-datum`) and orientation (`orientation`).
It also defines a `crs-proj-center` parameter facilitating the selection of the most likely parameters to center the projection on an area of interest.
The `orientation` parameter can also be used with the `crs` parameter, if the CRS by reference conformance class is also supported.

.Example orthographic projection request
```
.../map?
   crs-proj-method=[epsg-method:9840]&
   crs-proj-center=Lat(40),Lon(-120)&
   orientation=40
```

.Example Lambert Conic Conformal projection with two standard parallels
```
.../map?
   crs-proj-method=[epsg-method:9802]&
   crs-proj-params=[epsg-parameter:8823](40),[epsg-parameter:8824](90)&
   crs-datum=[epsg-datum:6230]&
   orientation=40
```

=== Requirements classes defining origins

*<<rc_collection-map>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/collection-map)

The _collection map_ conformance class allows retrieving maps from a specific geospatial data resource.

.Example request
```
/collections/buildings/map
```

*<<rc_dataset-map>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/dataset-map)

The _dataset map_ conformance class allows retrieving maps for a whole dataset potentially made up of multiple geospatial data resources.
All Web APIs have to implement this conformance class if they are claiming to support *dataset* maps following this _OGC API - Maps Part 1: Core_ standard.
Dataset maps may combine content from multiple geospatial resources, regardless of whether those are available separately (as maps or otherwise).

.Example request
```
/map
```

*<<rc_styled-map>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/styled-map)

The _styled map_ conformance class allows retrieving maps for a styled resource.

.Example request
```
.../styles/night/map
```

=== Requirements classes defining representations
*<<rc_data_encodings>>*

This standard does not mandate a specific encoding or format for representing maps and remains flexible and extensible to other formats that users and providers might need.
However, requirements classes are provided for the following common map formats:

*<<rc_png,PNG>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/png)

.Media type
```
image/png
```

*<<rc_jpeg,JPEG>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/jpeg)

.Media type
```
image/jpeg
```

*<<rc_tiff,TIFF>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/tiff)

.Media type
```
image/tiff
```

*<<rc_svg,SVG>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/svg)

.Media type
```
image/svg+xml
```

*<<rc_html,HTML>>* (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/html)

.Media type
```
text/html
```

*<<rc_oas30>>*  (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/oas30)

The _OpenAPI Specification 3.0_ conformance class specifies requirements for an OpenAPI 3.0 definition in addition to those defined in _OGC API - Common - Part 1: Core_.

All these conformance classes act as building blocks that should be implemented in combination with other more fundamental conformance classes that provide support for Web API discovery, conformity and Web API formal definition (e.g., OpenAPI). Possible alternatives for these fundamental conformance classes are _OGC API - Common Part 1: Core_, _OGC API - Features Part 1: Core_ or any other non-OGC classes that provide this functionality.

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.

NOTE: Despite the fact that full paths and full path templates in the previous tables are used in many implementations of the OGC API - Maps, these exact paths are ONLY examples and are NOT required by this standard. Other paths are possible if correctly described in by the Web API definition document and the links between resources.

That said, this draft specification includes recommendations to support, where practical, HTML.

The draft specification is intended to be a minimal useful API for fine-grained read-access to maps. Additional capabilities may be specified in future parts of the OGC API - Maps series or as vendor-specific extensions.

=== Declaration of conformance

Conformance with this standard shall be checked using all the relevant tests specified in Annex A (normative) of this document if the respective conformance URLs listed in <<table_conformance_urls>> is present in the conformance response. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

[#table_conformance_urls,reftext='{table-caption} {counter:table-num}']
.Conformance class URIs
[cols="30,70",options="header"]
|===
| Conformance class | URI
| <<rc_core>>                  | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core
| <<rc_tilesets>>              | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/tilesets
| <<rc_background>>            | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/background
| <<rc_collections-selection>> | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collections-selection
| <<rc_scaling>>               | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/scaling
| <<rc_display-resolution>>    | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/display-resolution
| <<rc_spatial-subsetting>>    | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/spatial-subsetting
| <<rc_datetime>>              | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/datetime
| <<rc_general-subsetting>>    | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/general-subsetting
| <<rc_crs>>                   | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/crs
| <<rc_projection>>            | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/projection
| <<rc_collection-map>>        | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/collection-map
| <<rc_dataset-map>>           | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/dataset-map
| <<rc_styled-map>>            | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/styled-map
| <<rc_png,PNG>>               | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/png
| <<rc_jpeg,JPEG>>             | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/jpeg
| <<rc_tiff,TIFF>>             | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/tiff
| <<rc_svg,SVG>>               | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/svg
| <<rc_html,HTML>>             | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/png
| <<rc_oas30>>                 | http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/oas30
|===
