[[rc_projection]]
== Requirement Class "Custom Projection CRS"

[[maps-projection-overview]]
=== Overview

include::requirements/requirements_class_projection.adoc[]

This requirements class defines the ability for clients to specify a custom projection CRS based on parameters defining a projection operation method, values for corresponding parameters, a datum, as well as an orientation.
It also provides a parameter facilitating the task of selecting a projection center across different projections, for which the relevant latitude and longitude parameters differ.
Angles are specified in degrees, whereas identifiers for methods, parameters and datums can be specified as URIs or safe CURIEs.

=== Operation

==== Parameter `crs-proj-method`
The operation method refers mainly to the equations that relates geographic coordinates to projected coordinates and vice-versa. 

include::requirements/projection/REQ_crs-proj-method.adoc[]

==== Parameter `crs-proj-params`
The operation method may have some parameters to set such as the standard parallel. This query parameter allows to set those values. In some simple cases this query parameter might not be necessary and clients can consider using `crs-proj-center` instead.

include::requirements/projection/REQ_crs-proj-params.adoc[]

==== Parameter `crs-proj-center`

In order to facilitate the task of centering a custom projection on the area of interest, with parameters varying greatly between projections, the `crs-proj-center` parameter automatically sets the most appropriate parameters
for the specified center latitude and longitude.

include::requirements/projection/REQ_crs-proj-center-definition.adoc[]

NOTE: For some projections where there is not a clear single center latitude parameter, such as those with multiple standard parallels, clients should use `crs-proj-params` to unambiguously set each parameter instead.

==== Parameter `crs-datum`

include::requirements/projection/REQ_crs-datum.adoc[]

==== Parameter `orientation`

include::requirements/projection/REQ_orientation.adoc[]

==== Response

A successful GET response is described in the core class (http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core).

==== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the parameter value for the parameters is not one of the supported for the collections, the status code of the response will be `404`.
