== Requirement Class "Map from more than one collection"

=== Overview

[[maps-collections-overview]]

include::requirements/maps/requirements_class_collections.adoc[]

In previous clauses maps that are produced form one and only one resource is discussed. This is achieved by concatenating the map path to a resource (e.g. a feature collection). This extension discusses the possibility of combining more than one resource to create a map. This is achieved by using by adding the map path to the root of the service.

=== Declaration of conformance classes

==== Response

The conformance page mainly consists of a list of links. OGC API - Common already requires some links.

include::requirements/maps/collections/REQ_conformance-success.adoc[]

In the conformance page (typically in JSON format) the links follow the link schema defined in the OGC API - Common. The following is an example fragment of the response of an OGC API - Maps conformance information page

[[ConformancePageMapsCollection]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core"
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/collections"
  ]
}
=================

=== Maps from more than one collection

==== Operation
include::requirements/maps/collections/REQ_mcs-op.adoc[]

==== Parameter styles
include::requirements/maps/collections/REQ_mcs-styles-definition.adoc[]

==== Parameter Collections
include::requirements/maps/collections/REQ_mcs-collections-definition.adoc[]

==== Response
To retrieve the map as a map or a tile another extension is needed. No requirements are provided here.
