[[rc_crs]]
== Requirements Class "Coordinate Reference System"

[[maps-crs-overview]]
=== Overview

include::requirements/requirements_class_crs.adoc[]

In WMS 1.3 the CRS parameters had two purposes: To indicate the CRS of the data rendered in the map and the CRS of the coordinates of the BBOX parameter. In the Maps API Standard, these two purposes have been separated. This section describes how to request a map in a specific CRS.

For _OGC API - Maps_ and _OGC API - Coverages_, a native CRS (also called a _storage CRS_) is defined. The `Content-Crs:` header (see <<maps-core-overview>>) specifies the CRS used in the response to avoid confusion.

=== Operation

The Maps API core requirements class defines how to retrieve a map. The CRS requirements class specifies parameters needed to retrieve a map in a particular output CRS.

==== Parameter `crs`
A successful GET response is described in the Maps API core class (https://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core).

include::requirements/crs/REQ_crs-definition.adoc[]

See how to determine the native (storage) CRS for the collection and the dataset in <<rc_collection-map>> and <<rc_dataset-map>> respectively.

NOTE: The default CRS of the BBOX is https://www.opengis.net/def/crs/OGC/1.3/CRS84 but the default CRS of the map is the native (storage) CRS

include::recommendations/crs/PER_crs-crs-curie.adoc[]

==== Response

include::requirements/crs/REQ_map-success.adoc[]

==== Error conditions

A general summary of the HTTP status codes can be found in https://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in the https://docs.ogc.org/is/19-072/19-072.html[OGC API – Common – Part 1: Core] Standard.

If the parameter value for `crs` is not valid for the collections, the status code of the response will be `400`.
