[[rc_data_encodings]]
== Requirements classes for encodings

The _OGC API - Maps_ Standard is designed to support mapped data that can potentially be encoded and provided in existing geospatial formats or new formats that could be developed in the future.
Web API deployments may adopt these encodings and declare conformance to them in the list of conformance classes supported by the API. 
The requirements in this section do not limit the number of encodings offered by a Maps API deployment.
The intent is to provide a minimum set of encodings that could be implemented by any deployed Maps APIs as well as to provide a practical way to test conformance to this Standard.
For each of these encodings, a requirements class is defined. An API implementing OGC API – Maps classes is free to support other encodings and data formats.
These other formats may be more convenient for given use cases even though they may not be listed as supported conformance classes by the API.
In addition, the declaration of an encoding in the supported conformance classes does not mean that all the resources provided by an implementation of an OGC API Standard should support all of them.
Partial support could be conditioned by the nature of the data behind each collection.

=== Overview

Six requirements classes for map responses of _OGC API - Maps_ implementations supporting various encodings are defined:

* <<rc_png,PNG>>
* <<rc_jpeg,JPEG>>
* <<rc_jpegxl,JPEG XL>>
* <<rc_tiff,TIFF>>
* <<rc_svg,SVG>>
* <<rc_html,HTML>>

NOTE: If maps are provided as tiles, this section should be ignored and the equivalent section in the _OGC API – Tiles - Part 1: Core_ Standard should be used instead.

NOTE: None of the encodings specified here are mandatory and an implementation of the Maps API Standard may implement none of them but implement other encodings instead.

[[rc_png]]
=== Requirements Class "PNG"

PNG can be used for simple and immediate visualization in a web browser. For this use case, selecting an encoding that can be natively interpreted by the web browser is fundamental. The PNG format is one of the most popular formats. The PNG format is defined by the ISO Information technology Computer graphics and image processing https://www.iso.org/standard/29581.html[ISO/IEC 15948:2004 Information technology — Computer graphics and image processing — Portable Network Graphics (PNG): Functional specification], also available from the World Wide Web Consortium (W3C) at https://www.w3.org/TR/PNG.

PNG supports lossless data compression. PNG supports palette-based images (with palettes of 24-bit RGB or 32-bit RGBA colors), grayscale images (with or without an alpha channel for transparency), and full-color non-palette-based RGB or RGBA images. The PNG working group designed the format for transferring images on the Internet, not for professional-quality print graphics. Therefore, non-RGB color spaces such as CMYK are not supported.

include::requirements/requirements_class_format_png.adoc[]

include::requirements/format_png/REQ_content.adoc[]

[[rc_jpeg]]
=== Requirements Class "JPEG"

JPEG can be used for simple and immediate visualization in a web browser. In these circumstances, selecting an encoding that can be natively interpreted by the web browser is fundamental. The JPEG format is another popular format used in web applications. JPEG is defined by the ITU-T Recommendation T.81 and the ISO/IEC 10918-1 Standard.

The JPEG compression algorithm operates at its best on photographs and paintings with smooth variations of tone and color. It is best used for color and grayscale still images, but not for binary images. JPEG is also the most common format used by digital cameras. However, JPEG is not well suited for line drawings and other textual or iconic graphics, where the sharp contrasts between adjacent pixels can cause noticeable artifacts. Such images are better saved in a lossless graphics format such as PNG because JPEG uses a lossy compression method, which reduces image fidelity. As such, it is inappropriate for exact reproduction of imaging data.

include::requirements/requirements_class_format_jpeg.adoc[]

include::requirements/format_jpeg/REQ_content.adoc[]

[[rc_jpegxl]]
=== Requirements Class "JPEG XL"

https://jpeg.org/jpegxl/[JPEG XL] is a relatively newer image format (compared to PNG and JPEG) with support for both lossy and lossless compression, alpha channels, high bit depths, high image quality, high compression ratio as well as high performance encoding and decoding. Free and open source libraries are available to read and write the format such as https://github.com/libjxl/libjxl[libjxl], released under a 3-clause BSD license.
Although JPEG XL is not yet widely supported in web browsers at the time of writing this document, this situation is likely to change, and this requirements class is included due to the numerous advantages of JPEG XL
over the traditional JPEG and PNG encoding, such as avoiding the need for compromising between high compression ratio, image quality and translucency.
JPEG XL is defined by the multi-part ISO standard Information technology JPEG XL - image coding system, including https://www.iso.org/standard/85066.html[ISO/IEC 18181-1:2024 Part 1: Core coding system] and
https://www.iso.org/standard/85253.html[ISO/IEC 18181-2:2024 Part 2: File format].

include::requirements/requirements_class_format_jpegxl.adoc[]

include::requirements/format_jpegxl/REQ_content.adoc[]

[[rc_tiff]]
=== Requirements Class "TIFF"
One use case for maps is to distribute coverage values as regular grids. In these circumstances, selecting an encoding able to store grid values in their original format and eventually compress them using lossless compression is the right solution. The TIFF format is one of the older formats but is still one of the most popular formats to preserve arrays of data values and is defined by the Adobe Systems TIFF v6 specification.

TIFF is a flexible, adaptable file format for handling images and data. The ability to store data in a lossless format makes a TIFF file a useful image archive: Unlike standard JPEG files, a TIFF file using lossless compression such as PackBits or LZW compression.

include::requirements/requirements_class_format_tiff.adoc[]

include::requirements/format_tiff/REQ_content.adoc[]

include::recommendations/format_tiff/REC_geotiff.adoc[]

[[rc_svg]]
=== Requirements Class "SVG"

SVG is a commonly used format for representing vector objects on the web. SVG is simple to understand and well supported by tools and software libraries. Modern web browsers can render the SVG format directly and can also react to events generated by the user on the features visualized. That is why it is a good alternative for creating more interactive maps.

include::requirements/requirements_class_format_svg.adoc[]

include::requirements/format_svg/REQ_content.adoc[]

include::recommendations/format_svg/PER_overflow.adoc[]

[[rc_html]]
=== Requirements Class "HTML"

Returning an HTML page with a full, operational map browser that allows for interactive navigation over the map (e.g., zoom and pan) is convenient for easy exploration of the data or for testing purposes.

include::requirements/requirements_class_format_html.adoc[]

include::requirements/format_html/REQ_content.adoc[]

include::recommendations/format_html/REC_content.adoc[]
