[[rs_spatial-subsetting-by-coord-intervals]]
== Requirement Class "Spatial subsetting"

=== Overview

[[maps-spatial-subsetting-overview]]

include::requirements/requirements_class_spatial-subsetting.adoc[]

The core requirements class of this standard defines the map resource.
The core also defines a minimum set of metadata to enable a client application to formulate a map request.
This requirements class adds the ability to request an arbitrary 2D subset of a map using either a bounding box specified using one of two equivalent syntaxes
(a `bbox` parameter similar to the one in WMS 1.3, as well as a `subset` parameter similar to WCS 2.1),
or as a center point as well as `width` and/or `height` parameters taking into account the scale and the display resolution.

The client can use only one of the `bbox`, `subset` or `center` subsetting mechanism.

[[maps-spatial-subsetting-crs]]
=== CRS for subsetting
In WMS 1.3 the CRS parameters had two missions: it indicated the CRS of the data rendered in the map and it was the CRS of the coordinates of the BBOX parameter.
In this Standard, these two objectives have been separated. This section defines the CRS parameters for subsetting.

The CRS advertised in the collection's spatial extent is always in http://www.opengis.net/def/crs/OGC/1.3/CRS84 (for Earthly data and as required by OGC API Features). At least, for OGC API Maps and OGC API Coverages a native CRS (also called or storage CRS) is defined. The Content-Crs header (see <<maps-core-overview>>) specifies the CRS used in the response to avoid confusion.

NOTE: There is no obligation to provide the maps in http://www.opengis.net/def/crs/OGC/1.3/CRS84.

NOTE: The collections description will contain a native or storage CRS. If it is not there then we will assume http://www.opengis.net/def/crs/OGC/1.3/CRS84. The exact mechanism to do so will be defined by OGC API common.

NOTE: Provide the extent of the collection in native CRS (also called or storage CRS) is recommended and the mechanism will be defined by OGC API common.

NOTE: A list of supported CRS's will be provided by the collection. The first should be storage CRS. The mechanism to do so will be defined by OGC API common.

==== Parameter bbox-crs

include::requirements/subsetting/REQ_bbox-crs-definition.adoc[]

==== Parameter subset-crs

include::requirements/subsetting/REQ_subset-crs-definition.adoc[]

==== Parameter center-crs

include::requirements/subsetting/REQ_center-crs-definition.adoc[]

NOTE: For clarification: The default CRS of the bbox, center and subset spatial dimensions is http://www.opengis.net/def/crs/OGC/1.3/CRS84 and the default CRS of the map is native (storage) CRS.

NOTE: The `center-crs`, `subset-crs` and `bbox-crs` are defined identically except they are affecting `center`, `subset` and `bbox` parameters respectively.

==== CURIE permission

include::recommendations/subsetting/PER_subset-crs-curie.adoc[]

=== Subsetting coordinates

==== Parameter `bbox`
This parameter defines how to subset a map by bounding box (in the `bbox-crs` coordinates). The `bbox` parameter values are defined considering the exterior edges of the pixels of the viewport defined by the width and height. In other words, the relation of the Bounding Box to the map pixel matrix is that the bounding box goes around the "outside" of the pixels of the map rather than through the centers of the map's border pixels (as many times done in coverages). In this context, individual pixels represent a cell area on the ground.

include::requirements/subsetting/REQ_bbox-definition.adoc[]

NOTE: This parameter use the comma (",") as the separator between the coordinates. Additional white space will not be used to delimit list items. The comma character should not be escaped (IETF RFC 2396).

Example:
`bbox=-180,-90,180,90&bbox-crs=`

==== Parameter `subset`
The behavior of the subset parameter is imported from the _OGC API - Common_ subset module. The entire module is reproduced here.
However, some considerations may not apply, and the generic behavior is limited by the CRS axis abbreviations.

include::api_modules/subset/requirements_module_subset.adoc[]

include::requirements/subsetting/REQ_subset-coordinates.adoc[]

include::recommendations/subsetting/REC_subset-crs-axis-names.adoc[]

==== Parameter `center`, `width` and `height`

The `center` parameter defines the center point of the map in the `center-crs` coordinates from which the `width` and `height` parameter will define a subset,
taking into consideration the scale and display resolution of the map.

NOTE: This parameter use the comma (",") as the separator between the coordinates. Additional white space will not be used to delimit list items. The comma character should not be escaped (IETF RFC 2396).

include::requirements/subsetting/REQ_center-definition.adoc[]

include::requirements/subsetting/REQ_subsetting-width-height-definition.adoc[]

=== Response

A successful GET response is described in the core class (http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core).

include::requirements/subsetting/REQ_map-success.adoc[]

Normally, the content partially outside the map bounding box will be clipped at the extent of the bounding box. This can be done efficiently when map subsets are in raster format (e.g. map tiles). However, maps containing features in vector format may not clip features that are partially outside to ensure continuity of features or for performance.

include::recommendations/subsetting/REC_map-outside-bounds.adoc[]

include::recommendations/subsetting/PER_map-outside-bounds.adoc[]

NOTE: As defined in the core requirements class, the `ogcapi-bbox` and the `Content-Crs` response headers report the actual bounding box of the data returned.

=== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the CRS in the parameter value `bbox-crs`, `subset-crs` or `center-crs` is not supported by the server for this resource, the parameter value is out-of-range, or the map is not provided due to lack of data in the area, the status code of the response will be `404`.

