[[rc_core]]
== Requirement Class "Core"

[[maps-core-overview]]
=== Overview

include::requirements/requirements_class_core.adoc[]

This core specifies a map resource: a resource that represents the geospatial data as a rendered map. Requesting a map resource, as defined in this core, results in retrieving a generic map as a graphical representation of the data in the API. With only the core, the representation is not constrained almost in any way by the client, so the server is free to return a total or a partial representation of the resource of an arbitrary size. Additional requirement classes will add query parameters to personalize the server behavior to the client needs. These requirement classes will define specific parameters that will allow for the client to control the map size and resolution of the map (width, height, bounding box and CRS) and well as the background of the map. In addition, an orthogonal requirement class will define how a map resource can be retrieved as tiles by applying the OGC API - Tiles.

A map resource can be obtained from a non map resource by adding `/map` to the resource URI. The core does not specify to which resources `/map` is applicable. However, a list of common places in the API, where maps can commonly be obtained is present in the following table as a recommendation. Additional requirements classes will better define these possibilities.

[#Common-map-resources-in-the-api,reftext='{table-caption} {counter:table-num}']
.Common map resources in a geospatial API
[width = "100%",options="header"]
|===
|Resource	Path |Description
|/map |A map representing dataset behind the API in the default style
|/styles/{styleId}/map |A map representing dataset behind the API in the `styleId` style.
|/collections/{collectionId}/map | A map representing `collectionId` in the default style
|/collections/{collectionId}/styles/{styleId}/map | A map representing `collectionId` in the `styleId` style
|===

NOTE: There is no mandatory dependency of this core on _OGC API - Common_. This allows for non-OGC APIs to implement this core without the need to comply to the OGC API common structure (landing page, conformance, API description). However, it expected that many implementations will specify a dependency on _OGC API - Common_ in their conformance page.

=== Map resource

A map distribution of a geospatial resource is a pictorial representation of it. To create a pictorial representation, a style is added to the data in the geospatial resource by a portrayal engine and following portrayal rules. This style can be internal (default style) or can be governed by the client.

This section defines the core resource of the _OGC API - Maps_ standard: a map representation for a geospatial resource. To keep the core of _OGC API - Maps_ simple, the core only includes a mechanism to retrieve a map of the size and for the spatiotemporal extent that the server considers optimal.

==== Operation
include::requirements/core/REQ_map-op.adoc[]

==== Response
include::requirements/core/REQ_map-response.adoc[]

==== Recommendations

include::recommendations/core/REC_map-op.adoc[]

include::recommendations/core/REC_content-crs.adoc[]

include::recommendations/core/REC_link-relation-type.adoc[]

include::recommendations/core/REC_multiple-media-types.adoc[]

Retrieving a map without subsetting or tiling has a limited use. An implementation should therefore consider allowing to retrieve only part of a map by supporting the _map tilesets_ and/or
the _spatial subsetting_ requirements class.

NOTE: The desired encoding is selected using HTTP content negotiation. In addition to the parameters specified by the core, other parameters should be added.

NOTE: HTTP content negotiation replaces the `FORMAT=` parameter in WMS. However, for convenience, some implementations can implement a `f=` parameter for circumstances where content negotiation is not possible or available (e.g., testing the API in a web browser, or using a URL embedded in an HTML IMG SRC tag).

=== Declaration of conformance classes
To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the conformance classes it implements and conforms to.

The conformance page mainly consists of a list of links.

include::requirements/core/REQ_conformance-success.adoc[]

If the server declares conformity also to _OGC API - Common - Part 1: Core_ or to _OGC API - Features - Part 1: Core_, then it has to consider the OGC API requirements for declaring conformance, i.e. the use of the `/conformance` resource. In the JSON format, the conformance resource is an array of links following the link schema defined in _OGC API - Common - Part 1: Core_ or in _OGC API - Features - Part 1: Core_. Below is an example fragment of a conformance information page of an API conformant to _OGC API - Common_ and _OGC API - Maps_.

[[ConformancePageMapsCore]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core"
  ]
}
=================
