[[rc_maps_tileSets-list]]
== Requirement Class "Map TileSets List"

=== Overview

[[maps-tilesets-overview]]

include::requirements/requirements_class_tilesetslist.adoc[]

This extension describes how to subset a map by making it accessible as tiles. Another way to subset a map is provided by another requirements class is to provide a bounding box (in a CRS).

NOTE: The concept of map tiles substitutes the WMTS 1.0 concept of tiles. Tiles can be data tiles (e.g. vector tiles) or map tiles (tiles that are rendered using an style)

=== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of links.

include::requirements/tilesets/REQ_conformance-success.adoc[]

If the server declares also conformity to OGC API - Common or to http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0], then it has to consider the OGC API - Common requirements for declaring conformance, i.e. the use of a the conformance page. In the JSON format the conformance page is an array of links following the link schema defined in the OGC API - Common or in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0]. Below is an example fragment of a conformance information page of an API conformant to OGC API - Common and OGC API - Tiles.

[[ConformancePageMapTileSets]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tilesets-list"
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-maps-2/1.0/conf/tilesets"
  ]
}
=================

=== Map
This standard does not specify how maps are exposed in the API. Refer to the _OGC API - Maps - Part 1: Core_, classes dataset or geodata for examples on how to generate maps.

include::requirements/tilesets/REQ_desc-links.adoc[]

.Fragment of a collection description document with a links array with one item of the array pointing to a tilesets.
=================
[source,JSON]

{
    "links": [
    ...
    {
      "href": "http://data.example.com/collections/buildings/map/tiles",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/tileset",
      "type": "application/json",
    }
  ]
}
=================

include::recommendations/tilesets/REC_desc-links.adoc[]

=== Map Tileset
A tileset contains the necessary metadata to enable a client application to formulate a tile request from a single geospatial data resource.

==== Operation

The tileset operation is described in the tileset class of the OGC API - Tiles

This standard does not specify the need for any additional query parameter in the GET request.

==== Response

A successful GET response is described in the tileset class of the OGC API - Tiles
