[[rc_scaling]]
== Requirement Class "Scaling"

=== Overview

[[maps-scaling-overview]]

include::requirements/requirements_class_scaling.adoc[]

This extension describes how to scale a map by specifying a set of parameters that will define its size (width and height) in pixels of a displaying device that indirectly defines que scale of the map.

=== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of links. OGC API - Common already requires some links.

include::requirements/scaling/REQ_conformance-success.adoc[]

In the conformance page (typically in JSON format) the links follow the link schema defined in the OGC API - Common. The following is an example fragment of the response of an implementation of the OGC API - Maps draft specification with the maps extension conformance information page.

[[ConformancePageMapsMaps]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-maps-2/1.0/req/scaling"
  ]
}
=================

=== Map resource
The _OGC API - Maps - Part 1: Core_ defines the map resource. The core also defines a minimum set of metadata to enable a client application to formulate a map request.

This class defines a extension to the core needed to scale the map by defining its size.

The geospatial resource may expose a geospatial extent. This does not precluded that the map resource presents its own extent that will be similar or smaller to the geospatial extent resource (the API may opt to expose only a part of the geospatial resource as a map subsets)

include::recommendations/scaling/REC_max-width-height.adoc[]

NOTE: These are indented to limit the work load of the server by providing limitations in size of the outputs of the subset. If you width and height parameters are related with the size of the device screen, please consider that new devices are being build with more and more pixels and a reasonable limit last year may be too restrictive with the emerging devices.

==== Operation

The core of Part 1 defines how to get a map. This standard specifies the parameters needed to scale a map.

==== Parameters width and height
These parameters indicate the size of the viewport in rows and columns where the map is going to be shown. If the format of the response is a raster image, the number of columns and rows of the image will match the requested width and height respectively

include::requirements/scaling/REQ_width-definition.adoc[]

include::requirements/scaling/REQ_height-definition.adoc[]

==== Aspect ratio considerations
If a client provides both width and height the server will adopt them even if the aspect ratio between (maxx-minx)/(maxy-miny) and w/h are different (resulting in a non square pixel). However, in general circumstances, the client should make an effort to preserve the aspect ratio. The client is allowed to provide only one of the values in width and height and the server should figure out the other one to maintain the aspect ratio.

include::recommendations/scaling/REC_width-definition.adoc[]

include::recommendations/scaling/REC_height-definition.adoc[]

include::recommendations/scaling/PER_no-width-height-definition.adoc[]

==== Parameter cell-size
The width and height of the image to be presented in the display device is not actually controlling the scale because it is provided in pixel units. What controls the scale is the ratio between the size of features represented in the map and the size of the features in the reality. One way to determine the scale is to divide the actual size of the display device in physical units (e.g. millimeters) by the actual size of the extent of the map (e.g. in meters).
include::requirements/scaling/REQ_cell-size-definition.adoc[]

With this parameter, the server is able to know how big the map will be presented or printed and react accordingly. For example, if the server receives a very small value, the server could decide to represent linear elements wider than for normal values (preventing to create a representation of linear features that is going to result in lines that are too thin to be correctly perceived).

==== Response

include::requirements/scaling/REQ_map-success.adoc[]

include::recommendations/scaling/REC_map-success-scale.adoc[]

==== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the parameters values for `width` or `height` are out-of-range, the status code of the response will be `400`.
If map is not provided due to lack of data in the area, the status code of the response will be `204`.
