[[rc_crs]]
== Requirement Class "Coordinate Reference System"

[[maps-crs-overview]]
=== Overview

include::requirements/requirements_class_crs.adoc[]

In WMS 1.3 the CRS parameters had two purposes: it indicated the CRS of the data rendered in the map and it was the CRS of the coordinates of the BBOX parameter. In this standard, these two purposes has been separated. This section describes how to request a map in a specific CRS.

At least for _OGC API - Maps_ and _OGC API - Coverages_, a native CRS (also called a _storage CRS_) is defined. The `Content-Crs:` header (see <<maps-core-overview>>) specifies the CRS used in the response to avoid confusion.

=== Operation

The core requirements class of this standard defines how to retrieve a map. This requirements class specifies parameters needed to retrieve a map in a particular output CRS.

==== Parameter `crs`
A successful GET response is described in the core class (http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core).

include::requirements/crs/REQ_crs-definition.adoc[]

See how to determine the native (storage) CRS for the collection and the dataset in <<rc_collection-map>> and <<rc_dataset-map>> respectively.

NOTE: The default CRS of the BBOX is http://www.opengis.net/def/crs/OGC/1.3/CRS84 but the default CRS of the map is the native (storage) CRS

include::recommendations/crs/PER_crs-crs-curie.adoc[]

==== Response

include::requirements/crs/REQ_map-success.adoc[]

==== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the parameter value for `crs` is not one of the supported for the collections, the status code of the response will be `404`.
