== Requirement Class "Map Core"

=== Overview

[[maps-core-overview]]

include::requirements/requirements_class_core.adoc[]

It specifies a map resource: a resource that contains information on how to formulate a request to a map. This document includes the CRSs and styles supported and other metadata (including attribution).
It also specifies how to apply a style to a map resources to get a styled map.

**TBD**

A map distribution of a dataset is a pictorial representation of geospatial resources. To create a pictorial representation a style is added to the data in the geospatial resource. Styles are defined internally and have a identifier. New styles can be added or modified if the OGC API - Maps draft specification works in combination with the OGC API - Styles draft specification. After associating styles to geospatial resources, a map can be retrieved by specifying a set of parameters that will determine its resolution (width, height, bounding  box and CRS) or can be retrieved as tiles.

This section defines the core part of the OGC API - Maps standard that allows defining a map representation for a geospatial resources. To retrieve a fragment of the map, this core needs to be combined with an OGC API - Tiles core standard or with the OGC API - Maps - Bbox extension standard.

To keep the core of the OGC API - Maps standard simple, the core only includes a mechanism to select the default style but it does not define any mechanism to declare, define or select a style other than the default one. The core only assumes that the service is capable of knowing which is the default style while the client ignores all the details about it (including its name).

**End of TBD**

=== Declaration of conformance classes
To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the conformance classes it implements and conforms to.

==== Response
The conformance page mainly consists of a list of links.

include::requirements/core/REQ_conformance-success.adoc[]

If the server declares also conformity to OGC API - Common or to OGC API - Features v1, then it has to consider the OGC API - Common requirements for declaring conformance, i.e. the use of a the conformance page. In the JSON format the conformance page is an array of links following the link schema defined in the OGC API - Common or in OGC API - Features v1. Below is an example fragment of a conformance information page of an API conformant to OGC API - Common and OGC API - Maps.

[[ConformancePageMapsCore]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
  [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core"
  ]
}
=================

=== Map
A map is defined by a map description document that contains the necessary metadata to enable a client application to formulate a map request from a single geospatial resource, some geospatial resources for from the entire dataset.

Nevertheless, the core class does not specify how to retrieve a map description.

==== Map description document
The core introduces the way data will be combined with styles to create a map. The only mandatory element in the map description document is the list of styles that are used to transform a resource into a map

include::requirements/core/REQ_styles.adoc[]

.API collection response fragment
=================
[source,JSON]
  "styles": [
  {
    "id": "night",
    "title": "Topographic night style",
    "links": [
      {
        "href": "https://example.com/api/1.0/styles/night?f=sld10",
        "type": "application/vnd.ogc.sld+xml;version=1.0",
        "rel": "stylesheet"
      },
      {
        "href": "https://example.com/api/1.0/styles/night/metadata?f=json",
        "type": "application/json",
        "rel": "describedBy"
      }
    ]
  },
  {
    "id": "topographic",
    "title": "Regular topographic style",
    "links": [
      {
        "href": "https://example.com/api/1.0/styles/topographic?f=sld10",
        "type": "application/vnd.ogc.sld+xml;version=1.0",
        "rel": "stylesheet"
      },
      {
        "href": "https://example.com/api/1.0/styles/topographic/metadata?f=json",
        "type": "application/json",
        "rel": "describedBy"
      }
    ]
  }
]
=================
The mandatory element `id` designates the id of the style. The work "default" is reserved to designate the default style.

The optional links element is useful for retrieving a styles description document. The format of a style description document is out of scope of this document. A possible encoding is the OGC Symbology Encoding.

include::recommendations/core/REC_smc-default-style.adoc[]

.API collection response fragment
=================
[source,JSON]
  "defaultStyle": "topographic"
=================

Two following two recommendations for having two specific properties in a map description are inherited from WMS: cascade and opaque.

include::recommendations/core/REC_smc-opaque.adoc[]

include::recommendations/core/REC_smc-cascaded.adoc[]

=== Map
This OGC API - Maps core standard does not specify how to retrieve a subset of a map. However, it does specify that in order for a map to be retrievable a parameter styleId should be added to a map resource in order to be ready to subset it other parameters may condition the style of the map. A map can be subset with bounding boxes or retrieved as tiles.

==== Operation
include::requirements/core/REQ_map-op.adoc[]

include::recommendations/core/PER_map-op.adoc[]

==== Parameter styleId
include::requirements/core/REQ_styleId-definition.adoc[]

==== Parameter transparent
include::requirements/core/REQ_mc-transparent-definition.adoc[]

==== Parameter bgcolor
include::requirements/core/REQ_mc-bgcolor-definition.adoc[]

If the client wants to force an opaque color, apart from defining the appropriate background color it should ensure that the parameter `transparent` is set to `false`. For the formats that reserve a color to define transparency, it still makes sense to combine background color and transparent=true with the purpose of helping the server to select a color that does not interfere with the actual values and colors in the map.

==== Response
The response of a GET request to this resource is not completely specified by this core. Without extra parameters, the response could results in a map representing the whole geospatial data resource at maximum resolution that could be too difficult to generate by the server or too big to be efficinetly retrieved by the client. Instead, it is expected that other path and query parameters are added by other extensions of this core to complete define the response. 
