[[rc_datasetMaps]]
== Requirement Class "Dataset Maps"

=== Overview

[[dataset-maps-overview]]

include::requirements/requirements_class_dataset-map.adoc[]

The map core and the map metadata, define how to get a map from a resource but they do nor detail which resources can be "mapped". This requirements class defines how to get a map resource from the dataset (or datasets) represented by the services. In other words it provides the path to get a map resource from the dataset behind the API. This is achieved by using by adding the map path to the root (a.k.a. the landing page) of the service.

=== General
include::recommendations/dataset/REC_api-common.adoc[]

This building block stays flexible and does not require implementation OGC API - Common, allowing for other API architectures outside the OGC API framework to adopt it. However, a server under the OGC APIs is expected to implement OGC API - Common. If so, in practice, this means that the landing page and the conformance page follow OGC API - Common core and collections requirement classes when used. Temporarily, it is also possible to combine this building block with http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] that is not tied to OGC API - Common.

=== Dataset API landing page

The landing page provides links to start exploring the resources offered by the API. It mainly consists of a list of links to `root` resources. This standard extension requires a new link in the landing page for getting a dataset map

==== Response

The root of the API represents a dataset that will be exposed in different ways by the API.

The root can be modified or complemented by other resources creating new endpoints indirectly giving access to the modified or complemented dataset. Other OGC API family standards will define this mechanisms. Examples of standards doing that are:

* OGC API - Styles defines how to complement a geospatial resource by adding a style to it. The new resources is an overlap of the dataset and the resource

include::requirements/dataset/REQ_landingpage.adoc[]

In the landing page, in JSON format, the links follow the link schema defined in the OGC API - Common or in OGC API - Features v1. Below you can find an example fragment of the response to an OGC API - Maps landing page showing the link to root tiles.

[[landingPageTilesRoot]]
.API Landing Page fragment that advertises dataset maps. The same links could be added to a room style description.
=================
[source,JSON]
----
{
  links: [
    ...,
    {
      "href": "http://data.example.org/map",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/map",
      "type": "image/png",
      "title": "Map combining collections in the dataset"
    },
    {
      "href": "http://data.example.org/map/metadata",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/map-meta",
      "type": "application/json",
      "title": "Metadata of the map combining collections in the dataset"
    }
  ]
}
----
=================

=== Declaration of conformance classes

==== Response

The conformance page mainly consists of a list of links. OGC API - Common already requires some links.

include::requirements/dataset/REQ_conformance-success.adoc[]

In the conformance page (typically in JSON format) the links follow the link schema defined in the OGC API - Common. The following is an example fragment of the response of an OGC API - Maps conformance information page

[[ConformancePageMapsCollection]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core"
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/dataset"
  ]
}
=================

=== Dataset maps
The maps core defines a `map` resource that is associated with an operation that contains the necessary information to later formulate a map request. Nevertheless, the core does not does not specify how to retrieve a map resource description. This section offers one possible path to do that from the dataset represented by the API.

==== Map path

include::requirements/dataset/REQ_operation.adoc[]

The request of this operation does not define extra parameters. Servers can advertise the requirements class http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/collections-selection to add a `collections` parameter that can be used to include only parts of the dataset in the map representation. Other extensions of this map standards will define how to get a subset of a map resource.

==== Response
A successful GET response is described in the core class (http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core)

A successful response is map that is expected to represent the dataset as a whole. In a Web API providing access to  a complex dataset formed by several geospatial data resources, there are reasons for being selective in the amount of information included. This can be achieved by applying a manual filter currently described in a OGC API - Tiles - Part 1 or as an automatic decision by the server side.

include::recommendations/dataset/REC_geodata-selection.adoc[]

include::recommendations/dataset/PER_geodata-selection.adoc[]
