[[rm_collections-selection]]

In a Web API providing access to a complex dataset formed by several geospatial data resources, it can be useful to select specific sub-resources of interest when requesting data from this dataset.
This requirements class defines how to include a query parameter when requesting a resource (e.g., dataset tiles) to specify which geospatial data resources (a.k.a. collections) should be used to generate the response.

This conformance class can be used e.g. in conjunction with the <<rc_datasetTileSets>> conformance class or in conjunction with an equivalent conformance class in _OGC API - Maps_.

=== General
include::recommendations/collections-selection/REC_api-common.adoc[]

This building block stays flexible and does not strictly require implementing _OGC API - Common_, allowing for other Web API architectures outside the OGC API framework to adopt it.
However, a server implementing other OGC APIs is expected to implement _OGC API - Common_.
In practice, this means that the landing page and the conformance page follow _OGC API - Common_ _core_ and _collections_ requirement classes when used. Temporarily, it is also possible to combine this building block with http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] that is not tied to _OGC API - Common_.

=== Selection of collections

==== Operation
By default, the geospatial data resources included in the dataset are undefined but are supposed to represent the dataset as a whole. This class adds a mechanism to select the geospatial data resources to be used to generate the derived resources (e.g., maps or tiles). In practice this enables the capability to generate resources involving more than one geospatial data sub-resource.

==== Parameter Resources
[[req_collections-selection_resources-query]]

include::requirements/collections-selection/REQ_query-collections.adoc[]

When this parameter refers to more that one geospatial data resource, this parameter will use the
comma (",") as the separator between the resource identifiers in the list. Additional white space will not be used to delimit list items. If a geospatial data resource identifier includes a space or comma, it shall be escaped using the URL encoding rules (IETF RFC 2396).

==== Error conditions

If the value of the parameter `collections` contains a resource id of URI that does not exist on the Web API, the status code of the response is 400.

If the value of the parameter `collections` has a wrong format or combines one of more geospatial data resources that are not compatible (e.g., they do not have a compatible value specified by other parameters in the request), the status code of the response is 400.
