== Requirement Class "Map BBox"

=== Overview

[[maps-bbox-overview]]

include::requirements/requirements_class_bbox.adoc[]

This extension describes how to subset a map by specifying a set of parameters that will determine its resolution (width, height, boundingbox and CRS).

=== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of links. OGC API - Common already requires some links.

include::requirements/bbox/REQ_conformance-success.adoc[]

In the conformance page (typically in JSON format) the links follow the link schema defined in the OGC API - Common. The following is an example fragment of the response of an implementation of the OGC API – Maps draft specification with the maps extension conformance information page.

[[ConformancePageMapsMaps]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
  [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core"
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/bbox"
  ]
}
=================

=== Map subset by bounding box

==== Operation

The core of this standard defines how to add a {styleId} parameter to a map to make retrievable as a subset. This standard specifies the parameters needed to subset a map an retrieve fragments of it.

An example of a resource that can be retrieved as map subsets is a feature collection (/collections/{collectionId}/map/{styleId}).

The supported encodings, or more precisely the media types of the supported encodings, can be determined from the API definition. The desired encoding is selected using HTTP content negotiation. In addition the parameters specified by the core, other parameters should be added.

==== Parameter crsId
This parameter indicates the CRS of the data rendered in the map as well as the CRS used by the parameter bbox.
include::requirements/bbox/REQ_crsid-definition.adoc[]

==== Parameter bbox
This parameter indicates the size of the bbox of the subset of the data (in the crsId coordinates).
include::requirements/bbox/REQ_bbox-definition.adoc[]

==== Parameter width
The subset of the map will specify the size of the viewport in rows and columns. If the format of the response is a raster image, the size of the image will match the requested width and height.
include::requirements/bbox/REQ_width-definition.adoc[]

==== Parameter height
include::requirements/bbox/REQ_height-definition.adoc[]

==== Response

A successful response to a map bbox GET operation will be consistent with the media type of resource requested. This draft specification does not impose any media type or file format and maps response may be in JPEG, PNG or other appropriate format (including vector based formats such as KML or SVG).

include::requirements/bbox/REQ_map-success.adoc[]

include::recommendations/bbox/PER_map-encoding.adoc[]

Normally, the content partially outside the map bounding box will be clipped at the extent of the bounding box. This can be done efficiently when map subsets are in raster format (e.g. map tiles). However, maps containing features in vector format may not clip features that are partially outside to ensure continuity of features or for performance.

include::recommendations/tileset/REC_tc-success-scale.adoc[]

==== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the parameter value `crsId` is not available by the server for this resource or the parameters values `bbox`, `width`, `height` are out-of-range, or the map is not provided due to lack of data in the area, the status code of the response will be `404`.
