== Requirement Class "Map BBox"

=== Overview

[[maps-bbox-overview]]

include::requirements/requirements_class_bbox.adoc[]

This extension describes how to subset a map by specifying a set of parameters that will determine its resolution (width, height, boundingbox and CRS).

=== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of links. OGC API - Common already requires some links.

include::requirements/bbox/REQ_conformance-success.adoc[]

In the conformance page (typically in JSON format) the links follow the link schema defined in the OGC API - Common. The following is an example fragment of the response of an implementation of the OGC API – Maps draft specification with the maps extension conformance information page.

[[ConformancePageMapsMaps]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
  [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/core"
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/req/bbox"
  ]
}
=================

=== Map Bbox

==== Operation

The core of this standard defines how to add a {styleId} parameter to a map to make retrievable as a subset. This standard specifies the parameters needed to subset a map an retrieve fragments of it.

An example of a resource that can be retrieved as map subsets is a feature collection (/collections/{collectionId}/map/{styleId}).

==== Parameter crsId
This parameter indicates the CRS of the data rendered in the map as well as the CRS used by the parameter bbox.
include::requirements/bbox/REQ_crsid-definition.adoc[]

==== Parameter bbox
This parameter indicates the size of the bbox of the subset of the data (in the crsId coordinates).
include::requirements/bbox/REQ_bbox-definition.adoc[]

==== Parameter width
The subset of the map will specify the size of the viewport in rows and columns. If the format of the response is a raster image, the size of the image will match the requested width and height.
include::requirements/bbox/REQ_width-definition.adoc[]

==== Parameter height
include::requirements/bbox/REQ_height-definition.adoc[]

==== Response

A successful response of a map request will be consistent with the media type of the resource requested. Common formats are JPEG or a PNG.

//include::requirements/tiles/maps/REQ_tc-success.adoc[]

==== Error conditions

A general summary of the HTTP status codes can be found in OGC API - Common.

If the parameter crs is not available by the server for this resource or the parameters bbox, width, height are out-of-range, the status code of the response will be 404.
