[[req_map-bbox_crs-and-extent]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/map-bbox/crs-and-extent*
^|A |The map description document SHALL enumerate the CRSs supported by the map resource  with the characteristics defined (shown as OpenAPI Specification 3.0 fragment). In addition the extent for each CRS could be provided.
[source,YAML]
----
  crsSpatialExtents:
    type: array
    description:
      Available CRSs and minimum spatial extent surrounding the map
    items:
      description:
        Available CRS and minimum spatial extent surrounding the map
      type: object
      required:
        - crs
      properties:
        crs:
          description:
            Coordinate reference system of the coordinates in the spatial extent
            (property `bbox`). The default reference system is WGS 84 longitude/latitude.
            In the Core this is the only supported coordinate reference system.
            Extensions may support additional coordinate reference systems and add
            additional enum values.
          type: string
          enum:
            - 'http://www.opengis.net/def/crs/OGC/1.3/CRS84'
          default: 'http://www.opengis.net/def/crs/OGC/1.3/CRS84'
        bbox:
          description:
            One or more bounding boxes that describe the spatial extent of the dataset.
            In the Core only a single bounding box is supported. Extensions may support
            additional areas. If multiple areas are provided, the union of the bounding
            boxes describes the spatial extent.
          type: array
          minItems: 1
          items:
            description:
              West, south, east, north edges of the bounding box. The coordinates
              are in the coordinate reference system specified in `crs`. By default
              this is WGS 84 longitude/latitude (CRS84).
            type: array
            minItems: 4
            maxItems: 6
            items:
              type: number
|===
