[[req_checkpoint_core_cp-changesettype-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/checkpoint/core/cp-changesettype-definition*
^|A |The operation SHALL support an optional parameter `changeSetType` that determines the type of the response and with the following characteristics (using an OpenAPI Specification 3.0 fragment) and determines the type of the response
[source,YAML]
----
  name: changeSetType
  in: query
  required: false
  style: form
  explode: false
  schema:
    type: string
    default: full
    enum:
      - summary
      - full
      - package
  example: full
----
^|B |If the value of the `changeSetType` parameter is set to `full` or if the parameter is not specified in the request, the server SHALL return the complete changeSet file following the `changeSet` schema.
^|C |If the value of the `changeSetType` parameter is set to `summary` the server SHALL return a summary of the changes. The summary SHALL follow the `changeSetSummary` schema.
^|D |If the value of the `changeSetType` parameter is set to `package` the server SHALL return a package (e.g. a ZIP file) that will include a summary of the changes (The summary follows the `changeSetSummary` schema) and the changes themselves as separated parts in the package. Use this value for requesting changes in tiled resources.
|===
