[[req_core_map-response]]

[requirement]
====
[%metadata]
identifier:: /req/core/map-response
part:: A successful execution of a map operation SHALL be a response with an HTTP status code 200.
part:: The map response SHALL be in the storage CRS specified in the description of the geospatial resource (such as the associated collection or dataset), or https://www.opengis.net/def/crs/OGC/1.3/CRS84 if none is specified, unless overridden by a specific query parameter (see <<rc_crs>>).
part:: The headers of the response SHALL include the `Content-Crs:` header with the URI or the safe CURIEs of the CRS used to render the map, except if the content is in the https://www.opengis.net/def/crs/OGC/1.3/CRS84 CRS.
part:: The headers of the response SHALL include a `Content-Bbox:` header with the actual geospatial boundary of the rendered map.
part:: The `Content-Bbox:` coordinates SHALL be in the response CRS (indicated in the `Content-Crs:` or https://www.opengis.net/def/crs/OGC/1.3/CRS84 if it is not present) and SHALL contain four comma-separated numbers representing the lower-left and upper-right corners of the response honoring the CRS coordinates order.
part:: If the geospatial resource has a temporal aspect (e.g., if a temporal extent is defined in the collection description or in the dataset landing page),
the headers of the response SHALL include a `Content-Datetime:` header with the actual datetime instant or datetime interval of the rendered map.
part:: In the `Content-Datetime:` response header, a datetime interval SHALL be expressed using the notation `time-instant / time-instant`.
part:: In the `Content-Datetime:` response header, a time instant, whether a single value or the `time-instant` of an interval, SHALL be expressed as defined in RFC 3339, section 5.6, using either UTC time or local time offsets,
with the additional options of:
* only a year: `yyyy`
* a year and a month: `yyyy-mm`
* a year, a month and a day: `yyyy-mm-dd`
* a year, a month, a day and an hour: `yyyy-mm-ddThhZ` (or e.g., `yyyy-mm-ddThh-04:00`)
* a year, a month, a day, an hour and a minute: `yyyy-mm-ddThh:mmZ` (or e.g., `yyyy-mm-ddThh-04:00`)
part:: The body of a response of a successful operation SHALL contain a map encoded in the negotiated format.
====
