[[req_core_map-response]]
////
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/core/map-response*
^|A |A successful execution of a map operation SHALL be a response with a HTTP status code 200.
^|B |The map response SHALL be in the storage CRS specified in the collection description, or https://www.opengis.net/def/crs/OGC/1.3/CRS84 if none is specified, unless overridden by a specific query parameter (see <<rc_crs>>).
^|C |The headers SHALL include the "Content-Crs" header with the URI or the safe CURIEs of the CRS used to render the map, except if the content is in the https://www.opengis.net/def/crs/OGC/1.3/CRS84 CRS.
^|D |The headers of the response SHALL include a "Content-Bbox" header with the actual geospatial boundary of the rendered map.
^|E |The "Content-Bbox" coordinates SHALL be in the response CRS (indicated in the "Content-Crs" or https://www.opengis.net/def/crs/OGC/1.3/CRS84 if it is not present) and SHALL contain four comma separated numbers representing the lower-left and upper right corners of the response honoring the CRS coordinates order.
^|F |The body of a response of a successful operation SHALL contain a map in the negotiated format.
|===
////

[requirement]
====
[%metadata]
identifier:: /req/core/map-response
part:: A successful execution of a map operation SHALL be a response with a HTTP status code 200.
part:: The map response SHALL be in the storage CRS specified in the collection description, or https://www.opengis.net/def/crs/OGC/1.3/CRS84 if none is specified, unless overridden by a specific query parameter (see <<rc_crs>>).
part:: The headers SHALL include the "Content-Crs" header with the URI or the safe CURIEs of the CRS used to render the map, except if the content is in the https://www.opengis.net/def/crs/OGC/1.3/CRS84 CRS.
part:: The headers of the response SHALL include a "Content-Bbox" header with the actual geospatial boundary of the rendered map.
part:: The "Content-Bbox" coordinates SHALL be in the response CRS (indicated in the "Content-Crs" or https://www.opengis.net/def/crs/OGC/1.3/CRS84 if it is not present) and SHALL contain four comma separated numbers representing the lower-left and upper right corners of the response honoring the CRS coordinates order.
part:: The body of a response of a successful operation SHALL contain a map in the negotiated format.
====

