[[req_subsetting_subset_crs]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/subsetting/subset-crs*
^|A |The map operation SHALL support a parameter `subset-crs` with the characteristics defined in the OpenAPI Specification 3.0 fragment
[source,YAML]
----
  crs:
    name: subset-crs
    in: query
    description: A URI of the coordinate reference system of the bbox and the map subset response. A list of all supported CRS values can be found under the collection metadata.
    required: false
    schema:
      type: string
    example: http://www.opengis.net/def/crs/OGC/1.3/CRS84
----
^|B |For Earthly data, the implementation SHALL support http://www.opengis.net/def/crs/OGC/1.3/CRS84 as a value. 
^|C |If the subset-crs is not indicated http://www.opengis.net/def/crs/OGC/1.3/CRS84 SHALL be assumed.
^|D |If the storage (native) CRS is known, the implementation SHALL support the storage CRS as a value. Other conformance classes may allow additional values (see crs parameter definition).
^|C |The implementation SHALL support CRS expressed as URIs or as safe CURIEs.
^|D |If no `subset` parameter referring to the axis of the CRS is indicated, the `subset-crs` SHALL be ignored.
|===

NOTE: A CURIE {authority}[-{objectType}]:{id} would map to the following OGC URI: http://www.opengis.net/def/{objectType}/{authority}/0/{id}. If -{objectType} is missing, the default object type is crs.