[[req_subsetting_bbox_crs]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/subsetting/bbox-crs*
^|A |The map retrieval operation SHALL support a parameter `bbox-crs` with the characteristics defined in the OpenAPI Specification 3.0 fragment
[source,YAML]
----
  bbox-crs:
    name: bbox-crs
    in: query
    description: A URI (or safe CURIE) of the coordinate reference system for the coordinates specified in the `bbox` parameter. The valid values are [OGC:CRS84], the native (storage) CRS (if different), or the output `crs` (if specified).
    required: false
    schema:
      type: string
    example: http://www.opengis.net/def/crs/OGC/1.3/CRS84
----
^|B |For Earthly data, the implementation SHALL support http://www.opengis.net/def/crs/OGC/1.3/CRS84 as a value.
^|C |If the bbox-crs is not indicated http://www.opengis.net/def/crs/OGC/1.3/CRS84 SHALL be assumed.
^|D |If the storage (native) CRS is known, the implementation SHALL support the storage CRS as a value. Other conformance classes may allow additional values (see crs parameter definition).
^|E |The implementation SHALL support CRS expressed as URIs or as safe CURIEs.
^|F |If the `bbox` parameter is not used, the `bbox-crs` SHALL be ignored.
|===

NOTE: A CURIE {authority}[-{objectType}]:{id} would correspond to the following OGC URI: http://www.opengis.net/def/{objectType}/{authority}/0/{id}. If -{objectType} is missing, the default object type is _crs_.
