[[req_subsetting_center_crs]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/subsetting/center-crs*
^|A |The map retrieval operation SHALL support a parameter `center-crs` with the characteristics defined in the OpenAPI Specification 3.0 fragment
[source,YAML]
----
  crs:
    name: subset-crs
    in: query
    description: A URI (or safe CURIE) of the coordinate reference system for the coordinates specified in the `center` parameter. The valid values are [OGC:CRS84], the native (storage) CRS (if different), or the output `crs` (if specified).
    required: false
    schema:
      type: string
    example: http://www.opengis.net/def/crs/OGC/1.3/CRS84
----
^|B |For Earthly data, the implementation SHALL support http://www.opengis.net/def/crs/OGC/1.3/CRS84 as a value.
^|C |If the `center-crs` is not used, http://www.opengis.net/def/crs/OGC/1.3/CRS84 SHALL be assumed.
^|D |If the storage (native) CRS is known, the implementation SHALL support the storage CRS as a value. Other requirements classes may allow additional values (see `crs` parameter definition).
^|E |The implementation SHALL support CRS expressed as URIs or as safe CURIEs.
^|F |If no `center` parameter is used, the `center-crs` SHALL be ignored.
|===

NOTE: A CURIE {authority}[-{objectType}]:{id} would map to the following OGC URI: http://www.opengis.net/def/{objectType}/{authority}/0/{id}. If -{objectType} is missing, the default object type is crs.
