[[req_background_bgcolor-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/background/bgcolor-definition*
^|A |The map operation SHALL support a parameter `bgcolor` to define a background color with the characteristics defined in the OpenAPI Specification 3.0 fragment
[source,YAML]
----
  bgcolor:
    name: bgcolor
    in: query
    description:
      Hexadecimal red-green-blue color value (0-255) or case-insensitive W3C web color name for the background color (default=0xFFFFFF). For a 6 digits hexadecimal value, the first and second digits specify the intensity of red, the third and fourth digits specify the intensity of green, and the fifth and sixth digits specify the intensity of blue.
    required: false
    style: form
    explode: false
    schema:
      type: string
      default: 0xFFFFFF
----
^|B |The map operation SHALL support a `bgcolor` parameter which can be an hexadecimal red-green-blue color value (0-255) or a case-insensitive https://www.w3.org/wiki/CSS/Properties/color/keywords[W3C web color name] for the background color of the map (default=0xFFFFFF). For a 6 digits hexadecimal value, the first and second digits specify the intensity of red, the third and fourth digits specify the intensity of green, and the fifth and sixth digits specify the intensity of blue.
^|C |If `bgcolor` is not specified, the server is free to choose a background color that is appropriate for the requested style, or 0xFFFFFF (white) if no such information is available.
|===
