[[req_background_bgcolor-definition]]
////
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/background/bgcolor-definition*
^|A |The map operation SHALL support a parameter `bgcolor` to define a background color with the characteristics defined in the OpenAPI Specification 3.0 fragment:
[source,YAML]
----
  bgcolor:
    name: bgcolor
    in: query
    description:
      Hexadecimal red-green-blue color value (0-255) or case-insensitive W3C web color name for the background color (default=0xFFFFFF). For a six digit hexadecimal value, the first and second digits specify the intensity of red. The third and fourth digits specify the intensity of green. The fifth and sixth digits specify the intensity of blue.
    required: false
    style: form
    explode: false
    schema:
      type: string
      default: 0xFFFFFF
----
^|B |The map operation SHALL support a `bgcolor` parameter which can be an hexadecimal red-green-blue color value (from 00 to FF, FF representing 255) or a case-insensitive https://www.w3.org/wiki/CSS/Properties/color/keywords[W3C web color name] for the background color of the map (default=0xFFFFFF). For a six-digit hexadecimal value, the first and second digits specify the intensity of red. The third and fourth digits specify the intensity of green. The fifth and sixth digits specify the intensity of blue.
^|C |If `bgcolor` is not specified, and either `transparent` is set to `false` or the output format cannot encode transparency, the server SHALL use the background color specified by the requested style.
|===
////

[requirement]
====
[%metadata]
identifier:: /req/background/bgcolor-definition
part:: The map operation SHALL support a parameter `bgcolor` to define a background color with the characteristics defined in the OpenAPI Specification 3.0 fragment:
+
[source,YAML]
----
  bgcolor:
    name: bgcolor
    in: query
    description:
      Hexadecimal red-green-blue color value (0-255) or case-insensitive W3C web color name for the background color (default=0xFFFFFF). For a six digit hexadecimal value, the first and second digits specify the intensity of red. The third and fourth digits specify the intensity of green. The fifth and sixth digits specify the intensity of blue.
    required: false
    style: form
    explode: false
    schema:
      type: string
      default: 0xFFFFFF
----
part:: The map operation SHALL support a `bgcolor` parameter which can be an hexadecimal red-green-blue color value (from 00 to FF, FF representing 255) or a case-insensitive https://www.w3.org/wiki/CSS/Properties/color/keywords[W3C web color name] for the background color of the map (default=0xFFFFFF). For a six-digit hexadecimal value, the first and second digits specify the intensity of red. The third and fourth digits specify the intensity of green. The fifth and sixth digits specify the intensity of blue.
part:: If `bgcolor` is not specified, and either `transparent` is set to `false` or the output format cannot encode transparency, the server SHALL use the background color specified by the requested style.
====
