[[req_background_map-success]]
[requirement]
====
[%metadata]
identifier:: /req/background/map-success
part:: The color of the map in the areas with no data SHALL be exactly the one specified in the `bgcolor`.
part:: The color in parts of the map outside of the valid areas of the projection / CRS SHALL be the one specified by `void-color`, or otherwise default to the same as the background color (whether specified by `bgcolor` or default).
part:: The transparency setting in parts of the map outside of the valid areas of the projection / CRS SHALL be the one specified by `void-transparent`, or otherwise default to the same as the background transparency setting (whether specified by `transparent` or default).
part:: In case the output format allows it and in the absence of the `transparent` parameter (or if it is `false`), the opacity (alpha value) of the map in the areas with no data SHALL be exactly 100% if `transparent` is `false` or 0% if `transparent` is `true`.
====

NOTE: If the renderer supports anti-aliasing, at the edges between data and no-data areas, the opacity may be a value between 0% and 100%.
