[[rec_scaling_map-success-scale]]
////
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/scaling/map-success-scale*
^|A |The resolution of the content represented in the map SHOULD be consistent with the `width` and `height` of the viewport indicated and should consider the display resolution (0.28 mm/pixel, unless the `mm-per-pixel` parameter is used) when applying symbology rules. These considerations should also be applied when simplifying the geometries for a vector format, such as KML or SVG.
|===
////

[recommendation]
====
[%metadata]
identifier:: /rec/scaling/map-success-scale
part:: The resolution of the content represented in the map SHOULD be consistent with the `width` and `height` of the viewport indicated and should consider the display resolution (0.28 mm/pixel, unless the `mm-per-pixel` parameter is used) when applying symbology rules. These considerations should also be applied when simplifying the geometries for a vector format, such as KML or SVG.
====