[[rec_scaling_max-width-height.adoc]]
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/scaling/max-width-height*
^|A |The service metadata may include a minimum and maximum width and height and product of both indicating what is the maximum values that the server will accept to create the map. Clients should not request a map subset with a width or a height greater than these limits and if they to, they should expect that the server will not be able to create a map. These characteristics are defined as (shown as OpenAPI Specification 3.0 fragment)

[source,YAML]
----

  x-OGC-limits:
    type: object
    properties:
      maps:
        type: object
        properties:
          maxWidth:
            type: integer
            description:
              Maximum width parameter value. If absent the server imposes no limit.
            example: 2048
          maxHeight:
            type: integer
            description:
              Maximum height parameter value. If absent the server imposes no limit.
            example: 2048
          maxPixels:
            type: integer
            description:
              Maximum  product of width and height parameter values. If absent the server imposes no limit.
            example: 4194304
----
^|C |An API instance may specify the maximum width and height by adding a `minimum` property to the `width` and `height` parameter definition in the OpenAPI as in this OpenAPI Specification 3.0 fragment
[source,YAML]
----
  width:
    name: width
    in: query
    description:
      Width of the viewport to present the response in pixel units (the map subset).
    required: false
    style: form
    explode: false
    schema:
      type: number
      minimun: 2048
  height:
    name: height
    in: query
    description:
      Height of the viewport to present the response in pixel units (the map subset).
    required: false
    style: form
    explode: false
    schema:
      type: number
      minimun: 2048
----
^|B |In the absence of the `maxWidth` or `maxPixels`, the client will assume that there is no limit in the parameter `width`. In the absence of the `maxHeight` or `maxPixels`, the client will assume that there is no limit in the parameter `height`.
|===

NOTE: this mimics the `maxWidth` and `maxHeight` elements in the WMS 1.3 _GetCabilities_ document.

NOTE: Service metadata can be embeded in the info section of the OpenAPI instance or in an independent document linked to the landing page with the rel="service-meta"
