[[rec_spatial-subsetting_map-outside-bounds]]
////
[width="90%",cols="2,6a"]
|===
^|*Recommendation {counter:rec-id}* |*/rec/spatial-subsetting/map-outside-bounds*
^|A |The server should try to honor the subsetting coordinates requested. For example, if the server has no data in the requested area, a map filled with the background color or transparent values based on the relevant query parameters specified should be returned. For example, if the subsetting coordinates requested are partially outside the server data, the area with no data SHOULD be filled with the background color or transparent values based on the relevant query parameters specified.
|===
////

[recommendation]
====
[%metadata]
identifier:: /rec/spatial-subsetting/map-outside-bounds
part:: The server should try to honor the subsetting coordinates requested. For example, if the server has no data in the requested area, a map filled with the background color or transparent values based on the relevant query parameters specified should be returned. For example, if the subsetting coordinates requested are partially outside the server data, the area with no data SHOULD be filled with the background color or transparent values based on the relevant query parameters specified.
====