[[req_tiles_multiltiles_mtc-multitiletype-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/tiles/multitiles/mtc-multitiletype-definition*
^|A |The operation SHALL support an optional a parameter `multitileType` that determines the type of the response and with the following characteristics (using an OpenAPI Specification 3.0 fragment):

[source,YAML]
----
  name: multiTileType
  in: query
  description:
    'When successful, the service will respond to a query in one of two ways. It can provide a file with links to each tile or or it will provide the tiles in a package. The package can still contain the description of each tile

    The allowed values for this parameter are `url`, `tiles` and `full`.'
  style: form
  schema:
    type: string
    default: tiles
    enum:
      - url
      - tiles
      - full
  example: full
----
^|B | If the value of the `multiTileType` parameter is set to `url` the server SHALL return a list of the selected tiles in a format following the `tileSet` schema. Each tile description in the list will contain a URL to download the tile later.
^|C | If the value of the `multiTileType` parameter is set to `tiles`  or if the parameter is not specified in the request, the server SHALL return a package (e.g. a ZIP file) that will include tiles as separated parts in the package.
^|D | If the value of the `multiTileType` parameter is set to `full` the server SHALL return the tiles and a list of the selected tiles (in a format following the `tileSet` schema) as part of a package.
|===
