[[req_png_content]]
////
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/png/content*
^|A |Every 200-response of the server with the media type image/png SHALL be a PNG document representing only one map.
^|B |The colors of the PNG SHALL represent the geospatial features or coverage values in the map.
^|C |The alpha channel of the PNG SHALL be used when partial transparency is required
^|D |All maps representing parts of the same resource or resources and using the same style SHALL follow the same portrayal rules
|===
////

[requirement]
====
[%metadata]
identifier:: /req/png/content
part:: Every 200-response of the server with the media type `image/png` SHALL be a PNG document representing only one map.
part:: The colors of the PNG SHALL represent the geospatial features or coverage values in the map.
part:: The alpha channel of the PNG SHALL be used when partial transparency is required
part:: All maps representing parts of the same resource or resources and using the same style SHALL follow the same portrayal rules
====

NOTE: The way the colors in the PNG format are mapped to geospatial features or coverage values is out of scope for the Maps API Standard. However, a common set of portrayal rules for all maps representing part of the same resource is essential, as maps are normally represented one after the other as a response to actions of the user (e.g. zoom and pan). 
