[[req_jpegxl_content]]

[requirement]
====
[%metadata]
identifier:: /req/jpegxl/content
part:: Every 200-response of the server with the media type `image/jxl` SHALL be a JPEG XL file representing only one map.
part:: The JPEG XL SHALL be a color image representing the geospatial features or coverage values in the map.
part:: All maps representing parts of the same resource or resources and using the same style SHALL follow the same portrayal rules.
====

NOTE: The way the colors in the JPEG XL are mapped to geospatial features or coverage values is out of scope of the Maps API Standard.
However, a common set of portrayal rules for all maps representing part of the same resource is essential, as maps are normally represented one after the other as a response to actions of the user (e.g., zoom and pan).

NOTE: JPEG XL is an ideal file format for all map types, due to its support for high image quality (including the possibility of lossless encoding), high compression ratio, high bit depth and translucency.
