== Requirement Class "Map BBox"

=== Overview

[[maps-bbox-overview]]

include::requirements/requirements_class_bbox.adoc[]

This extension describes how to subset a map by specifying a set of parameters that will determine its resolution (width, height, bounding box and CRS) as well as a few other supporting parameters

=== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of links. OGC API - Common already requires some links.

include::requirements/bbox/REQ_conformance-success.adoc[]

In the conformance page (typically in JSON format) the links follow the link schema defined in the OGC API - Common. The following is an example fragment of the response of an implementation of the OGC API – Maps draft specification with the maps extension conformance information page.

[[ConformancePageMapsMaps]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-maps-1/1.0/conf/core"
    "http://www.opengis.net/spec/ogcapi-maps-2/1.0/conf/bbox"
  ]
}
=================

=== Map resource
The OGC API - Maps - Part 1: Core defines the map resource. The core contains a minimum set of metadata to enable a client application to formulate a map request.

This class defines the extension to the core needed to formulate a bounding box subset.

The geospatial resource may expose a geospatial extent. This does not precluded that the map resource presents its own extent that will be similar or smaller to the geospatial extent resource (the API may opt to expose only a part of the geospatial resource as a map subsets)

include::requirements/bbox/REQ_extent-in-WGS84.adoc[]

include::requirements/bbox/REQ_crs-and-extent.adoc[]

NOTE: The parameters `noSubsets` `fixedWidth` and `fixedHeight` present in the WMS have been deprecated and removed form this API. To get a similar functionality as `fixedWidth` and `fixedHeight` use the OGC API - Tiles.

NOTE: These parameters reflect limitations in the cartography. A too detailed product does not look good in low resolution and the server my decide not to serve it. In some APIs it is common that there is another geospatial resource in the API that is more appropriate out of these scale range.

NOTE: These are indented to limit the work load of the server by providing limitations in size of the outputs of the subset. If your width and height parameters are related to the size of the device screen, please consider that new devices are being build with more and more pixels and a reasonable limit last year may be too restrictive with the emerging devices.

=== Map subset by bounding box

==== Operation

The core of Part 1 defines how to add a {styleId} parameter to a map to make it retrievable as a subset. This standard specifies the parameters needed to subset a map an retrieve fragments of it.

An example of a resource that can be retrieved as map subsets is a feature collection (/collections/{collectionId}/map/{styleId}).

The supported encodings, or more precisely the media types of the supported encodings, can be determined from the API definition. The desired encoding is selected using HTTP content negotiation. In addition the parameters specified by the core, other parameters should be added.

==== Parameter crs
This parameter indicates the CRS of the data rendered in the map as well as the CRS used by the bbox parameter.
include::requirements/bbox/REQ_crs-definition.adoc[]

==== Parameter bbox
This parameter indicates the bounding box of the subset of the map to retrieved (in the crs coordinates). In this OPC API extension the bbox parameter values are defined considering the exterior edges of the pixels of the viewport defined by the width and height. In other words, the relation of the Bounding Box to the map pixel matrix is that the bounding box goes around the "outside" of the pixels of the map rather than through the centers of the map's border pixels (which is the usual case for coverages). In this context, individual pixels represent a cell area on the ground.

include::requirements/bbox/REQ_bbox-definition.adoc[]

NOTE: This parameter uses the comma (",") as the separator between the coordinates. Additional white space will not be used to delimit list items. The comma character should not be escaped (IETF RFC 2396).

include::recommendations/bbox/PER_map-op.adoc[]

==== Parameters style, transparency and bgcolor
These parameters are defined at the OGC API - maps; core and are not modified by this extension

==== Response

A successful response to a map bbox GET operation will be consistent with the media type of resource requested. This draft specification does not impose any media type or file format and map responses may be in JPEG, PNG or other appropriate format (including vector based formats such as KML or SVG). It is also possible to respond an HTML page with the image embedded and, eventually, with additional controls.

include::requirements/bbox/REQ_map-success.adoc[]

include::recommendations/bbox/PER_map-encoding.adoc[]

Normally, the content partially outside the map bounding box will be clipped at the extent of the bounding box. This can be done efficiently when map subsets are in raster format (e.g. map tiles). However, maps containing features in vector format may not clip features that are partially outside to ensure continuity of features or for performance.

include::recommendations/bbox/REC_map-success-scale.adoc[]

==== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the parameter value `crs` is not available by the server for this resource or the parameters values `bbox`, `width`, `height` are out-of-range, or the map is not provided due to lack of data in the area, the status code of the response will be `404`.
