== Conformance
This standard defines *TBD* requirements / conformance classes.

The standardization targets of all conformance classes are "web services".

The main requirements class is:

* <<rc_core,Core>>.

The _Core_ specifies requirements that all Map Tile APIs have to implement.

*TBD* requirements classes depend on the _Core_ and <enter their purpose here>:

C**apture additional requirements classes here**

Conformance with this standard shall be checked using all the relevant tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

In order to conform to this OGC® interface standard, a software implementation shall choose to implement:
* Any one of the conformance levels specified in Annex A (normative).
* Any one of the Distributed Computing Platform profiles specified in Annexes TBD through TBD (normative).

All requirements-classes and conformance-classes described in this document are owned by the standard(s) identified.
