[[req_spatial-subsetting_center-crs]]
////
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/spatial-subsetting/center-crs*
^|A |The map retrieval operation SHALL support a parameter `center-crs` with the characteristics defined in the OpenAPI Specification 3.0 fragment:
[source,YAML]
----
  crs:
    name: center-crs
    in: query
    description: A URI (or safe CURIE) of the coordinate reference system for the coordinates specified in the `center` parameter. The valid values are [OGC:CRS84], the native (storage) CRS (if different), or the output `crs` (if specified).
    required: false
    schema:
      type: string
    example: https://www.opengis.net/def/crs/OGC/1.3/CRS84
----
^|B |For Earth centric data, https://www.opengis.net/def/crs/OGC/1.3/CRS84 SHALL be supported as a value.
^|C |If the `center-crs` is not used, https://www.opengis.net/def/crs/OGC/1.3/CRS84 SHALL be assumed.
^|D |If the storage (native) CRS is known, the storage CRS SHALL be supported as a value. Other requirements classes may allow additional values (see crs parameter definition).
^|E |CRS expressed as URIs or as safe CURIEs SHALL be supported.
^|F |If no `center` parameter is used, the `center-crs` SHALL be ignored.
|===
////

[requirement]
====
[%metadata]
identifier:: /req/spatial-subsetting/center-crs
part:: The map retrieval operation SHALL support a parameter `center-crs` with the characteristics defined in the OpenAPI Specification 3.0 fragment:
+
[source,YAML]
----
  crs:
    name: center-crs
    in: query
    description: A URI (or safe CURIE) of the coordinate reference system for the coordinates specified in the `center` parameter. The valid values are [OGC:CRS84], the native (storage) CRS (if different), or the output `crs` (if specified).
    required: false
    schema:
      type: string
    example: https://www.opengis.net/def/crs/OGC/1.3/CRS84
----
part:: For Earth centric data, https://www.opengis.net/def/crs/OGC/1.3/CRS84 SHALL be supported as a value.
part:: If the `center-crs` is not used, https://www.opengis.net/def/crs/OGC/1.3/CRS84 SHALL be assumed.
part:: If the storage (native) CRS is known, the storage CRS SHALL be supported as a value. Other requirements classes may allow additional values (see crs parameter definition).
part:: CRS expressed as URIs or as safe CURIEs SHALL be supported.
part:: If no `center` parameter is used, the `center-crs` SHALL be ignored.
====

NOTE: A CURIE {authority}[-{objectType}]:{id} would map to the following OGC URI: https://www.opengis.net/def/{objectType}/{authority}/0/{id}. If -{objectType} is missing, the default object type is crs.
