[[req_spatial-subsetting_subset-definition]]

[requirement]
====
[%metadata]
identifier:: /req/spatial-subsetting/subset-definition
part:: The implementation SHALL support a `subset` parameter conforming to the following Augmented Backus Naur Form (ABNF) fragment:
+
[source,ABNF]
----
  SubsetSpec =       "subset" "=" axisName "(" intervalOrSingle ")"
  intervalOrSingle = interval / single
  interval =         low ":" high
  low =              single
  high =             single
  single =           number

  Where:
     `axisName` is an abbreviation identifying an axis starting by a lowercase or uppercase letter A-Z, optionally followed by any number of alphanumeric characters
     `number` is an integer or floating-point number.
----
part:: Axis names `Lat` and `Lon` SHALL be supported for geographic CRS and `E` and `N` for projected CRS, which are to be interpreted as the best matching spatial axis in the CRS definition.
part:: If a third spatial dimension is supported (if the resource's spatial extent bounding box is three dimensional), the implementation SHALL also support a `h` dimension. This is the elevation above the ellipsoid in EPSG:4979 or CRS84h for geographic CRS and `z` for projected CRS, which are to be interpreted as the vertical axis in the CRS definition.
part:: A 4xx error status code SHALL be returned if an axis name in the subset parameter value does not correspond to one of the axes of the subsetting CRS ^2^.
part:: If the _interval_ values fall entirely outside the range of valid values defined for the identified axis, a 204 or 404 status code SHALL be returned.
part:: For a CRS where an axis can wrap around, such as subsetting across the dateline (anti-meridian) in a geographic CRS, a _low_ value greater than _high_ SHALL be supported to indicate an extent crossing that wrapping point.
part:: Coordinates SHALL be interpreted as values for the named axis of the CRS specified in the `subset-crs` parameter value or in https://www.opengis.net/def/crs/OGC/1.3/CRS84 (https://www.opengis.net/def/crs/OGC/1.3/CRS84h for vertical dimension) if the `subset-crs` parameter is missing.
part:: If the `subset` parameter including any of the dimensions corresponding to those of the map bounding box is used with a `bbox` and/or `center` parameter, the server SHALL return a 4xx error.
part:: Multiple `subset` parameters SHALL be interpreted, as if all dimension subsetting values were provided in a single `subset` parameter (comma separated)^1^.
+
^1^ Example: `subset=Lat(-90:90)&subset=Lon(-180:180)` is equivalent to `subset=Lat(-90:90),Lon(-180:180)`
+
^2^ Note that this is only valid of the spatial dimensions. The 'additional' dimensions rely on the names of the extent of the collection.
====

NOTE: A subset parameter for https://www.opengis.net/def/crs/OGC/1.3/CRS84 will read as subset=Lon(left_lon:right_lon),Lat(lower_lat:upper_lat).

NOTE: When the _interval_ values fall partially outside of the range of valid values defined by the CRS for the identified axis, the service is expected to return the non-empty portion of the resource resulting from the subset.

NOTE: For the operation of returning a map, there normally is no value in preserving dimensionality, therefore a _slicing_ operation (using the _point_ notation) is usually equivalent to
a _trimming_ operation (using the _interval_ notation) when the low and high bounds of an interval are the same. Therefore, use of the point notation is encouraged in these cases.

NOTE: For typical 2D map requests, a trimming operation (interval) is always used (never a single slicing value) for the dimensions corresponding to the latitude (or northing) and longitude (or easting) dimensions,
while a slicing or trimming operation for a third vertical dimension may be provided, where that third dimension is flattened on the map.
For a response format where the content can actually be in three dimension, an interval for the third dimension would not need to be flattened.
In the case of more specialized maps, such as a vertical profile, or a temporal graph for a vegetation index at a particular spatial location, a slicing operation with single values might be appropriate for all spatial dimensions.
