[[req_spatial-subsetting_bbox-definition]]
////
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/spatial-subsetting/bbox-definition*
^|A |The map operation SHALL support a parameter `bbox` with the characteristics defined in the OpenAPI Specification 3.0 fragment:
[source,YAML]
----
  bbox:
    name: bbox
    in: query
    description:
      Bounding box of the rendered map. The bounding box is provided as four or six coordinates

      * Lower left corner, coordinate axis 1
      * Lower left corner, coordinate axis 2
      * Minimum value, coordinate axis 3 (optional)
      * Upper right corner, coordinate axis 1
      * Upper right corner, coordinate axis 2
      * Maximum value, coordinate axis 3 (optional)

      The coordinate reference system and axis order of the values are indicated in the `bbox-crs` parameter or if the parameter is missing in https://www.opengis.net/def/crs/OGC/1.3/CRS84
    required: false
    schema:
      type: array
      oneOf:
      - minItems: 4
        maxItems: 4
      - minItems: 6
        maxItems: 6
      items:
        type: number
        format: double
    style: form
    explode: false
----
^|B |`bbox` SHALL be a comma separated list of four or six floating point numbers.
If the bounding box consists of six numbers, the first three numbers are the coordinates of the lower bound corner of a three-dimensional bounding box and the last three are the coordinates of the upper bound corner.
The axis order is determined by the `bbox-crs` parameter value or longitude and latitude if the parameter is missing (https://www.opengis.net/def/crs/OGC/1.3/CRS84 axis order for a 2D bounding box,
https://www.opengis.net/def/crs/OGC/1.3/CRS84h for a 3D bounding box).
For example in https://www.opengis.net/def/crs/OGC/1.3/CRS84 the order is left_long, lower_lat, right_long, upper_lat.
^|C |If the `bbox` parameter is used together with the `center` and/or with a `subset` parameter including any of the dimensions corresponding to those of the map bounding box, the server SHALL return a 400 client error.
|===
////

[requirement]
====
[%metadata]
identifier:: /req/spatial-subsetting/bbox-definition
part:: The map operation SHALL support a parameter `bbox` with the characteristics defined in the OpenAPI Specification 3.0 fragment:
+
[source,YAML]
----
  bbox:
    name: bbox
    in: query
    description:
      Bounding box of the rendered map. The bounding box is provided as four or six coordinates

      * Lower left corner, coordinate axis 1
      * Lower left corner, coordinate axis 2
      * Minimum value, coordinate axis 3 (optional)
      * Upper right corner, coordinate axis 1
      * Upper right corner, coordinate axis 2
      * Maximum value, coordinate axis 3 (optional)

      The coordinate reference system and axis order of the values are indicated in the `bbox-crs` parameter or if the parameter is missing in https://www.opengis.net/def/crs/OGC/1.3/CRS84
    required: false
    schema:
      type: array
      oneOf:
      - minItems: 4
        maxItems: 4
      - minItems: 6
        maxItems: 6
      items:
        type: number
        format: double
    style: form
    explode: false
----
part:: `bbox` SHALL be a comma separated list of four or six floating point numbers.
+
If the bounding box consists of six numbers, the first three numbers are the coordinates of the lower bound corner of a three-dimensional bounding box and the last three are the coordinates of the upper bound corner.
The axis order is determined by the `bbox-crs` parameter value or longitude and latitude if the parameter is missing (https://www.opengis.net/def/crs/OGC/1.3/CRS84 axis order for a 2D bounding box,
https://www.opengis.net/def/crs/OGC/1.3/CRS84h for a 3D bounding box).
For example in https://www.opengis.net/def/crs/OGC/1.3/CRS84 the order is left_long, lower_lat, right_long, upper_lat.
part:: If the `bbox` parameter is used together with the `center` and/or with a `subset` parameter including any of the dimensions corresponding to those of the map bounding box, the server SHALL return a 400 client error.
====