[[req_tiles_core_mtcs-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/tiles/core/mtcs-success*
^|A |A successful execution of the operation SHALL be reported as a response with a HTTP status code `200`.
^|B |The content of that response SHALL be consistent with the format requested and be inside or intersect with the spatial extent of the geographical area represented by the 'bbox' and `scaleDenominator`.
^|C |If list of the tiles has been requested, the content of that response SHALL contain a tileSet document be based upon the following OpenAPI 3.0 schema:
[source,YAML]
----
  tileSet:
    description:
      This is the response for a multiple tiles request.
    required:
      - type
    type: array
    items:
      $ref: '#/components/schemas/tileSetEntry'
  tileSetEntry:
    description:
      This is an entry on a multiple tiles request.
    type: object
    required:
      - tileURL
      - tileMatrix
      - tileRow
      - tileCol
    properties:
      tileURL:
        type: string
        format: uri
      tileMatrix:
        type: string
      tileRow:
        type: number
      tileCol:
        type: number
      width:
        type: number
        description:
          The width of the tile in rendering device pixels. If it exceeds the visual display area be should cut when displayed
      height:
        type: number
        description:
          The height of the tile in rendering device pixels. If it exceeds the visual display area be should cut when displayed
      top:
        type: number
        description:
          Vertical position from the top of the visual display area in pixels. Negative value means that the left side of the tile is outside the top-left corner of the display and should be cut when displayed
      left:
        type: number
        description:
          Horizontal position from the left of the visual display area in pixels. Negative value means that the left side of the tile is outside the top-left corner of the display and should be cut when displayed
----
^|D |When a package is being returned and the package format supports expressing file paths of its parts (such as the ZIP file), each tile in the package SHALL have a path following the template: `{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}.{file-extension}`. {file-extension} is the file extension that corresponds to the media type (e.g "jpg" for image/jpeg).
|===
