[[req_tiles_core_stc-tmslink.adoc]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/tiles/core/stc-tmslink*
^|A |The content of the response of a successful execution SHALL contain a _tiles_ object in addition to other information present in the collection in the `/collections` response.
^|B |the _tiles_ object SHALL contain a property called _tileMatrixSetLinks_ with a list of _tileMatrixSetLink_ objects following a data model defined in the clause 7.3 of OGC 17-083r2. In the core _tileMatrixSetLink_ is only used for referencing the supported TileMatrixSets for the tiles limiting it to the following schema (expressed in OpenAPI Specification 3.0 fragment):
[source,YAML]
----
  tileMatrixSetLink-set:
    description: This list tileMatrixSetLink as defined in OGC 17-083r2 supported by this collectionId.
    type: array
    items:
      $ref: '#/components/schemas/tileMatrixSetLink-entry'
  tileMatrixSetLink-entry:
    type: object
    required:
      - tileMatrixSet
    properties:
      tileMatrixSet:
        type: string
        example: 'WebMercatorQuad'
      tileMatrixSetURI:
        type: string
        format: uri
        example: 'http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad'
----
^|C |This core does not provide any mechanism to defined TileMatrixSets so if this mechanism is not provided in an extension, the tileMatrixSetURI should point to one of the 8 URIs defined in the OGC 17-083r2 Annex D.
|===
