[[req_checkpoint_tiles_cp-success]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/checkpoint/tiles/cp-success*
^|A |If the `scalesOfChangedItems` property is present in the request, the response SHALL contain an interval of scales affected by changes. If it is not included all scales are affected SHALL be include
^|B |When the `changeSetType` parameter forces a response using the `changeSet` schema, the content of that response SHALL use the `changeSetTiles` schema instead (that extents `changeSet` by adding a scale interval). The `changeSetTiles` OpenAPI 3.0 follows the schema:

[source,YAML]
----
  allOf:
  - $ref: '#/components/schemas/changeSet'
  - type: object
    properties:
      scalesOfChangedItems:
        type: object
        required:
          - minScaleDenominator:
          - maxScaleDenominator:
        properties:
          minScaleDenominator:
            type: number
            format: double
          maxScaleDenominator:
            type: number
            format: double
----
^|C |When a package is being returned and the package format supports expressing file paths of its parts (such as the ZIP file), each tile in the package SHALL have a path following the template: `{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}.{file-extension}`. {file-extension} is the file extension that corresponds to the media type (e.g "jpg" for image/jpeg).
|===
