[[req_crs_crs]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/crs/crs*
^|A |The map operation SHALL support a parameter `crs` with the characteristics defined in the OpenAPI Specification 3.0 fragment
[source,YAML]
----
  crs:
    name: crs
    in: query
    description: A coordinate reference system of the map response. A list of all supported CRS values can be found under the collection metadata.
    required: false
    schema:
      type: string
    example: http://www.opengis.net/def/crs/OGC/1.3/CRS84
----
^|B |The implementation SHALL support any of the CRSs listed in the collection (or collections) description. If the list of supported CRS is not present, only http://www.opengis.net/def/crs/OGC/1.3/CRS84 SHALL be supported.
^|C |If the spatial subsetting conformance class is supported, the bbox-crs and the subset-crs SHALL additionally support value specified in the crs parameter.
^|D |The implementation SHALL support CRS expressed as URIs or as safe CURIEs.
|===

NOTE: When no crs parameters is specified, please refer to the core conformance class to know about the default crs.

NOTE: A CURIE {authority}[-{objectType}]:{id} would map to the following OGC URI: http://www.opengis.net/def/{objectType}/{authority}/0/{id}. If -{objectType} is missing, the default object type is crs.