[[req_crs_crs-definition]]
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/crs/crs-definition*
^|A |The map operation SHALL support a parameter `crs` with the characteristics defined in the OpenAPI Specification 3.0 fragment:
[source,YAML]
----
  crs:
    name: crs
    in: query
    description: A coordinate reference system of the map response. A list of all supported CRS values can be found under the collection metadata.
    required: false
    schema:
      type: string
    example: https://www.opengis.net/def/crs/OGC/1.3/CRS84
----
^|B |Any of the CRSs listed in the collection (or collections) description SHALL be supported. If the list of supported CRS is not present, only https://www.opengis.net/def/crs/OGC/1.3/CRS84 SHALL be supported.
^|C |If the spatial subsetting requirements class is supported, the `bbox-crs` and the `subset-crs` SHALL additionally support value specified in the crs parameter.
^|D |CRS expressed as URIs or as safe CURIEs SHALL be supported.
|===

NOTE: When no crs parameters are specified, please refer to the Maps API core conformance class to know about the default crs.

NOTE: A CURIE `{authority}[-{objectType}]:{id}` would map to the following OGC URI: `https://www.opengis.net/def/{objectType}/{authority}/0/{id}`. If `-{objectType}` is missing, the default object type is crs.
